# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2025-2026 Jean-François Barthélémy and Anthony Soive (Cerema, UMR MCD)

using ChemistryLab
using DynamicQuantities
using ForwardDiff
using LinearAlgebra
using SciMLBase
using Test

include("reference_species.jl")

# ── Surfaces of three charge planes, against PHREEQC's CD-MUSIC ──────────────
#
# Goethite as Hiemstra and Van Riemsdijk (1996) describe it, two kinds of
# surface groups of charge −1/2 on one surface, in three placements of the
# charges: the basic Stern model of their Fig. 6, the three planes of their
# Table 2 with a monodentate phosphate complex whose charge is shared between
# the 0- and 1-planes, and the ion pairs in the 1-plane of the triple-layer
# model of Davis et al. (1978). Generated by test/reference/phreeqc_cd_music.py,
# with the activity coefficients one on both sides, so that what is compared is
# the surface model.
#
# The aqueous species that react are built from the constants PHREEQC used,
# recorded in the fixture (its ionization constant of water and of phosphoric
# acid), on the energies of slop98's H2O, H⁺, Na⁺, Cl⁻ and PO₄³⁻; the surface
# species from the constants of the papers, as every surface test here does.

const CD_MUSIC = reference_oracle("phreeqc_cd_music")
const RT25_CP = ChemistryLab.R_GAS * 298.15
_g0_cp(v) = SymbolicFunc(v * u"J/mol")
_lk_cp(x) = RT25_CP * log(10) * x

# The goethite of one case at the totals of one PHREEQC point: the system, its
# state, the two families and the model.
function _goethite(case, pt; C2 = case.C2, model = nothing)
    h2o, hp, na, cl, po4 = reference_species(("H2O@", "H+", "Na+", "Cl-", "PO4-3"))
    G(s) = s[:ΔₐG⁰](T = 298.15)
    function aqueous(name, g)
        s = Species(name; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
        s[:ΔₐG⁰] = _g0_cp(g)
        return s
    end
    oh = aqueous("OH-", G(h2o) - G(hp) - _lk_cp(CD_MUSIC.log_k_water))
    lkp(name) = getproperty(CD_MUSIC.log_k_phosphate, Symbol(name))
    hpo4 = aqueous("HPO4-2", G(po4) + G(hp) - _lk_cp(lkp("HPO4-2")))
    h2po4 = aqueous("H2PO4-", G(po4) + 2G(hp) - _lk_cp(lkp("H2PO4-")))
    h3po4 = aqueous("H3PO4", G(po4) + 3G(hp) - _lk_cp(lkp("H3PO4")))

    # The surface species, energies from the log K of their formation from the
    # free group, plane charges from the case: the intrinsic −1/2 of the group
    # on the 0-plane, the change of charge of the complexation on each plane.
    function surface(name, g, c)
        s = Species(name; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        s[:ΔₐG⁰] = _g0_cp(g)
        return with_plane_charges(s, c...)
    end
    kH, kp = case.log_k_H, CD_MUSIC.log_k_ion_pair
    pair = case.pair_plane == 2 ? [0.0, 0.0, 1.0] : [0.0, 1.0, 0.0]
    cation = [-0.5, 0.0, 0.0] .+ pair
    anion = [0.5, 0.0, 0.0] .- pair
    s_free = surface("XsOH", 0.0, (-0.5, 0.0, 0.0))
    s_prot = surface("XsOH2+", -_lk_cp(kH), (0.5, 0.0, 0.0))
    s_na = surface("XsOHNa+", G(na) - _lk_cp(kp), cation)
    s_cl = surface("XsOH2Cl", G(cl) - _lk_cp(kH + kp), anion)
    t_free = surface("XtO", 0.0, (-0.5, 0.0, 0.0))
    t_prot = surface("XtOH+", -_lk_cp(kH), (0.5, 0.0, 0.0))
    t_na = surface("XtONa+", G(na) - _lk_cp(kp), cation)
    t_cl = surface("XtOHCl", G(cl) - _lk_cp(kH + kp), anion)
    s_others = [s_prot, s_na, s_cl]
    if case.phosphate !== nothing
        dz = case.phosphate.dz
        push!(
            s_others, surface(
                "XsOPO3-2", G(hp) + G(po4) - G(h2o) - _lk_cp(case.phosphate.log_k),
                (-0.5 + dz[1], dz[2], dz[3]),
            ),
        )
    end

    model = something(model, ChargePlanes(; area = CD_MUSIC.area, C1 = case.C1, C2))
    support = SurfaceSupport("goethite", nothing, FixedSurfaceArea(CD_MUSIC.area))
    n_s, n_t = sum(pt.uni), sum(pt.tri)
    fs = SiteFamily("Xs", s_free, s_others; capacity = TotalSiteAmount(n_s), support, model)
    ft = SiteFamily("Xt", t_free, [t_prot, t_na, t_cl]; capacity = TotalSiteAmount(n_t), support, model)

    species = [h2o, hp, oh, na, cl, po4, hpo4, h2po4, h3po4, s_free, s_others..., t_free, t_prot, t_na, t_cl]
    cs = ChemicalSystem(species, [h2o, hp, na, cl, po4, s_free, t_free]; site_families = [fs, ft])
    n = Any[fill(1.0e-12u"mol", length(cs.species))...]
    at(sym) = findfirst(s -> symbol(s) == sym, cs.species)
    n[at("H2O@")] = moles_of_water() * u"mol"
    # The system's sodium and chloride: what stays in solution and what pairs.
    n[at("Na+")] = (pt.Na + pt.uni[3] + pt.tri[3]) * u"mol"
    n[at("Cl-")] = (pt.Cl + pt.uni[4] + pt.tri[4]) * u"mol"
    case.phosphate === nothing || (n[at("PO4-3")] = case.phosphate.total * u"mol")
    n[at("XsOH")] = n_s * u"mol"
    n[at("XtO")] = n_t * u"mol"
    return (; cs, state = ChemicalState(cs, n), model, at)
end

function _solve_goethite(case, pt; kwargs...)
    g = _goethite(case, pt; kwargs...)
    des = DualEquilibriumSolver(g.cs, DiluteSolutionModel())
    b = Float64.(g.cs.SM.A) * Float64[ustrip(us"mol", x) for x in g.state.n]
    q = Base.RefValue{Any}(nothing)
    eq = SciMLBase.solve(des, g.state; b, constraint = FixedpH(pt.pH), parameters = q)
    cert = optimality_certificate(des, eq; b, constraint = FixedpH(pt.pH))
    n = Float64[ustrip(us"mol", x) for x in eq.n]
    uni = [n[g.at(s)] for s in ("XsOH", "XsOH2+", "XsOHNa+", "XsOH2Cl")]
    case.phosphate === nothing || push!(uni, n[g.at("XsOPO3-2")])
    tri = [n[g.at(s)] for s in ("XtO", "XtOH+", "XtONa+", "XtOHCl")]
    return (; g..., des, eq, cert, n, q = q[], uni, tri, b)
end

@testsection "three charge planes: the model" begin
    @testset "construction refuses what it cannot mean" begin
        @test_nowarn ChargePlanes(; area = 105.0, C1 = 0.9)
        @test ChargePlanes(; area = 105.0, C1 = 0.9).C2 == Inf
        @test ChargePlanes(; area = 1.05e6u"cm^2", C1 = 0.9u"F/m^2", C2 = 5.0u"F/m^2").area ≈ 105.0
        @test_throws ArgumentError ChargePlanes(; area = 0.0, C1 = 0.9)
        @test_throws ArgumentError ChargePlanes(; area = 105.0, C1 = 0.0)
        @test_throws ArgumentError ChargePlanes(; area = 105.0, C1 = 0.9, C2 = -1.0)
        @test_throws ArgumentError ChargePlanes(; area = 105.0, C1 = 0.9, ε_r = 0.0)
        @test_throws ArgumentError ChargePlanes(; area = 105.0u"m^2/kg", C1 = 0.9)
        # One electrostatic model per surface: a plane-resolved one does not
        # decorate another.
        dl = DiffuseLayer(; area = 105.0)
        @test_throws ArgumentError ChargePlanes(; area = 105.0, C1 = 0.9, base = dl)
        @test_throws ArgumentError DiffuseLayer(; area = 105.0, base = ChargePlanes(; area = 105.0, C1 = 0.9))
        m = ChargePlanes(; area = 105.0, C1 = 0.9)
        @test is_electrostatic(m) && needs_ionic_strength(m) && needs_potential_unknown(m)
        @test !is_gradient_consistent(m)
        @test !supports_multidentate(m)
        @test supports_multidentate(ChargePlanes(; area = 105.0, C1 = 0.9, base = GainesThomasMixing()))
        @test m.ε_r ≈ water_relative_permittivity(298.15) rtol = 1.0e-12
    end

    @testset "the charges a species puts on the planes" begin
        s = Species("XsOH2Cl"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        @test ChemistryLab._plane_charges(s) == (0.0, 0.0, 0.0)
        @test ChemistryLab._plane_charges(Species("XsOH2+"; aggregate_state = AS_SURFACE)) == (1.0, 0.0, 0.0)
        c = with_plane_charges(s, 0.5, 0, -1)
        @test ChemistryLab._plane_charges(c) == (0.5, 0.0, -1.0)
        @test charge(c) == charge(s) && symbol(c) == symbol(s)
        @test ChemistryLab._plane_charges(with_plane_charges(s, 0.25)) == (0.25, 0.0, 0.0)
    end

    @testset "a family's two counts of charge agree up to the group's own" begin
        sup = SurfaceSupport("goethite", nothing, FixedSurfaceArea(105.0))
        m = ChargePlanes(; area = 105.0, C1 = 0.9)
        sp(name) = Species(name; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        fam(free, others) = SiteFamily(
            "Xs", free, others; capacity = TotalSiteAmount(1.0e-4), support = sup, model = m,
        )
        free = with_plane_charges(sp("XsOH"), -0.5)
        @test_nowarn fam(free, [with_plane_charges(sp("XsOH2+"), 0.5)])
        @test_nowarn fam(free, [with_plane_charges(sp("XsOH2Cl"), 0.5, 0, -1)])
        # +1 on the planes for a member whose formula gains +1 and whose group
        # carries −1/2: the counts would part on protonation.
        @test_throws ArgumentError fam(free, [with_plane_charges(sp("XsOH2+"), 1.0)])
        # Without plane charges each member puts its formula's on plane 0.
        @test_nowarn fam(sp("XsOH"), [sp("XsOH2+")])
    end

    @testset "one surface, one set of planes" begin
        # Two families on one support must agree on its capacitances, as they
        # must on its area.
        case = only(c for c in CD_MUSIC.cases if c.name == "basic_stern")
        pt = case.series[1].points[1]
        g = _goethite(case, pt)
        @test length(only(ChemistryLab._potential_supports(g.cs))) == 2
        fams = g.cs.site_families
        other = ChargePlanes(; area = CD_MUSIC.area, C1 = 1.0, C2 = case.C2)
        f2 = SiteFamily(
            "Xt", fams[2].free_site, fams[2].complexes;
            capacity = fams[2].capacity, support = fams[2].support, model = other,
        )
        cs = ChemicalSystem(g.cs.species, g.cs.SM.primaries; site_families = [fams[1], f2])
        @test_throws ArgumentError ChemistryLab._potential_supports(cs)
    end

    @testset "the three equations of the planes" begin
        m = ChargePlanes(; area = 105.0, C1 = 0.9, C2 = 5.0)
        c = [(0.5, 0.0, 0.0), (-0.5, 0.0, 1.0), (-0.25, -2.25, 0.0)]
        n = [3.0e-4, 2.0e-5, 8.0e-5]
        I, T = 0.01, 298.15
        ψ = charge_planes_potentials(m, c, n, I, T)
        σ = [ChemistryLab.FARADAY * sum(c[j][p] * n[j] for j in 1:3) / m.area for p in 1:3]
        f = ChemistryLab.FARADAY / (ChemistryLab.R_GAS * T)
        @test ψ[1] - ψ[2] ≈ f * σ[1] / m.C1 rtol = 1.0e-12
        @test ψ[2] - ψ[3] ≈ f * (σ[1] + σ[2]) / m.C2 rtol = 1.0e-12
        κ = sqrt(8 * m.ε_r * VACUUM_PERMITTIVITY * ChemistryLab.R_GAS * T * 1000)
        @test ψ[3] ≈ 2 * asinh(sum(σ) / (κ * sqrt(I))) rtol = 1.0e-12
        # C2 = Inf merges the outer two planes: the basic Stern model.
        bs = charge_planes_potentials(ChargePlanes(; area = 105.0, C1 = 0.9), c, n, I, T)
        @test bs[2] == bs[3]
        # Both capacitances infinite and every charge on the 0-plane: the
        # diffuse layer alone.
        gc = ChargePlanes(; area = 105.0, C1 = Inf, C2 = Inf)
        z = [1.0, -1.0, 0.0]
        dl = charge_planes_potentials(gc, [(zj, 0.0, 0.0) for zj in z], n, I, T)
        @test all(==(dl[1]), dl)
        @test dl[1] ≈ diffuse_layer_potential(DiffuseLayer(; area = 105.0), z, n, I, T) rtol = 1.0e-14
        # The derivatives, by automatic differentiation: one more mole of a
        # species of charges c raises ψ̃₀ − ψ̃₁ by F² c₀/(𝒜 C₁ RT).
        J = ForwardDiff.jacobian(x -> collect(charge_planes_potentials(m, c, x, I, T)), n)
        for j in 1:3
            @test J[1, j] - J[2, j] ≈ f * ChemistryLab.FARADAY * c[j][1] / (m.area * m.C1) rtol = 1.0e-12
            @test J[2, j] - J[3, j] ≈ f * ChemistryLab.FARADAY * (c[j][1] + c[j][2]) / (m.area * m.C2) rtol = 1.0e-12
        end
    end
end

@testsection "three charge planes against PHREEQC's CD-MUSIC" begin
    @test CD_MUSIC.database_md5 == "4d3f4378c46498730d569cacc37c4fa8"

    # The site amounts PHREEQC formed from the densities and the area agree with
    # this package's Avogadro constant to its own: it is the PHREEQC amounts
    # that are used, so that the two surfaces carry the same sites.
    hv(name) = ustrip(literature_value("Hiemstra1996", name))
    pt1 = CD_MUSIC.cases[1].series[1].points[1]
    @test sum(pt1.uni) ≈ hv("singly_coordinated_site_density") * CD_MUSIC.area / AVOGADRO rtol = 1.0e-4
    @test sum(pt1.tri) ≈ hv("triply_coordinated_site_density") * CD_MUSIC.area / AVOGADRO rtol = 1.0e-4

    worst = Dict{String, NTuple{2, Float64}}()
    for case in CD_MUSIC.cases
        wf, wψ, certified, total = 0.0, 0.0, 0, 0
        for ser in case.series, pt in ser.points
            r = _solve_goethite(case, pt)
            total += 1
            r.cert.stationarity < 1.0e-8 && (certified += 1)
            # A diffuse layer: a self-consistent speciation, as for DiffuseLayer.
            @test r.cert.scope === :self_consistent
            # The titrant, then the three potentials.
            @test length(r.q) == 4
            ψ = r.q[2:4] ./ (ChemistryLab.FARADAY / RT25_CP)
            wψ = max(wψ, maximum(abs.(ψ .- pt.psi)))
            for (got, want) in ((r.uni, pt.uni), (r.tri, pt.tri))
                wf = max(wf, maximum(abs.(got ./ sum(got) .- want ./ sum(want))))
            end
        end
        @test certified == total
        worst[case.name] = (wf, wψ)
    end
    @info "ChargePlanes against PHREEQC CD-MUSIC: worst site fraction, worst potential (V)" worst
    # Measured at 3e-5 to 5e-5 in the fractions and 0.03 to 0.05 mV where the
    # potential of the diffuse layer is small, 7e-4 and 0.26 mV in the basic
    # Stern model, where it carries most of the potential at low ionic strength.
    for name in ("triple_layer", "three_plane_phosphate")
        @test worst[name][1] < 1.0e-4
        @test worst[name][2] < 1.0e-4
    end
    @test worst["basic_stern"][1] < 1.0e-3
    @test worst["basic_stern"][2] < 5.0e-4

end
