# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2025-2026 Jean-François Barthélémy and Anthony Soive (Cerema, UMR MCD)

using ChemistryLab
using ChemistryLab: value
using DynamicQuantities
using JSON
using SciMLBase
using Test

include("reference_species.jl")

# ── A ClaySor 2023 subset ─────────────────────────────────────────────────────
#
# Generated by `test/reference/phreeqc_claysor.py`.
#
# ClaySor 2023 is the 2SPNE SC/CE model of Bradbury and Baeyens: two-site
# protolysis, NON-electrostatic, plus cation exchange. Three edge site families
# and one exchanger on one clay — which is the first case in this package where
# FOUR site budgets share a support, and the reason it is worth a gate of its
# own beyond the constants it brings.
#
# WHAT THIS IS NOT. ClaySor's constants were fitted against PSI/Nagra TDB 2020,
# which this repository does not have and does not ship. Both sides here run the
# sorption model over `phreeqc.dat`'s aqueous chemistry, so this tests the
# implementation of the model — site budgets, protolysis, competition, the
# exchange convention — and is not a reproduction of ClaySor. The distinction is
# the same one as using a surface constant fitted with a diffuse layer in a model
# without one, and the fixture carries it as a field rather than a hope.
const CLAYSOR = reference_oracle("phreeqc_claysor")

const RT_CS = ChemistryLab.R_GAS * 298.15
_g0_cs(v) = SymbolicFunc(v * u"J/mol")
_mRT(logK) = -RT_CS * log(10.0^logK)

"""
The log K of one reaction of the subset, by the species it produces — read from
the fixture, which read it from ClaySor, so no constant is typed here.
"""
function _logK(produces)
    for r in vcat(CLAYSOR.reactions.surface, CLAYSOR.reactions.exchange)
        occursin(produces, split(r.equation, "=")[2]) && return r.log_K
    end
    error("no reaction producing $produces in the fixture")
end

function _claysor_system(; chloride)
    h2o, hp, oh, na, ca, cl =
        reference_species(("H2O@", "H+", "OH-", "Na+", "Ca+2", "Cl-"))
    G(s) = ustrip(us"J/mol", s[:ΔₐG⁰](T = 298.15u"K", P = 1.0e5u"Pa"; unit = true))

    sf(sym, g) = begin
        s = Species(sym; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        s[:ΔₐG⁰] = _g0_cs(g)
        s
    end

    support = SurfaceSupport(
        "Na-montmorillonite", nothing,
        BETSurfaceArea(CLAYSOR.specific_area_m2_per_g * 1000.0),   # m²/kg
    )

    # The three edge families. ClaySor writes them `Mnt_s`, `Mnt_v`, `Mnt_w`;
    # here they are pseudo-elements, because a PHREEQC site name would be read
    # as chemistry — `Mnt_sOH` parses as elements, which is the trap the site
    # symbols exist to avoid.
    families = SiteFamily[]
    species = Any[h2o, hp, oh, na, ca, cl]
    for (sym, phreeqc, capacity) in (
            ("Xs", "Mnt_s", CLAYSOR.sites_mol_per_g.var"Mnt_sOH"),
            ("Xv", "Mnt_v", CLAYSOR.sites_mol_per_g.var"Mnt_vOH"),
            ("Xw", "Mnt_w", CLAYSOR.sites_mol_per_g.var"Mnt_wOH"),
        )
        free = sf("$(sym)OH", 0.0)
        prot = sf("$(sym)OH2+", _mRT(_logK("$(phreeqc)OH2+")))
        depr = sf("$(sym)O-", _mRT(_logK("$(phreeqc)O-")))
        push!(
            families, SiteFamily(
                phreeqc, free, [prot, depr];
                capacity = TotalSiteAmount(capacity * CLAYSOR.grams), support,
            )
        )
        append!(species, (free, prot, depr))
    end

    # And the exchanger, in the convention PHREEQC's EXCHANGE block uses.
    naX = sf("NaXm", 0.0)
    caX = sf("CaXm2", _mRT(_logK("Mntx2Ca")) + G(ca) - 2 * G(na))
    push!(
        families, SiteFamily(
            "Mntx", naX, [caX];
            capacity = TotalSiteAmount(CLAYSOR.cec_mol_per_g * CLAYSOR.grams),
            support, model = GainesThomasMixing(),
        )
    )
    append!(species, (naX, caX))

    # `identity.` narrows the `Vector{Any}` the loop above builds: the
    # constructor dispatches on the element type, and `Any` matches nothing.
    sp = identity.(species)
    primaries = identity.([h2o, hp, na, ca, cl, species[7], species[10], species[13], naX])
    cs = ChemicalSystem(sp, primaries; site_families = identity.(families))
    idx = Dict(symbol(sp) => k for (k, sp) in enumerate(cs.species))

    n0 = Any[fill(1.0e-14u"mol", length(cs.species))...]
    n0[idx["H2O@"]] = moles_of_water() * u"mol"
    n0[idx["Na+"]] = CLAYSOR.na * u"mol"
    n0[idx["Ca+2"]] = CLAYSOR.ca * u"mol"
    n0[idx["Cl-"]] = chloride * u"mol"
    n0[idx["XsOH"]] = CLAYSOR.sites_mol_per_g.var"Mnt_sOH" * CLAYSOR.grams * u"mol"
    n0[idx["XvOH"]] = CLAYSOR.sites_mol_per_g.var"Mnt_vOH" * CLAYSOR.grams * u"mol"
    n0[idx["XwOH"]] = CLAYSOR.sites_mol_per_g.var"Mnt_wOH" * CLAYSOR.grams * u"mol"
    n0[idx["NaXm"]] = CLAYSOR.cec_mol_per_g * CLAYSOR.grams * u"mol"
    return cs, ChemicalState(cs, n0), idx
end

@testsection "a published clay sorption model, end to end" begin

    @testset "the model is read, not retyped" begin
        # Every constant in the system above came from ClaySor through the
        # fixture. These are the values, asserted once so a silent change in the
        # reader shows up here rather than as a drifting comparison.
        @test _logK("Mnt_sOH2+") ≈ 4.5
        @test _logK("Mnt_sO-") ≈ -7.9
        @test _logK("Mntx2Ca") ≈ 0.396
        @test CLAYSOR.cec_mol_per_g ≈ 0.00087
        @test CLAYSOR.sites_mol_per_g.var"Mnt_sOH" ≈ 2.0e-6
        # And the fixture says what it is not.
        @test occursin("not a reproduction", lowercase(CLAYSOR.not_a_reproduction))
        @test occursin("TDB 2020", CLAYSOR.not_a_reproduction)
        @test CLAYSOR.model_licence == "CC-BY-4.0"
    end

    @testset "four site budgets on one clay" begin
        cs, st, idx = _claysor_system(; chloride = CLAYSOR.na + 2 * CLAYSOR.ca)
        @test length(cs.site_families) == 4
        # One support, four families — the case the surface potential had to be
        # taught about, and which here is non-electrostatic by construction.
        @test length(unique(surface_support(f).name for f in cs.site_families)) == 1
        @test all(!needs_potential_unknown(f.model) for f in cs.site_families)
        # Three families count particles, one counts charge equivalents.
        @test count(f -> f.model isa GainesThomasMixing, cs.site_families) == 1
    end

    @testset "matched against PHREEQC" begin
        des_cache = nothing
        worst_edge, worst_exchange, certified = 0.0, 0.0, 0
        for pt in CLAYSOR.points
            # The ionic strength is matched to PHREEQC's, whose own titrant
            # moves it; the chloride carries the difference.
            mH, mOH = 10.0^(-pt.pH), 10.0^(pt.pH - 14)
            chloride = 2 * pt.I - CLAYSOR.na - 4 * CLAYSOR.ca - mH - mOH
            cs, st, idx = _claysor_system(; chloride)
            des = DualEquilibriumSolver(cs, DaviesActivityModel())
            b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(pt.pH),
                parameters = Base.RefValue{Any}(nothing),
            )
            cert = optimality_certificate(des, eq; b = b, constraint = FixedpH(pt.pH))
            cert.stationarity < 1.0e-8 || continue
            certified += 1
            n = Float64[ustrip(us"mol", x) for x in eq.n]

            # The site budgets close, which is the first thing to check and the
            # one a wrong capacity would break. The tolerance is set by the
            # 1e-14 floor every species starts at, not by the solve: on a
            # budget of 2e-6 that floor is already 1e-8 relative.
            @test n[idx["XsOH"]] + n[idx["XsOH2+"]] + n[idx["XsO-"]] ≈
                CLAYSOR.sites_mol_per_g.var"Mnt_sOH" rtol = 1.0e-6
            @test n[idx["NaXm"]] + 2 * n[idx["CaXm2"]] ≈ CLAYSOR.cec_mol_per_g rtol = 1.0e-8

            for (ours, theirs) in (
                    ("XsOH", "Mnt_sOH"), ("XsOH2+", "Mnt_sOH2+"), ("XsO-", "Mnt_sO-"),
                    ("XwOH", "Mnt_wOH"), ("XwO-", "Mnt_wO-"),
                )
                want = getproperty(pt.species, Symbol(theirs))
                want > 1.0e-12 || continue
                worst_edge = max(worst_edge, abs(n[idx[ours]] / want - 1))
            end
            for (ours, theirs) in (("NaXm", "MntxNa"), ("CaXm2", "Mntx2Ca"))
                want = getproperty(pt.species, Symbol(theirs))
                worst_exchange = max(worst_exchange, abs(n[idx[ours]] / want - 1))
            end
        end

        @test certified == length(CLAYSOR.points)
        @info "ClaySor subset against PHREEQC" worst_edge worst_exchange
        # THE TWO NUMBERS DIFFER BY FOUR ORDERS OF MAGNITUDE, and the reason is
        # structural rather than accidental. The edge sites see only the proton,
        # whose activity `FixedpH` prescribes on both sides, so no aqueous
        # activity model enters and the comparison is of the surface model
        # alone: 2.5e-6. The exchanger sees the sodium and calcium activities,
        # where Davies and PHREEQC's extended Debye-Hückel genuinely differ:
        # 2.0e-2. Measured, not asserted — the next block turns the second into
        # an attribution.
        @test worst_edge < 1.0e-4
        @test worst_exchange < 0.03
    end

    @testset "and the exchange gap is the aqueous model, measured" begin
        # Running the identical system under two aqueous models separates the
        # surface model from the solution it sits in, which is the only way to
        # say what a residual is. Same protocol as the zinc edge.
        pt = CLAYSOR.points[4]                     # pH 7, mid-range
        mH, mOH = 10.0^(-pt.pH), 10.0^(pt.pH - 14)
        chloride = 2 * pt.I - CLAYSOR.na - 4 * CLAYSOR.ca - mH - mOH
        gaps = map((DiluteSolutionModel(), DaviesActivityModel())) do model
            cs, st, idx = _claysor_system(; chloride)
            des = DualEquilibriumSolver(cs, model)
            b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(pt.pH),
                parameters = Base.RefValue{Any}(nothing),
            )
            n = Float64[ustrip(us"mol", x) for x in eq.n]
            maximum(
                abs(n[idx[o]] / getproperty(pt.species, Symbol(t)) - 1)
                    for (o, t) in (("NaXm", "MntxNa"), ("CaXm2", "Mntx2Ca"))
            )
        end
        ideal_gap, davies_gap = gaps
        @info "ClaySor exchange, by aqueous model" ideal = ideal_gap davies = davies_gap
        # Ideal activities are badly off on a divalent exchange; Davies is not.
        @test ideal_gap > 0.1
        @test davies_gap < 0.03
        @test ideal_gap / davies_gap > 5
    end
end
