# Cross-code reference test for the kinetics/equilibrium coupling.
#
# Calcite dissolves at a *constant* rate, so the kinetic half of Leal's system is
# analytic and every difference of rate-law convention between the two codes
# drops out. What is left is the question that matters: does the equilibrium
# partition follow nₑ(t) = φ(bₑ(t))?
#
# The oracle is generated by test/reference/reaktoro_coupling.py. Measured worst
# relative deviation over the trajectory: 0.3 % at t = 0, rising to 4.3 % at
# 3600 s, and always on CO₂@ — which sits at 2.3e-8 mol.

include("reference_species.jl")

# The oracle's output, read from its fixture: the aqueous partition at each
# sampled time, for calcite dissolving at a constant rate into pure water.
const RKC_FIXTURE = reference_oracle("reaktoro_coupling")
const RKC = Dict(
    float(smp.t) => Dict(String(k) => v for (k, v) in pairs(smp.amounts))
        for smp in RKC_FIXTURE.samples
)
const K_RATE = RKC_FIXTURE.rate

@testset "Reaktoro reference: kinetics/equilibrium coupling" begin
    data = datapath("cemdata18-thermofun.json")
    dict = Dict(symbol(s) => s for s in build_species(data))
    aq = ["H2O@", "H+", "OH-", "CO2@", "HCO3-", "CO3-2", "Ca+2", "CaOH+", "Ca(CO3)@", "Ca(HCO3)+"]
    cs = ChemicalSystem([dict[s] for s in vcat(aq, "Cal")], ["H2O@", "H+", "Ca+2", "CO3-2", "Zz"])
    nm = symbol.(cs.species); idx(s) = findfirst(==(s), nm)
    spc = Dict(s => cs.species[idx(s)] for s in nm)
    rxn = Reaction(
        OrderedDict(spc["Cal"] => 1),
        OrderedDict(spc["Ca+2"] => 1, spc["CO3-2"] => 1);
        symbol = "Cal_diss", equal_sign = '→'
    )
    st = zeros(Float64, length(nm))
    st[idx("Cal")] = -1.0; st[idx("Ca+2")] = 1.0; st[idx("CO3-2")] = 1.0
    kr = KineticReaction(rxn, (T, P, t, n, lna, n0) -> K_RATE, idx("Cal"), st)

    n = Any[fill(0.0u"mol", length(nm))...]
    n[idx("H2O@")] = RKC_FIXTURE.n_H2O * u"mol"; n[idx("Cal")] = 0.05u"mol"
    state = ChemicalState(cs, n)
    kp = KineticsProblem(
        cs, [kr], state, (0.0u"s", 3600.0u"s");
        equilibrium_solver = EquilibriumSolver(cs, DiluteSolutionModel(), OptimaOptimizer())
    )
    ks = KineticsSolver(;
        ode_solver = Rodas5P(), reltol = 1.0e-8, abstol = 1.0e-14,
        saveat = [0.0, 600.0, 1800.0, 3600.0]
    )
    sol = integrate(kp, ks)
    @test length(sol.t) == 4
    # The ODE state is (bₑ, nₖ); the equilibrium species are recovered by
    # φ(bₑ) — exactly what the oracle computes.
    sub = ChemistryLab._equilibrium_subsystem(cs, kp.idx_equilibrium)
    subnm = symbol.(sub.species)
    es = EquilibriumSolver(sub, DiluteSolutionModel(), OptimaOptimizer())
    n_be = size(kp.Ae, 1)
    for (ti, t) in enumerate(sol.t)
        haskey(RKC, t) || continue
        be = collect(sol.u[ti][1:n_be])
        guess = Any[fill(1.0e-10u"mol", length(subnm))...]
        guess[findfirst(==("H2O@"), subnm)] = RKC_FIXTURE.n_H2O * u"mol"
        eq = ChemistryLab.SciMLBase.solve(es, ChemicalState(sub, guess); b = be)
        v = [ustrip(us"mol", x) for x in eq.n]
        ref = RKC[t]
        worst = 0.0; wsp = ""
        for (k, s) in enumerate(subnm)
            haskey(ref, s) || continue
            ref[s] > 1.0e-10 || continue
            r = abs(v[k] / ref[s] - 1)
            if r > worst
                worst = r; wsp = s
            end
        end
        @test worst < 0.05
    end
end
