# The chloride end member of CSHQ, and the database it ships in.
#
# `data/cemdata18-chloride.json` is GENERATED by data/chloride/regenerate.jl and
# vendored: CEMDATA18 verbatim, with one end member, CSHQ-Cl = (CaCl2)0.5,
# appended. Its Gibbs energy is fitted on the sorption tests of Hirao et al.
# (2005), and that is the only fitted number; data/chloride/member.jl writes the
# end member and models the tests, and this file includes it. What is asserted:
# that the shipped file is what the generator writes, that its value is the
# minimum of the fit it records, that the phase is built only from that
# database, the Ca/Si trend the end member was chosen on, and the effect of the
# cation, which nothing was chosen or fitted on.

using JSON, Logging
include("reference_species.jl")
include(joinpath(pkgdir(ChemistryLab), "data", "chloride", "member.jl"))

@testsection "Chloride end member of CSHQ" begin
    base = JSON.parsefile(datapath("cemdata18-thermofun.json"); dicttype = Dict{String, Any})
    ext = JSON.parsefile(datapath("cemdata18-chloride.json"); dicttype = Dict{String, Any})
    by_symbol(db) = Dict(String(s["symbol"]) => s for s in db["substances"])
    B, E = by_symbol(base), by_symbol(ext)
    cand = ChlorideMember.SHIPPED
    member = ChlorideMember.member_symbol(cand)
    entry = E[member]
    prov = entry["chloride_provenance"]
    δ = prov["delta_J_per_mol"]

    @testset "a strict superset, with one end member added" begin
        @test issubset(keys(B), keys(E))
        @test setdiff(keys(E), keys(B)) == Set([member])
        gibbs(s) = get(get(s, "sm_gibbs_energy", Dict()), "values", nothing)
        @test all(gibbs(E[k]) == gibbs(B[k]) for k in keys(B))
        @test prov["kind"] == "fitted"
        @test prov["source"]["doi"] == literature("Hirao2005").source["doi"]
        @test ext["chloride_extension"]["added_substances"] == [member]
    end

    subs = build_species(datapath("cemdata18-thermofun.json"); verbose = false)
    byname = Dict(symbol(s) => s for s in subs)

    @testset "the shipped entry is the one the generator writes" begin
        # The same record, rebuilt here from the recorded δ.
        rebuilt = ChlorideMember.member_entry(cand, base, byname, δ)
        for key in ("sm_gibbs_energy", "sm_enthalpy", "sm_entropy_abs", "sm_heat_capacity_p", "sm_volume")
            @test entry[key]["values"] ≈ rebuilt[key]["values"] rtol = 1.0e-12
        end
        @test entry["formula"] == ChlorideMember.member_formula(cand)
        # The reaction it is formed by balances in atoms and in charge.
        ext_subs = Dict(symbol(s) => s for s in build_species(datapath("cemdata18-chloride.json"); verbose = false))
        cl = ext_subs[member]
        lhs = Dict{Symbol, Float64}()
        for (s, ν) in ChlorideMember.composition(cand), (el, k) in atoms_charge(ext_subs[s])
            lhs[el] = get(lhs, el, 0.0) + ν * k
        end
        @test all(isapprox(get(lhs, el, 0.0), Float64(get(atoms_charge(cl), el, 0)); atol = 1.0e-12) for el in union(keys(lhs), keys(atoms_charge(cl))))
        # And the Gibbs energy of that reaction, from the species the file
        # builds, is δ at the reference temperature.
        G(s) = ustrip(us"J/mol", s[:ΔₐG⁰](T = ChlorideMember.T_REF * u"K", P = 1.0e5u"Pa"; unit = true))
        @test G(cl) - sum(ν * G(ext_subs[s]) for (s, ν) in ChlorideMember.composition(cand)) ≈ δ atol = 1.0e-6
    end

    model = HKFActivityModel(å = 0.0, Ḃ = gems_bdot(), Kₙ = 0.0)
    w = ustrip(literature_value("HongGlasser1999", "water_content_high_CaSi"))
    @test prov["gel_water_fraction"] == w
    f = ChlorideMember.forward(cand, subs, base; model, water_fraction = w)
    pts = ChlorideMember.calibration_points()

    @testset "the recorded fit, and that it is a minimum" begin
        @test prov["chloride_mol_per_L"] == pts.chloride
        @test prov["bound_measured_mmol_per_g"] == pts.bound
        r = f(δ)
        # Every point at the 20 °C of the tests. A route of the certified
        # cascade built its state at 25 °C until 0.24.0: where it was the one
        # that succeeded, as it was under Windows at 1 mol/L, the point was
        # certified at the wrong temperature, 0.19 low in pH, and the next ones
        # started from it.
        @info "Hirao test, as computed here" Ca_Si = r.r bound = r.bound held = r.held
        @test all(temperature(st) == 293.15u"K" for st in r.states)
        @test r.bound ≈ prov["bound_model_mmol_per_g"] atol = 1.0e-8
        ssr(x) = sum(abs2, f(x).bound .- pts.bound)
        s0 = ssr(δ)
        @test ssr(δ - 100) > s0 && ssr(δ + 100) > s0
        # What the fit is worth, pinned: -4.9 kJ/mol, within 0.03 mmol/g at 0.5
        # mol/L, 0.05 low at 1 mol/L, four times the measurement at 0.1.
        @test δ ≈ -4907 atol = 1
        @test prov["delta_uncertainty_J_per_mol"] ≈ 308 atol = 1
        @test all(abs.(r.bound .- [0.1384, 0.325, 0.2927]) .< 5.0e-5)
        # The gel takes water from the solution as it rehydrates, which the
        # depletion reads as chloride released: at 1 mol/L the end member holds
        # 0.41 mmol/g where the measurement would see 0.29.
        @test r.held[3] - r.bound[3] ≈ 0.122 atol = 5.0e-4
    end

    ext_species = build_species(datapath("cemdata18-chloride.json"); verbose = false)
    xbyname = Dict(symbol(s) => s for s in ext_species)

    @testset "CSHQ_Cl is built from its database only" begin
        with = build_solid_solutions(datapath("solid_solutions.toml"), xbyname)
        cshq_cl = only(p for p in with if name(p) == "CSHQ_Cl")
        @test length(end_members(cshq_cl)) == 7
        # With CEMDATA18 alone the entry is skipped, and without a warning.
        without = @test_logs min_level = Logging.Warn build_solid_solutions(datapath("solid_solutions.toml"), byname)
        @test !any(name(p) == "CSHQ_Cl" for p in without)
        # CSHQ and CSHQ_Cl describe one gel, and declaring both is refused.
        cshq = only(p for p in with if name(p) == "CSHQ")
        sp = vcat([xbyname[s] for s in ("H2O@", "H+", "OH-", "Ca+2", "SiO2@", "Na+", "K+", "Cl-")], end_members(cshq_cl))
        @test_throws ErrorException ChemicalSystem(sp, CEMDATA_PRIMARIES; solid_solutions = [cshq, cshq_cl])
    end

    @testset "the Ca/Si trend the end member was chosen on" begin
        # Chloride binding by C-S-H grows with its Ca/Si (Zibara et al. 2008).
        # The candidate written after NaSiOH fitted the tests as well and bound
        # less at the higher Ca/Si; this one binds more, as recorded.
        t = ChlorideMember.calcium_trend(ext_species, xbyname[member]; model)
        @test t.ratio_high > t.ratio_low
        @test t.high > t.low
        @test [t.low, t.high] ≈ prov["calcium_trend_held_per_Si"] rtol = 1.0e-8
        rej = prov["rejected_candidate"]
        @test rej["calcium_trend_held_per_Si"][2] < rej["calcium_trend_held_per_Si"][1]
    end

    @testset "the cation, which nothing was fitted or chosen on" begin
        # At equal chloride, more is bound from CaCl2 than from NaCl (Tran et
        # al. 2018, after the measurements they cite), on a gel made at Ca/Si
        # 1.4 in 0.3 mol of chloride per kilogram of water: twice as much here.
        cs = ChlorideMember.gel_system(ext_species, xbyname[member])
        k = findfirst(s -> symbol(s) == member, cs.species)
        function charged(x)
            st = ChemicalState(cs; T = 293.15u"K")
            set_quantity!(st, "Lim", 1.4u"mol")
            set_quantity!(st, "Amor-Sl", 1.0u"mol")
            set_quantity!(st, "H2O@", 55.51u"mol")
            x < 1 && set_quantity!(st, "Na+", 0.3 * (1 - x) * u"mol")
            x > 0 && set_quantity!(st, "Ca+2", 0.15 * x * u"mol")
            set_quantity!(st, "Cl-", 0.3u"mol")
            return st
        end
        # The cation is exchanged in steps from the NaCl solution, each solve
        # starting from the last, up to nine tenths of the chloride as CaCl2: a
        # budget with no sodium at all would leave the sodium species, NaSiOH
        # among them, pinned at the floor with nothing to say.
        steps = range(0.0, 0.9; length = 10)
        A = Float64.(cs.SM.A)
        eqs, certs = equilibrate_path(charged(0.0), [A * ustrip.(us"mol", charged(x).n) for x in steps]; model)
        @test all(c.optimal for c in certs)
        na, ca = ustrip(us"mol", first(eqs).n[k]), ustrip(us"mol", last(eqs).n[k])
        @info "chloride end member: NaCl against CaCl2" na ca
        @test ca > na
        @test ca / na ≈ 1.98 atol = 5.0e-3
    end
end
