# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2025-2026 Jean-François Barthélémy and Anthony Soive (Cerema, UMR MCD)

using ChemistryLab
using DynamicQuantities
using JSON
using ForwardDiff
using LinearAlgebra
using SciMLBase
using Test

include("reference_species.jl")

const RT25_DL = ChemistryLab.R_GAS * 298.15
_g0_dl(v) = SymbolicFunc(v * u"J/mol")

# Ferrihydrite's weak sites at Dzombak and Morel's own site density — 2.0e-4 mol
# on 53.4 m², which is 3.75 µmol/m² or 2.25 sites/nm². That number is not a
# detail: a surface a thousand times more dilute carries a thousandth of the
# charge per unit area, raises no potential worth the name, and would let a
# diffuse layer that did nothing at all pass for one that worked. The first
# attempt at this fixture made exactly that mistake.
#
# A background electrolyte is here because a diffuse layer is *screened*: with
# no ions in solution Gouy-Chapman diverges, and the whole content of the model
# is how the answer moves with the ionic strength.
function _ddl_system(;
        logK1, logK2, n_sites, area, m_na, m_cl, model,
    )
    # The aqueous side is the database's, not this file's (see
    # test/reference_species.jl). The surface side is built from the log K under
    # test, because that is the oracle and no database carries it.
    h2o, hp, oh, na, cl = reference_species(("H2O@", "H+", "OH-", "Na+", "Cl-"))

    free = Species("XsOH"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    free[:ΔₐG⁰] = _g0_dl(0.0)
    prot = Species("XsOH2+"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    prot[:ΔₐG⁰] = _g0_dl(-RT25_DL * log(10.0^logK1))
    depr = Species("XsO-"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    depr[:ΔₐG⁰] = _g0_dl(-RT25_DL * log(10.0^logK2))

    support = SurfaceSupport("hfo", nothing, FixedSurfaceArea(area))
    family = SiteFamily(
        "Xs", free, [prot, depr];
        capacity = TotalSiteAmount(n_sites), support, model,
    )
    species = [h2o, hp, oh, na, cl, free, prot, depr]
    cs = ChemicalSystem(species, [h2o, hp, na, cl, free]; site_families = [family])

    n = Any[fill(1.0e-12u"mol", length(cs.species))...]
    n[1] = moles_of_water() * u"mol"
    n[4] = m_na * u"mol"
    n[5] = m_cl * u"mol"
    n[6] = n_sites * u"mol"
    return cs, ChemicalState(cs, n)
end

# ── The matched PHREEQC case ──────────────────────────────────────────────────
#
# Generated by `test/reference/phreeqc_hfo_surface.py --case protolysis-ddl`.
#
# Three ionic strengths rather than one, because that is the whole content of a
# diffuse layer: a model that got the charge right and the screening wrong would
# reproduce one series and miss the other two. The ionic strength PHREEQC
# computed travels with each point, because PHREEQC reaches its pH by adding
# HCl and the background is therefore not the one that was asked for — at pH 4
# in 1 mM NaCl it is 14 % higher. Matching it is what keeps this a comparison of
# surface models rather than of titration bookkeeping.
# generated by test/reference/phreeqc_hfo_surface.py
# python       3.12.14
# phreeqpython 1.6.2
# database     phreeqc.dat  md5 fca384eb269fda632fcefa6f74c8f90e
# model        diffuse layer (PHREEQC's default SURFACE), weak sites, no metal
# sites        0.0002 mol on 53.4 m2 = 3.75 umol/m2
# log K        protonation 7.29, deprotonation -8.93

const PHREEQC_DIFFUSE_LAYER = reference_oracle("phreeqc_diffuse_layer")

# The ionic strength PHREEQC reports, reproduced on this side by prescribing the
# chloride rather than by hoping the two titrations agree.
# The kilogram of water is the solvent's own molar mass times its amount,
# not 0.018015 typed here.
_kgw_dl() = 1.0     # by construction: the solvent amount IS one kilogram
function _ddl_case(ser, pt; model)
    mH, mOH = 10.0^(-pt.pH), 10.0^(pt.pH - 14)
    kgw = _kgw_dl()
    return _ddl_system(;
        logK1 = PHREEQC_DIFFUSE_LAYER.logK_protonation,
        logK2 = PHREEQC_DIFFUSE_LAYER.logK_deprotonation,
        n_sites = PHREEQC_DIFFUSE_LAYER.n_sites,
        area = PHREEQC_DIFFUSE_LAYER.area,
        m_na = ser.nacl * kgw,
        m_cl = (2 * pt.I - ser.nacl - mH - mOH) * kgw,
        model,
    )
end

@testsection "a diffuse layer, and the elimination that stops working" begin

    @testset "construction refuses what it cannot mean" begin
        # Both sides of every guard, which is the rule in this repository and
        # the reason the capacitance guards are exercised here too: they went in
        # with the constant-capacitance model and went in untested.
        @test_nowarn DiffuseLayer(; area = 53.4)
        @test_throws ArgumentError DiffuseLayer(; area = 0.0)
        @test_throws ArgumentError DiffuseLayer(; area = -1.0)
        @test_throws ArgumentError DiffuseLayer(; area = 53.4, ε_r = 0.0)
        @test_throws ArgumentError DiffuseLayer(; area = 53.4, ε_r = -78.0)
        @test_throws ArgumentError DiffuseLayer(; area = 53.4, scale = -0.1)
        @test_throws ArgumentError DiffuseLayer(; area = 53.4, scale = 1.1)
        @test_nowarn DiffuseLayer(; area = 53.4, scale = 0.0)
        @test_nowarn DiffuseLayer(; area = 53.4, scale = 1.0)

        @test_nowarn ConstantCapacitance(; C = 1.06, area = 53.4)
        @test_throws ArgumentError ConstantCapacitance(; C = 0.0, area = 53.4)
        @test_throws ArgumentError ConstantCapacitance(; C = -1.0, area = 53.4)
        @test_throws ArgumentError ConstantCapacitance(; C = 1.06, area = 0.0)
        @test_throws ArgumentError ConstantCapacitance(; C = 1.06, area = -53.4)

        # Units are accepted and converted; a wrong dimension is refused rather
        # than stripped, which is the whole point of `_area_si`.
        @test DiffuseLayer(; area = 53.4u"m^2").area ≈ 53.4
        @test DiffuseLayer(; area = 534_000.0u"cm^2").area ≈ 53.4
        @test_throws ArgumentError DiffuseLayer(; area = 53.4u"m^2/kg")

        # Two charge planes are not two potentials added together.
        cc = ConstantCapacitance(; C = 1.06, area = 53.4)
        dl = DiffuseLayer(; area = 53.4)
        @test_throws ArgumentError DiffuseLayer(; area = 53.4, base = cc)
        @test_throws ArgumentError ConstantCapacitance(; C = 1.06, area = 53.4, base = dl)
        # but decorating an ordinary mixing model is exactly what they are for,
        # and the decoration is transparent to what the base decides — for BOTH
        # electrostatic models, because a trait that delegates for one and not
        # the other is a trap rather than a trait.
        @test_nowarn DiffuseLayer(; area = 53.4, base = GainesThomasMixing())
        @test supports_multidentate(DiffuseLayer(; area = 53.4, base = GainesThomasMixing()))
        @test !supports_multidentate(DiffuseLayer(; area = 53.4))
        @test supports_multidentate(
            ConstantCapacitance(; C = 1.06, area = 53.4, base = GainesThomasMixing()),
        )
        @test supports_multidentate(
            ConstantCapacitance(; C = 1.06, area = 53.4, base = VanselowMixing()),
        )
        @test !supports_multidentate(ConstantCapacitance(; C = 1.06, area = 53.4))
    end

    @testset "the constants are the package's own, not PHREEQC's" begin
        # ε_r comes from the Johnson-Norton model this package already carries
        # for HKF, evaluated once at construction.
        @test DiffuseLayer(; area = 1.0).ε_r ≈ water_relative_permittivity(298.15) rtol = 1.0e-12
        @test water_relative_permittivity(298.15) ≈ 78.2451 rtol = 1.0e-4
        # and it is temperature-dependent, which is why a room-temperature
        # calibration is not transferable to a hydrating paste in silence
        @test water_relative_permittivity(333.15) < 0.9 * water_relative_permittivity(298.15)

        # κ = √(8 ε_r ε₀ R T ρ): PHREEQC writes 0.1174 into its source, we
        # compute 0.117215. Agreeing with it while using a different dielectric
        # constant is a stronger statement than reusing its arithmetic.
        κ = sqrt(
            8 * water_relative_permittivity(298.15) * VACUUM_PERMITTIVITY *
                ChemistryLab.R_GAS * 298.15 * 1000
        )
        @test κ ≈ 0.117215 rtol = 1.0e-5
        @test abs(κ / 0.1174 - 1) < 3.0e-3
        @test VACUUM_PERMITTIVITY ≈ 8.8541878128e-12 rtol = 1.0e-12
    end

    @testset "the traits say what the models cost" begin
        dl = DiffuseLayer(; area = 53.4)
        cc = ConstantCapacitance(; C = 1.06, area = 53.4)
        id = IdealSiteMixing()

        @test is_electrostatic(dl) && is_electrostatic(cc) && !is_electrostatic(id)
        @test needs_ionic_strength(dl)
        @test !needs_ionic_strength(cc) && !needs_ionic_strength(id)
        # A constant capacitance is the gradient of a quadratic form; a diffuse
        # layer is the gradient of nothing.
        @test is_gradient_consistent(cc) && is_gradient_consistent(id)
        @test !is_gradient_consistent(dl)

        # λ = 0 removes the term entirely, which is what makes it a homotopy
        @test with_electrostatic_scale(dl, 0.0).scale == 0.0
        @test with_electrostatic_scale(dl, 1.0).scale == 1.0
        @test with_electrostatic_scale(id, 0.3) === id      # a no-op, by dispatch
    end
end

@testsection "the diffuse layer against PHREEQC, by both routes" begin
    f = PHREEQC_DIFFUSE_LAYER
    dl = DiffuseLayer(; area = f.area)
    z_members = [0.0, 1.0, -1.0]          # XsOH, XsOH2+, XsO⁻, in family order

    function run(ser, pt; surface_potential)
        cs, st = _ddl_case(ser, pt; model = dl)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
        eq = SciMLBase.solve(
            des, st; b = b, constraint = FixedpH(pt.pH), surface_potential,
            parameters = Base.RefValue{Any}(nothing),
        )
        cert = optimality_certificate(des, eq; b = b, constraint = FixedpH(pt.pH))
        n = Float64[ustrip(us"mol", x) for x in eq.n]
        N = n[6] + n[7] + n[8]
        return (; des, eq, cert, n, fracs = (n[6] / N, n[7] / N, n[8] / N))
    end

    @testset "carrying Ψ as an unknown: all eighteen points" begin
        # THE POINT OF THE UNKNOWN. Written as an activity coefficient, the
        # potential is reached by a fixed-point iteration that stops contracting
        # above a stiffness of about five — and fifteen of these eighteen points
        # are above it. Carried as an unknown it is a column of the outer Newton,
        # which has the coupling in its Jacobian, and all eighteen certify.
        worst_rel, worst_abs, certified = 0.0, 0.0, 0
        for ser in f.series, pt in ser.points
            r = run(ser, pt; surface_potential = :unknown)
            @test r.cert.stationarity < 1.0e-8
            r.cert.stationarity < 1.0e-8 && (certified += 1)

            p = ChemistryLab._build_params(r.eq)
            @test r.des.lna(r.n, p)[2] / log(10) ≈ pt.la_H atol = 1.0e-6

            for (got, want) in zip(r.fracs, (pt.free, pt.protonated, pt.deprotonated))
                worst_abs = max(worst_abs, abs(got - want))
                worst_rel = max(worst_rel, abs(got / want - 1))
            end
        end
        @test certified == 18

        # Measured at 1.5e-4 absolute and 2.4e-3 relative. The two numbers say
        # different things and the absolute one is the honest headline: the
        # largest RELATIVE figure sits on a site fraction of 0.13, where a
        # common absolute error is divided by a small number.
        @info "PHREEQC, potential as an unknown" worst_abs worst_rel
        @test worst_abs < 3.0e-4
        @test worst_rel < 3.0e-3
    end

    @testset "eliminating it instead, and where that stops" begin
        # The same model, the same points, the potential eliminated — kept as a
        # measurement rather than removed, because it is what says the unknown
        # was necessary and not merely tidier.
        stiff_ok, stiff_bad, n_ok = 0.0, Inf, 0
        for ser in f.series, pt in ser.points
            # The forecast is made at PHREEQC's answer, so it predicts rather
            # than describes what this package happened to return.
            n_ref = f.n_sites .* [pt.free, pt.protonated, pt.deprotonated]
            stiff = electrostatic_stiffness(dl, z_members, n_ref, pt.I, 298.15)
            r = run(ser, pt; surface_potential = :eliminated)
            if r.cert.stationarity < 1.0e-8
                n_ok += 1
                stiff_ok = max(stiff_ok, stiff)
                for (got, want) in zip(r.fracs, (pt.free, pt.protonated, pt.deprotonated))
                    @test got ≈ want rtol = 3.0e-3
                end
            else
                stiff_bad = min(stiff_bad, stiff)
                # A diverged solve must never look like an answer: it violates
                # mass action by four orders of magnitude and the certificate
                # says so, fourteen orders of magnitude away from 1e-16.
                @test r.cert.stationarity > 1.0e-3
            end
        end
        @test 0 < n_ok < 18                       # both regimes are exercised

        # AND THE CRITERION PREDICTS THE SPLIT, with the limit strictly inside
        # the gap. This is the claim `ELECTROSTATIC_STIFFNESS_LIMIT` makes.
        @info "stiffness bracket, eliminated route" stiff_ok ELECTROSTATIC_STIFFNESS_LIMIT stiff_bad
        @test stiff_ok < ELECTROSTATIC_STIFFNESS_LIMIT < stiff_bad
    end

    @testset "two unknowns that both rebuild the activity model are refused" begin
        # An adiabatic solve makes the activity model a function of an unknown
        # temperature; a diffuse layer makes it a function of an unknown
        # potential. Composing the two would mean threading one's parameter
        # merge through the other's, and the shipped callbacks are opaque to
        # that — so it refuses and says where to start, rather than silently
        # applying one and dropping the other.
        ser, pt = f.series[1], f.series[1].points[1]
        cs, st = _ddl_case(ser, pt; model = dl)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
        err = try
            SciMLBase.solve(
                des, st; b = b, constraint = Adiabatic(),
                parameters = Base.RefValue{Any}(nothing),
            )
            nothing
        catch e
            e
        end
        @test err isa ArgumentError
        @test occursin("DiffuseLayer", sprint(showerror, err))

        # And the same system under the same constraint goes through once the
        # potential is eliminated, which is what says the refusal is about the
        # composition and not about either model.
        @test_nowarn SciMLBase.solve(
            des, st; b = b, constraint = Adiabatic(),
            surface_potential = :eliminated,
            parameters = Base.RefValue{Any}(nothing),
        )

        # The keyword refuses what it cannot do, too.
        @test_throws ArgumentError SciMLBase.solve(
            des, st; b = b, constraint = FixedpH(pt.pH), surface_potential = :nonsense,
            parameters = Base.RefValue{Any}(nothing),
        )
    end

    @testset "what the residual is not" begin
        # No explanation survives measurement, and saying so is worth more than
        # attributing the residual to the first plausible cause.
        #
        #   aqueous activity model   ideal  2.121e-4 absolute
        #                            Davies 2.072e-4
        #                            SIT    2.085e-4   — three models, 2 % apart
        #   dielectric constant      ours (78.245, κ = 0.117215) 2.385e-3 relative
        #                            PHREEQC's (78.5, κ = 0.117406) 2.408e-3, WORSE
        #   surface species set      identical: the weak-site block of
        #                            phreeqc.dat defines twenty-nine Hfo_w
        #                            species and a Na/Cl system can form three
        #
        # So it is not aqueous, not the dielectric constant, and not a missing
        # complex. It is 2e-4 on a site fraction, and it stays unattributed.
        #
        # So adopting PHREEQC's own constant does not improve the match, which
        # rules it out as the cause and makes the agreement a stronger result:
        # it holds with a different dielectric constant, not because of a shared
        # one.
        ser, pt = f.series[1], f.series[1].points[1]      # 0.1 M NaCl, pH 4
        worst(model) = maximum(
            abs(g / w - 1) for (g, w) in zip(
                    run(ser, pt; surface_potential = :unknown).fracs,
                    (pt.free, pt.protonated, pt.deprotonated),
                )
        )
        base = worst(dl)
        @test base < 3.0e-3
        κ_ours = sqrt(
            8 * water_relative_permittivity(298.15) * VACUUM_PERMITTIVITY *
                ChemistryLab.R_GAS * 298.15 * 1000
        )
        κ_phreeqc = sqrt(
            8 * 78.5 * VACUUM_PERMITTIVITY * ChemistryLab.R_GAS * 298.15 * 1000
        )
        @test κ_ours ≈ 0.117215 rtol = 1.0e-5
        @test κ_phreeqc ≈ 0.1174 rtol = 1.0e-4      # PHREEQC's source constant
        @test abs(κ_ours / κ_phreeqc - 1) < 3.0e-3
    end
end

@testsection "what the diffuse layer costs the certificate, measured" begin
    f = PHREEQC_DIFFUSE_LAYER
    ser, pt = f.series[1], f.series[1].points[1]      # 0.1 M NaCl, pH 4

    # MEASURED AT A CHARGED SURFACE, and that is not a detail. The coupling to
    # the ionic strength is proportional to σ, so at a surface carrying no net
    # charge it vanishes identically and every model looks consistent. The first
    # version of this test evaluated at the starting composition — all sites
    # free, σ = 0 — and reported the same 3.6e-3 for all three models, which is
    # the solvent/solute asymmetry `DiluteSolutionModel` has on its own.
    #
    # The per-pair relative measure, not the whole-Jacobian one: normalizing by
    # the largest entry hides a real inconsistency behind the 1/n self-terms of
    # trace species, which `test/activities.jl` records as a mistake once made.
    function asym(model)
        cs, st = _ddl_case(ser, pt; model)
        n = Float64[ustrip(us"mol", x) for x in st.n]
        n[6], n[7], n[8] = f.n_sites .* (pt.free, pt.protonated, pt.deprotonated)
        return site_gradient_asymmetry(cs, DiluteSolutionModel(), n)
    end

    ideal = asym(IdealSiteMixing())
    cc = asym(ConstantCapacitance(; C = 1.06, area = f.area))
    dl = asym(DiffuseLayer(; area = f.area))

    # THE TWO CRITERIA COME APART HERE, and only one of them is the
    # certificate's. Measuring both is what showed it.
    #
    #   symmetry     ∂ln aᵢ/∂nⱼ = ∂ln aⱼ/∂nᵢ   — a potential exists
    #   Gibbs-Duhem  Σᵢ nᵢ ∂ln aᵢ/∂nⱼ = 0      — that potential is extensive
    #
    # A constant capacitance passes the first and fails the second, and the
    # second failure is not a defect. Its charging work `F²(z·n)²/(2C𝒜)` is
    # homogeneous of degree TWO in `n`, because the area is a parameter of the
    # problem and does not scale with the amounts — the same way a fixed volume
    # does not. Extensivity in `n` alone is simply not what a surface of given
    # area has. What the certificate needs is that a potential exist at all, and
    # that is the first line, where the capacitance changes nothing.
    #
    # Neither baseline is zero: `DiluteSolutionModel` has a solvent/solute
    # asymmetry of its own, 3.6e-3, independent of any surface.
    @test ideal.worst < 1.0e-2
    @test ideal.gd < 1.0e-2
    @test cc.worst ≈ ideal.worst rtol = 1.0e-10     # still a gradient
    @test cc.gd > 0.5                               # but not an extensive one
    @info "constant capacitance: gradient kept, extensivity not" cc.worst cc.gd

    # The diffuse layer is not, and the pair that breaks it is a surface species
    # against an ion of the background — which is exactly the coupling the
    # Dzombak-Morel approximation makes one-way.
    @test dl.worst > 0.5
    @test dl.worst > 100 * ideal.worst
    surface_names = ("XsOH", "XsOH2+", "XsO-")
    @test count(in(surface_names), dl.pair) == 1     # one surface species
    @test count(in(surface_names), dl.pair) + count(!in(surface_names), dl.pair) == 2
    # The other member is aqueous, and it is the SOLVENT rather than a background
    # ion, which is the sharpest form of the one-way coupling: the ionic strength
    # is per kilogram of water, so the water amount moves the surface potential
    # while the surface moves nothing about the water.
    @test "H2O@" in dl.pair
    @info "diffuse layer, activity Jacobian asymmetry" dl.worst dl.pair dl.gd

    @testset "the state-level forecast" begin
        # The form a user reaches for: hand it a composition and it says whether
        # the elimination will hold there.
        model = DiffuseLayer(; area = f.area)
        _, st = _ddl_case(ser, pt; model)
        s = electrostatic_stiffness(st; T = 298.15)
        @test length(s) == 1
        @test s[1] > 0
        # switching the term off makes the forecast exactly zero
        _, st0 = _ddl_case(ser, pt; model = with_electrostatic_scale(model, 0.0))
        @test only(electrostatic_stiffness(st0)) == 0.0
        _, sti = _ddl_case(ser, pt; model = IdealSiteMixing())
        @test only(electrostatic_stiffness(sti)) == 0.0
        # a constant capacitance does not depend on the composition at all,
        # which is why a capacitance can be judged once and for all
        _, stc = _ddl_case(ser, pt; model = ConstantCapacitance(; C = 3.0, area = f.area))
        @test only(electrostatic_stiffness(stc)) ≈ 4.69 rtol = 1.0e-2
    end

    @testset "it differentiates" begin
        # The known trap is eltype promotion: each piece passes alone and the
        # chain breaks because a parameter sits outside the promotion. Here the
        # parameter is the area, which enters σ, κ√I and the stiffness alike.
        z = [0.0, 1.0, -1.0]
        n = [1.0e-4, 0.66e-4, 0.34e-4]
        # The second argument is the MEMBER's charge, not its index: the rest of
        # the vector is the whole support's, because that is what raises the
        # potential, and the member only rides on it.
        g = ForwardDiff.derivative(
            a -> ChemistryLab._electrostatic_ln_a(
                DiffuseLayer(; area = a, ε_r = 78.2451), z[2], z, n, 0.01, 298.15, nothing
            ), 53.4,
        )
        @test isfinite(g)
        @test g < 0                       # a larger area dilutes the charge

        # And through a potential that is GIVEN rather than computed, which is
        # the path a solve carrying it as an unknown takes: the term is then
        # linear in it, so the derivative is exactly the member's charge.
        gψ = ForwardDiff.derivative(
            ψ -> ChemistryLab._electrostatic_ln_a(
                DiffuseLayer(; area = 53.4), z[2], z, n, 0.01, 298.15, ψ
            ), 1.5,
        )
        @test gψ ≈ z[2]
        @test ChemistryLab._electrostatic_ln_a(
            DiffuseLayer(; area = 53.4), z[3], z, n, 0.01, 298.15, 1.5
        ) ≈ z[3] * 1.5

        # and at the unscreened limit the guard gives a finite number, not a NaN
        big = ChemistryLab._electrostatic_ln_a(
            DiffuseLayer(; area = 53.4), z[2], z, n, 0.0, 298.15, nothing
        )
        @test isfinite(big)
        # A positively charged surface makes one more positive species costlier
        # to put on it, so its activity RISES: the sign is +z_k ψ̃, and the
        # suppression appears in the mass-action balance, not here.
        @test big > 0
        @test abs(big) > 30               # Gouy-Chapman genuinely diverges there
    end
end
