# Cross-code reference test: calcite + CO₂ + water against Reaktoro 2.13.
#
# The oracle is generated by test/reference/reaktoro_calcite_co2.py, which reads
# the same Cemdata18 file, declares the same species, and uses ideal activities
# to match `DiluteSolutionModel()`. All three have to match: leaving Reaktoro on
# its HKF model instead shifts ∂Ca²⁺/∂(CO₂) by 35 %, which says nothing about
# either code.

# Reaktoro 2.13.0, Cemdata18, ideal activities
# finite-difference spread across h ∈ {1e-3, 1e-4, 1e-5}: 7.12e-4
const REAKTORO = Dict(
    "H2O@" => (n = 55.4961389, dn = -0.181397291),
    "H+" => (n = 3.69286738e-7, dn = 3.25691398e-5),
    "OH-" => (n = 2.70633096e-8, dn = -2.38767062e-6),
    "CO2@" => (n = 0.00613892838, dn = 0.818600249),
    "HCO3-" => (n = 0.00738915525, dn = 0.333426734),
    "CO3-2" => (n = 9.37864261e-7, dn = -4.03977783e-5),
    "Ca+2" => (n = 0.00352901991, dn = 0.151986657),
    "CaOH+" => (n = 1.58551676e-9, dn = -7.15930328e-8),
    "Ca(CO3)@" => (n = 5.54793457e-6, dn = -1.8134238e-8),
    "Ca(HCO3)+" => (n = 0.000332647348, dn = 0.029337739),
    "Cal" => (n = 0.0461327832, dn = -0.181324306),
)

# The oracle is itself a finite difference; nothing below its own step-size
# spread is meaningful, so that is the tolerance.
const RK_SPREAD = 7.12e-4

# ── Trace species ─────────────────────────────────────────────────────────────
#
# Every species now agrees with Reaktoro: those above ~1e-5 mol to 1e-3 relative,
# the trace ions to 5 %, the worst being `CaOH+` at ×1.032. `pKw` on this system
# is 13.9994 against Reaktoro's 14.0001; the 13.979 this comment used to quote was
# computed from the pre-fix `OH-`.
#
# That was not always so, and the history is worth keeping because it says where
# to look when a trace ion is wrong. Two defects in the back-end, both fixed:
#
#   * the Newton step formed the Schur complement `S = A H⁻¹ Aᵀ`, which needs
#     `H` invertible — a pure phase has unit activity, hence exactly zero
#     curvature. Pure water came out with `[H⁺]/[OH⁻] = 3.78`;
#   * the convergence test excluded species judged "at their bound" using a
#     threshold scaled by the *largest* amount in the system. With a solvent at
#     55 mol that threshold was 5.5e-7, so every trace ion below it was declared
#     to sit on a bound of 1e-16 and its stationarity was never enforced. That
#     alone accounted for CaOH⁺ ×20.8, OH⁻ ×3.19 and `pKw` = 13.40.
#
# After those two, `CaOH+` was still 2.5× high at 4e-9 mol and was left
# `@test_broken`, on the reasoning that Ipopt landed on the same point (×2.46) so
# the discrepancy could not belong to one back-end. That reasoning was wrong: both
# were barrier iterations stopping before stationarity at μ = 0, and trace species
# are exactly where that shows. `is_converged` was comparing the residual at the
# CURRENT barrier level, which vanishes at the barrier subproblem's solution for
# any μ; it now uses the same residual at μ = 0, the true KKT error (OptimaSolver
# 0.4.1). The `@test_broken` is gone and the assertion below is a plain `@test`.
#
const TRACE_CUTOFF = 1.0e-5

const N_H2O, N_CAL, N_CO2 = 55.5, 0.05, 0.01

@testset "Reaktoro reference: calcite + CO₂ + water" begin
    data = datapath("cemdata18-thermofun.json")
    dict = Dict(symbol(s) => s for s in build_species(data))
    syms = collect(keys(REAKTORO))
    cs = ChemicalSystem([dict[s] for s in syms], ["H2O@", "H+", "Ca+2", "CO3-2", "Zz"])
    names = symbol.(cs.species)

    ih2o = findfirst(==("H2O@"), names)
    ical = findfirst(==("Cal"), names)
    ico2 = findfirst(==("CO2@"), names)

    function speciate(x)
        n = Any[fill(0.0u"mol", length(cs.species))...]
        n[ih2o] = N_H2O * u"mol"
        n[ical] = N_CAL * u"mol"
        n[ico2] = x * u"mol"
        eq = equilibrate(ChemicalState(cs, n), OptimaOptimizer())
        return [ustrip(us"mol", v) for v in eq.n]
    end

    amounts = speciate(N_CO2)
    derivs = ForwardDiff.derivative(speciate, N_CO2)

    @testset "amounts agree with Reaktoro" begin
        # Species above ~1e-5 mol match Reaktoro to 1e-3 relative, the rest to 5 %.
        #
        # `CaOH+` used to be the exception, out by a factor 2.5 at 4e-9 mol, and it
        # was left `@test_broken` because Ipopt landed on the same point — so it
        # looked like a property of the problem rather than of one solver. It was
        # neither: the interior-point stage was reporting a point it had reached
        # without ever satisfying the KKT conditions at μ = 0, and the trace
        # species are exactly where that shows. Every species now matches.
        for (k, name) in enumerate(names)
            ref = REAKTORO[name].n
            if ref > TRACE_CUTOFF
                @test amounts[k] ≈ ref rtol = 1.0e-3
            else
                @test amounts[k] ≈ ref rtol = 0.05
            end
        end
    end

    @testset "sensitivities agree with Reaktoro" begin
        # Species carrying a resolvable share of the response are compared
        # relatively; the rest only have to stay within the oracle's own noise.
        scale = maximum(abs(v.dn) for v in values(REAKTORO))
        for (k, name) in enumerate(names)
            ref = REAKTORO[name].dn
            if abs(ref) > 1.0e-3 * scale
                @test derivs[k] ≈ ref rtol = 2 * RK_SPREAD
            else
                @test abs(derivs[k] - ref) < RK_SPREAD * scale
            end
        end
    end

    # There is deliberately no "AD against our own finite differences" test.
    # Differencing two independent solves over 2h = 2e-6 amplifies whatever
    # error each one carries by 5e5, so the check measures the solver's
    # termination accuracy, not the derivative — it cannot pass without a
    # tolerance tuned until it does. The AD is checked against Reaktoro above,
    # on every species, which is the comparison that means something.

    @testset "water autoprotolysis" begin
        # The tightest constraint there is, and one no thermodynamic database
        # can get wrong: pure water is electrically neutral, so [H⁺] = [OH⁻]
        # exactly, whatever Kw happens to be. It is a pure statement about the
        # solve. This failed — 4.03 instead of 1 — while the back-end was
        # steering on an approximated Hessian diagonal.
        csw = ChemicalSystem(
            [dict[s] for s in ["H2O@", "H+", "OH-"]],
            ["H2O@", "H+", "Zz"]
        )
        nw = symbol.(csw.species)
        n = Any[fill(0.0u"mol", length(nw))...]
        n[findfirst(==("H2O@"), nw)] = 55.5u"mol"
        eq = equilibrate(ChemicalState(csw, n), OptimaOptimizer())
        v = [ustrip(us"mol", x) for x in eq.n]
        h, oh = v[findfirst(==("H+"), nw)], v[findfirst(==("OH-"), nw)]
        @test h ≈ oh rtol = 1.0e-4
        @test 13.9 < -log10(h * oh) < 14.1

        # THE SCHUR-COMPLEMENT ROUTE IS STILL WRONG, and this testset used to say
        # otherwise because it only looked at the half that happens to be right.
        #
        # History: the route came out at [H⁺]/[OH⁻] ≈ 3.78, then at 8.7e-5, and
        # the assertion was written the other way round — "the answer is wrong" —
        # with the note that if it ever started passing, the defect had been cured
        # elsewhere. It started passing, and the note was taken at its word.
        #
        # It should not have been. The ratio is electroneutrality, which is
        # necessary and not sufficient; the other half of "this is pure water" is
        # the ion product, and nothing asserted it for this route. Measured on
        # Linux x86_64, Julia 1.13, OptimaSolver 0.6.0:
        #
        #     route     [H⁺]/[OH⁻]   [H⁺]        [OH⁻]       pKw
        #     default   1.000000     1.0002e-7   1.0002e-7   13.9998
        #     Schur     0.995604     1.1833e-6   1.1885e-6   11.8519
        #
        # Both ions come out about twelve times too large, so the product is off
        # by a factor of 140 while their RATIO stays within half a percent of one.
        # The element balance closes exactly either way — 111.000000 mol of H
        # against 111.0 in — so the route returns a point that conserves matter
        # and is not an equilibrium, and it says so: the solve reports `MaxIters`.
        #
        # This also reframes the failure an external audit saw on macOS ARM64,
        # where the ratio came out 0.83683 and the assertion went red. The route
        # is wrong on Linux too; the platform only changes how visibly.
        eqs = equilibrate(ChemicalState(csw, n), OptimaOptimizer(; nullspace_step = false))
        vs = [ustrip(us"mol", x) for x in eqs.n]
        hs, ohs = vs[findfirst(==("H+"), nw)], vs[findfirst(==("OH-"), nw)]
        ratio = hs / ohs

        # Reported, not merely asserted: a boolean against a tolerance hides how
        # much room is left, and there is little — 0.44 % against 1 %.
        @info "water autoprotolysis, Schur route" ratio pKw = -log10(hs * ohs)

        @test isapprox(ratio, 1.0; rtol = 1.0e-2)
        # The half that was missing. `@test_broken`, so the suite states the
        # defect instead of passing over it — and turns red the day it is fixed,
        # which is how we will hear about it.
        @test_broken 13.9 < -log10(hs * ohs) < 14.1
    end

    @testset "element balance closes exactly" begin
        # Calcium has no source or sink here, so the sensitivities of every
        # Ca-bearing species must cancel. A finite difference only manages this
        # approximately; the KKT route is exact.
        ca = Dict(
            "Ca+2" => 1, "Cal" => 1, "CaOH+" => 1,
            "Ca(CO3)@" => 1, "Ca(HCO3)+" => 1
        )
        budget = sum(derivs[k] * get(ca, name, 0) for (k, name) in enumerate(names))
        @test abs(budget) < 1.0e-12
    end
end
