# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2025-2026 Jean-François Barthélémy and Anthony Soive (Cerema, UMR MCD)

using ChemistryLab
using DynamicQuantities
using JSON
using SciMLBase
using Test

const RT_EX = ChemistryLab.R_GAS * 298.15
include("reference_species.jl")

_gx(v) = SymbolicFunc(v * u"J/mol")

# ── Cation exchange, in both conventions ─────────────────────────────────────
#
# Generated by `test/reference/reaktoro_ion_exchange.py`. Reaktoro is the
# reference here because it is the one that carries **both** conventions, which
# is what this comparison is about.
#
# The aqueous model is ideal on both sides, deliberately: an exchange constant
# and an aqueous activity coefficient are different things, and this compares
# the first. The composition holds all three cations in comparable amounts —
# the place the two conventions are furthest apart, rather than a trace limit
# where they agree by construction.
# generated by test/reference/reaktoro_ion_exchange.py
# python    3.12.13
# reaktoro  2.13.0
# database  phreeqc.dat (via Reaktoro's PhreeqcDatabase)
# aqueous   ideal on both sides, deliberately
# capacity  1.0 mmol of charge
# solution  {'Na+': 1.0, 'K+': 1.0, 'Ca+2': 0.5, 'Cl-': 3.0} mmol
const REAKTORO_EXCHANGE = reference_oracle("reaktoro_ion_exchange")

# Standard energies of the aqueous cations. Only their *differences* enter an
# exchange reaction, so any consistent set does; these are the usual ones.
# The aqueous standard energies that enter each exchange constant, read off the
# species the database gives rather than written here. They were a line of three
# literals, and two of them had already drifted in the last digits.
_G298(s) = ustrip(us"J/mol", s[:ΔₐG⁰](T = 298.15u"K", P = 1.0e5u"Pa"; unit = true))

"""
Build an exchanger with `model` as its convention. `heterovalent = false` drops
calcium, leaving a homovalent Na/K exchange — the case where the two
conventions must agree.
"""
function _exchanger(model; heterovalent = true, capacity = REAKTORO_EXCHANGE.capacity)
    f = REAKTORO_EXCHANGE
    aq(sym, g, cl = SC_AQSOLUTE) = begin
        s = Species(sym; aggregate_state = AS_AQUEOUS, class = cl); s[:ΔₐG⁰] = _gx(g); s
    end
    ex(sym, g) = begin
        s = Species(sym; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        s[:ΔₐG⁰] = _gx(g); s
    end

    h2o, hp, na, k, ca = reference_species(("H2O@", "H+", "Na+", "K+", "Ca+2"))
    G_NA, G_K, G_CA = _G298(na), _G298(k), _G298(ca)

    # The reference form carries the zero of the family's energy scale, so each
    # exchanger's standard energy follows from its exchange constant against it.
    #
    #   K⁺ + NaX = KX + Na⁺   ⇒  G(KX)   = −RT lnK + G(K⁺)  − G(Na⁺)
    #   Ca²⁺ + 2 NaX = CaX₂ + 2 Na⁺  ⇒  G(CaX₂) = −RT lnK + G(Ca²⁺) − 2 G(Na⁺)
    #
    # The aqueous terms enter with the sign the reaction gives them, which is
    # the opposite of the one that reads naturally. Getting it backwards leaves
    # the exchanger inert — every site stays sodium — and the comparison below
    # is what says so.
    naX = ex("NaXc", 0.0)
    kX = ex("KXc", -RT_EX * log(10.0^f.logK_K) + G_K - G_NA)
    caX = ex("CaXc2", -RT_EX * log(10.0^f.logK_Ca) + G_CA - 2 * G_NA)

    members = heterovalent ? [kX, caX] : [kX]
    family = SiteFamily(
        "X", naX, members;
        capacity = TotalSiteAmount(capacity * u"mol"),
        support = SurfaceSupport("exchanger", nothing, FixedSurfaceArea(1.0)),
        model = model,
    )
    species = heterovalent ? [h2o, hp, na, k, ca, naX, kX, caX] : [h2o, hp, na, k, naX, kX]
    primaries = heterovalent ? [h2o, hp, na, k, ca, naX] : [h2o, hp, na, k, naX]
    cs = ChemicalSystem(species, primaries; site_families = [family])

    idx = Dict(symbol(sp) => j for (j, sp) in enumerate(cs.species))
    n0 = Any[fill(1.0e-12u"mol", length(cs.species))...]
    # Exactly one kilogram of water, because Reaktoro's `set("H2O", 1.0, "kg")`
    # does the same and the dilute model reads activities as molalities. At
    # 55.5 mol the two bases differ by 1.7e-4, which the exchange propagates.
    n0[idx["H2O@"]] = moles_of_water() * u"mol"
    n0[idx["NaXc"]] = capacity * u"mol"
    n0[idx["Na+"]] = 1.0e-3u"mol"
    n0[idx["K+"]] = 1.0e-3u"mol"
    heterovalent && (n0[idx["Ca+2"]] = 5.0e-4u"mol")
    return cs, ChemicalState(cs, n0), idx
end

function _solve_exchanger(model; kwargs...)
    cs, st, idx = _exchanger(model; kwargs...)
    des = DualEquilibriumSolver(cs, DiluteSolutionModel())
    b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
    eq = SciMLBase.solve(des, st; b = b)
    n = Float64[ustrip(us"mol", x) for x in eq.n]
    return n, idx, cs
end

@testsection "Cation exchange" begin

    @testset "the budget counts charge, not molecules" begin
        cs, _, _ = _exchanger(GainesThomasMixing())
        row = cs.SM.A[findfirst(p -> symbol(p) == "NaXc", cs.SM.primaries), :]
        names = symbol.(cs.species)
        w = Dict(names[i] => Int(row[i]) for i in eachindex(names) if row[i] != 0)
        # A divalent cation neutralizes two units of charge and consumes two of
        # the budget. That is what makes this a capacity in **equivalents**, and
        # it comes from the formula rather than from a declaration.
        @test w == Dict("NaXc" => 1, "KXc" => 1, "CaXc2" => 2)
    end

    @testset "a homovalent exchange cannot tell the conventions apart" begin
        # With every exchanger monovalent, a mole fraction and an equivalent
        # fraction are the same number. Two conventions, one answer — and if
        # this ever fails, one of them is not the convention it says it is.
        nv, iv, _ = _solve_exchanger(VanselowMixing(); heterovalent = false)
        ng, ig, _ = _solve_exchanger(GainesThomasMixing(); heterovalent = false)
        for sym in ("NaXc", "KXc")
            @test nv[iv[sym]] ≈ ng[ig[sym]] rtol = 1.0e-10
        end
    end

    @testset "a heterovalent exchange tells them apart, and Reaktoro agrees" begin
        f = REAKTORO_EXCHANGE
        pairs = (
            (VanselowMixing(), f.vanselow), (GainesThomasMixing(), f.gainesthomas),
        )
        worst = 0.0
        for (model, ref) in pairs
            n, idx, _ = _solve_exchanger(model)
            got = (NaX = n[idx["NaXc"]], KX = n[idx["KXc"]], CaX2 = n[idx["CaXc2"]])
            for k in (:NaX, :KX, :CaX2)
                @test getfield(got, k) ≈ getfield(ref, k) rtol = 1.0e-7
                worst = max(worst, abs(getfield(got, k) / getfield(ref, k) - 1))
            end
            # The capacity is in equivalents and is conserved as such.
            @test got.NaX + got.KX + 2 * got.CaX2 ≈ f.capacity rtol = 1.0e-8
        end
        # Measured at 4.1e-9, and the threshold keeps a factor of twenty-four
        # of margin. It was 5.5e-5 until the water basis was matched: Reaktoro
        # sets one kilogram, 55.5 mol is 0.99983 kg, and every molality carried
        # that 1.7e-4. Four orders of magnitude for one line — worth knowing
        # before blaming a model for what a basis did.
        @info "ion exchange against Reaktoro, both conventions" worst
        @test worst < 1.0e-7

        # And the two conventions really do disagree here — by tens of percent
        # on the sodium. A test that passed against both without this would be
        # measuring nothing.
        nv, iv, _ = _solve_exchanger(VanselowMixing())
        ng, ig, _ = _solve_exchanger(GainesThomasMixing())
        @test abs(nv[iv["NaXc"]] / ng[ig["NaXc"]] - 1) > 0.2
    end

    @testset "multidentate is a convention's business, not a default" begin
        support = SurfaceSupport("exchanger", nothing, FixedSurfaceArea(1.0))
        cap = TotalSiteAmount(1.0e-3)
        naX = Species("NaXc"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        caX = Species("CaXc2"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)

        # The site balance holds for any denticity; the mixing law does not
        # follow from it. Ideal site mixing therefore still refuses.
        @test_throws ArgumentError SiteFamily(
            "X", naX, [caX]; capacity = cap, support, model = IdealSiteMixing(),
        )
        # The exchange conventions accept it, because there the sites counted
        # are units of charge and a divalent cation straddles nothing.
        for model in (VanselowMixing(), GainesThomasMixing())
            fam = SiteFamily("X", naX, [caX]; capacity = cap, support, model)
            @test supports_multidentate(site_mixing_model(fam))
            @test denticity(fam, caX) == 2
            @test symbol(reference_member(fam)) == "NaXc"
        end
        @test !supports_multidentate(IdealSiteMixing())
    end

end
