using JSON

# The reader of PHREEQC databases against PHREEQC itself, on the six databases
# PHREEQC distributes, obtained by `datapath` as the package obtains them. The
# reference values are generated by `test/reference/phreeqc_databases.py`.
#
# Each case is solved twice. With the Debye–Hückel A (and B) PHREEQC used, which
# the fixture records, the models are PHREEQC's own, and what remains is what
# the tolerances below say: the mass of water, which PHREEQC holds at 1 kg in an
# initial solution and which follows the reactions here (2e-6), the gas constant
# of PHREEQC's van 't Hoff equation, 8.31470 J/(mol K) against the exact value
# (7e-5 at 60 °C), and the `-ZETA` terms of pitzer.dat, which the Pitzer model
# does not carry (8e-5). With the A and B of ChemistryLab's own water model, the
# gap is that of A, 0.27 % at 25 °C, and stays within a percent.

@testsection "PHREEQC databases against PHREEQC" begin
    oracle = JSON.parsefile(joinpath(@__DIR__, "reference", "phreeqc_databases.json"))["databases"]
    solutes = ["Na+" => 0.5, "K+" => 0.01, "Ca+2" => 0.01, "Mg+2" => 0.02, "Cl-" => 0.525, "SO4-2" => 0.02, "HCO3-" => 0.005]
    elements = Set([:H, :O, :Na, :K, :Ca, :Mg, :Cl, :S, :C])
    # The relative tolerance with PHREEQC's A and B, at 25 and 60 °C; `nothing`
    # where the model cannot be given them (the temperature terms of a Pitzer
    # set come with ChemistryLab's own A).
    tight = Dict(
        "phreeqc.dat" => (2.0e-5, 1.5e-4), "wateq4f.dat" => (2.0e-5, 1.5e-4),
        "minteq.v4.dat" => (2.0e-5, 1.5e-4), "llnl.dat" => (2.0e-5, 2.0e-5),
        "sit.dat" => (2.0e-5, 2.0e-5), "pitzer.dat" => (1.5e-4, nothing),
    )

    function with_phreeqc_AB(model, o, T)
        model isa TruesdellJonesActivityModel && return TruesdellJonesActivityModel(;
            parameters = model.parameters, A = o["DH_A"], B = o["DH_B"], water = :phreeqc,
        )
        model isa SITActivityModel && return SITActivityModel(;
            parameters = model.parameters, A = o["DH_A"], water = :osmotic,
        )
        model isa PitzerActivityModel && return PitzerActivityModel(;
            parameters = model.parameters, A = o["DH_A"], missing_pairs = :zero,
        )
        # The LLNL model takes its A and B from the database, as PHREEQC does.
        @test model isa LLNLActivityModel
        @test ChemistryLab._llnl_terms(model, 273.15 + T)[1] ≈ o["DH_A"] rtol = 1.0e-12
        return model
    end

    # The largest relative gap over the species PHREEQC finds above 1e-12 mol/kg.
    function worst_gap(db, eq, o)
        w = ustrip(us"mol", moles(eq, "H2O@")) * ustrip(us"kg/mol", eq.system.species[only(eq.system.idx_solvent)][:M])
        by_name = Dict(sp.name => sp for sp in db.species)
        worst = 0.0
        for (name, m) in o["molality"]
            m < 1.0e-12 && continue
            sym = ChemistryLab._phreeqc_symbol_of(by_name[ChemistryLab._phreeqc_name(name)])
            worst = max(worst, abs(ustrip(us"mol", moles(eq, sym)) / w / m - 1))
        end
        return worst
    end

    for (file, (tol25, tol60)) in sort!(collect(tight))
        db = read_phreeqc_database(datapath(file))
        own = database_activity_model(db)
        @testset "$file" begin
            for case in ("speciation", "minerals")
                phases = case == "minerals" ? ["Calcite", "Gypsum"] : String[]
                names = [sp.name for sp in db.species if sp.name != "e-" && all(in(elements), keys(sp.atoms))]
                cs = ChemicalSystem(build_species(db, vcat(names, phases)))
                for (T, tol) in ((25.0, tol25), (60.0, tol60))
                    o = oracle[file][case][string(T)]
                    st = ChemicalState(cs; T = (273.15 + T) * u"K", P = 101325.0u"Pa")
                    set_quantity!(st, "H2O@", 1.0u"kg")
                    if case == "speciation"
                        for (s, m) in solutes
                            set_quantity!(st, s, m * u"mol")
                        end
                    else
                        set_quantity!(st, "Calcite", 10.0u"mol")
                        set_quantity!(st, "Gypsum", 10.0u"mol")
                    end
                    for (model, rtol) in ((own, 1.5e-2), (tol === nothing ? nothing : with_phreeqc_AB(own, o, T), tol))
                        model === nothing && continue
                        eq = equilibrate(st; model)
                        @test worst_gap(db, eq, o) < rtol
                        @test ionic_strength(eq) ≈ o["mu"] rtol = rtol
                        if case == "minerals"
                            for m in ("Calcite", "Gypsum")
                                @test 10 - ustrip(us"mol", moles(eq, m)) ≈ o["dissolved"][m] rtol = rtol
                            end
                        end
                        # PHREEQC's Pitzer reports single-ion activities on the
                        # MacInnes scale, which moves its pH by 0.03 here and no
                        # composition: the pH is compared under the other models.
                        own isa PitzerActivityModel || @test pH(eq, model) ≈ o["pH"] atol = 5.0e-3
                        rtol < 1.0e-3 && !(own isa PitzerActivityModel) && @test pH(eq, model) ≈ o["pH"] atol = 1.0e-4
                    end
                end
            end
        end
    end
end

@testsection "PHREEQC databases: gauge, notes, readers" begin
    # Two writings of one database, each with its own master species for carbon
    # (CO3-2 in the first, HCO3- in the second): the energies of the species
    # differ, the equilibrium does not. The constants are illustrative, not
    # those of any database.
    masters(c) = """
    SOLUTION_MASTER_SPECIES
    H     H+     -1.0  H     1.008
    H(1)  H+     -1.0  0
    E     e-      0.0  0     0.0
    O     H2O     0.0  O     16.0
    O(-2) H2O     0.0  0
    Ca    Ca+2    0.0  Ca    40.08
    C     $c      2.0  HCO3  12.0111
    C(4)  $c      2.0  HCO3
    SOLUTION_SPECIES
    H+ = H+
        -gamma 9.0 0.0
    e- = e-
    H2O = H2O
    Ca+2 = Ca+2
        -gamma 5.0 0.165
    H2O = OH- + H+
        -log_k -14.0
        -delta_h 55.9 kJ
        -gamma 3.5 0.0
    """
    a = masters("CO3-2") * """
        CO3-2 = CO3-2
            -gamma 5.4 0.0
        CO3-2 + H+ = HCO3-
            -log_k 10.3
            -delta_h -15.0 kJ
            -gamma 5.4 0.0
        CO3-2 + 2 H+ = CO2 + H2O
            -log_k 16.7
            -delta_h -24.0 kJ
        Ca+2 + CO3-2 = CaCO3
            -log_k 3.2
            -delta_h 15.0 kJ
        PHASES
        Calcite
            CaCO3 = CO3-2 + Ca+2
            -log_k -8.5
            -delta_h -10.0 kJ
        END
        """
    b = masters("HCO3-") * """
        HCO3- = HCO3-
            -gamma 5.4 0.0
        HCO3- = CO3-2 + H+
            -log_k -10.3
            -delta_h 15.0 kJ
            -gamma 5.4 0.0
        HCO3- + H+ = CO2 + H2O
            -log_k 6.4
            -delta_h -9.0 kJ
        Ca+2 + HCO3- = CaCO3 + H+
            -log_k -7.1
            -delta_h 30.0 kJ
        PHASES
        Calcite
            CaCO3 + H+ = HCO3- + Ca+2
            -log_k 1.8
            -delta_h -25.0 kJ
        END
        """
    mktempdir() do dir
        fa, fb = joinpath(dir, "a.dat"), joinpath(dir, "b.dat")
        write(fa, a)
        write(fb, b)
        da, db = read_phreeqc_database(fa), read_phreeqc_database(fb)
        @test da.gauge != db.gauge
        sa, sb = build_species(da), build_species(db)
        ga = Dict(symbol(s) => s for s in sa)
        gb = Dict(symbol(s) => s for s in sb)
        T, P = 323.15, 1.0e5
        # The energies differ by the gauge: CO3-2 is at zero in the first only.
        @test ga["CO3-2"][:ΔₐG⁰](T = T, P = P) == 0.0
        @test abs(gb["CO3-2"][:ΔₐG⁰](T = T, P = P)) > 1.0e4
        # A species defined by the same reaction in both has the same energy.
        @test ga["OH-"][:ΔₐG⁰](T = T, P = P) ≈ gb["OH-"][:ΔₐG⁰](T = T, P = P) rtol = 1.0e-12
        model = database_activity_model(da)
        for (Tc, tol) in ((25.0, 1.0e-9), (50.0, 1.0e-9))
            amounts = map((sa, sb)) do sp
                cs = ChemicalSystem(sp)
                st = ChemicalState(cs; T = (273.15 + Tc) * u"K", P = 101325.0u"Pa")
                set_quantity!(st, "H2O@", 1.0u"kg")
                set_quantity!(st, "Calcite", 1.0u"mol")
                eq = equilibrate(st; model)
                Dict(s => ustrip(us"mol", moles(eq, s)) for s in ("Ca+2", "CO3-2", "HCO3-", "CO2@", "CaCO3@", "OH-", "H+"))
            end
            for s in keys(amounts[1])
                @test amounts[1][s] ≈ amounts[2][s] rtol = tol
            end
        end
        # Species of the two cannot be mixed in one system.
        err = try
            ChemicalSystem([ga["H2O@"], ga["H+"], gb["Ca+2"], gb["CO3-2"]])
        catch e
            e
        end
        @test err isa ArgumentError
        @test occursin("different zeros", sprint(showerror, err))

        # What the reader does not use is noted with its line: a species
        # defined again, an option the manual does not document, a pseudo-element,
        # an input block.
        fc = joinpath(dir, "c.dat")
        write(
            fc, masters("CO3-2") * """
                CO3-2 = CO3-2
                Ca+2 + CO3-2 = CaCO3
                    -log_k 3.0
                    -frobnicate 2
                Ca+2 + CO3-2 = CaCO3
                    -log_k 3.2
                Mtg = Mtg
                Mtg + Ca+2 = CaMtg+2
                    -log_k 1.0
                SOLUTION_MASTER_SPECIES
                Mtg     Mtg     0.0  Mtg  16.042
                KNOBS
                    -iterations 200
                END
                """,
        )
        dc = read_phreeqc_database(fc)
        @test any(n -> occursin("CaCO3 is defined again", n), dc.notes)
        @test any(n -> occursin("`-frobnicate`", n), dc.notes)
        @test any(n -> occursin("CaMtg+2 is made of", n), dc.notes)
        @test any(n -> occursin("KNOBS is an input block", n), dc.notes)
        caco3 = only(sp for sp in dc.species if sp.name == "CaCO3")
        @test first(ChemistryLab._formation_log10K(dc, caco3.formation, 298.15)) ≈ 3.2
        @test occursin("PhreeqcDatabase(\"c.dat\"", sprint(show, dc))
    end

    # The parameters of `-gamma`, the master species, and the activity model of
    # each kind of database.
    γ = phreeqc_gamma_parameters(datapath("phreeqc.dat"))
    @test γ["Ca+2"] == (5.0, 0.165)
    primaries = extract_primary_species(datapath("phreeqc.dat"))
    @test "Ca+2" in primaries.symbol
    @test last(primaries.symbol) == "Zz"
    @test !("HCO3-" in primaries.symbol)
    @test database_activity_model(read_phreeqc_database(datapath("wateq4f.dat"))) isa TruesdellJonesActivityModel

    # The LLNL model: its A, B and B-dot interpolated linearly in °C, refused
    # outside its grid, and its arguments checked.
    llnl = database_activity_model(read_phreeqc_database(datapath("llnl.dat")))
    A, B, Bdot = ChemistryLab._llnl_terms(llnl, 273.15 + 120.0)[1:3]
    @test A ≈ 0.5995 + 0.4 * (0.6855 - 0.5995)
    @test Bdot ≈ 0.046 + 0.4 * 0.001
    @test_throws DomainError ChemistryLab._llnl_terms(llnl, 273.15 + 320.0)
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [25.0], A = [0.5], B = [0.3], Bdot = [0.04], co2 = zeros(5), sizes = Dict{String, Float64}())
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [0.0, 25.0], A = [0.5], B = [0.3, 0.3], Bdot = [0.04, 0.04], co2 = zeros(5), sizes = Dict{String, Float64}())
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [25.0, 0.0], A = [0.5, 0.5], B = [0.3, 0.3], Bdot = [0.04, 0.04], co2 = zeros(5), sizes = Dict{String, Float64}())
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [0.0, 25.0], A = [0.5, 0.5], B = [0.3, 0.3], Bdot = [0.04, 0.04], co2 = zeros(4), sizes = Dict{String, Float64}())
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [0.0, 25.0], A = [0.5, 0.5], B = [0.3, 0.3], Bdot = [0.04, 0.04], co2 = zeros(5), sizes = Dict{String, Float64}(), water = :ideal)
    @test_throws ArgumentError TruesdellJonesActivityModel(; parameters = Dict{String, Tuple{Float64, Float64}}(), water = :ideal)
    @test_throws ArgumentError SITActivityModel(; water = :ideal)
    @test_throws ArgumentError PitzerActivityModel(; parameters = build_pitzer_parameters(datapath("pitzer-reardon1990.toml")), missing_pairs = :ignore)

    # The kinds of species of the LLNL model, and PHREEQC's activity of water,
    # held at its bound past the 59 mol/kg where it has no value.
    toy = LLNLActivityModel(;
        temperatures = [0.0, 100.0], A = [0.5, 0.6], B = [0.33, 0.34], Bdot = [0.04, 0.05],
        co2 = (-1.0312, 0.0012806, 255.9, 0.4445, -0.001606), sizes = Dict("Na+" => 4.0, "SiO2@" => 3.0),
        co2_species = ["CO2@"], gamma = Dict("K+" => (3.5, 0.015)), water = :phreeqc,
    )
    terms = ChemistryLab._llnl_terms(toy, 298.15)
    I, sI = 0.5, sqrt(0.5)
    @test ChemistryLab._llnl_log10γ((0, 0.0, 0.0), 1, I, sI, terms[1], terms[2:5]) == 0.0
    @test ChemistryLab._llnl_log10γ((3, 3.5, 0.015), 1, I, sI, terms[1], terms[2:5]) ≈ 0.015 * I
    @test ChemistryLab._llnl_log10γ((2, 0.0, 0.0), 0, I, sI, terms[1], terms[2:5]) ≈
        (terms[4] * I - terms[5] * I / (1 + I)) / log(10)
    # The coefficients a state reports are those of the closure: an ion with a
    # size, carbon dioxide, a neutral species with a size (γ = 1).
    db_llnl = read_phreeqc_database(datapath("llnl.dat"))
    cs = ChemicalSystem(build_species(db_llnl, ["H2O", "H+", "OH-", "Na+", "Cl-", "HCO3-", "CO3-2", "CO2", "NaCl"]))
    st = ChemicalState(cs; T = 333.15u"K", P = 101325.0u"Pa")
    set_quantity!(st, "H2O@", 1.0u"kg")
    set_quantity!(st, "Na+", 0.5u"mol")
    set_quantity!(st, "Cl-", 0.49u"mol")
    set_quantity!(st, "HCO3-", 0.01u"mol")
    eq = equilibrate(st; model = llnl)
    γs = activity_coefficients(eq, llnl)
    A60, B60, Bd60, c1, c2 = ChemistryLab._llnl_terms(llnl, 333.15)
    Ieq = ionic_strength(eq)
    @test log10(γs["Na+"]) ≈ -A60 * sqrt(Ieq) / (1 + 4.0 * B60 * sqrt(Ieq)) + Bd60 * Ieq rtol = 1.0e-6
    @test log10(γs["CO2@"]) ≈ (c1 * Ieq - c2 * Ieq / (1 + Ieq)) / log(10) rtol = 1.0e-6
    @test γs["NaCl@"] ≈ 1.0
    # An element outside the order the package writes formulas in.
    @test length(build_species(db_llnl, ["Li+", "Zn+2"])) == 2
    @test ChemistryLab._solvent_lna(:phreeqc, 1.0, 2.0, 1.0, 0.018) ≈ log(1 - 0.017 / 0.018)
    @test isfinite(ChemistryLab._solvent_lna(:phreeqc, 1.0, 101.0, 100.0, 0.018))
end
