using JSON
using ChemistryLab: value, source
using ChemistryLab.DataFrames: metadata

# The reader of PHREEQC databases against PHREEQC itself, on the six databases
# PHREEQC distributes, obtained by `datapath` as the package obtains them. The
# reference values are generated by `test/reference/phreeqc_databases.py`.
#
# Each case is solved twice. With the Debye–Hückel A (and B) PHREEQC used, which
# the fixture records, the models are PHREEQC's own, and what remains is what
# the tolerances below say: the mass of water, which PHREEQC holds at 1 kg in an
# initial solution and which follows the reactions here (2e-6), the gas constant
# of PHREEQC's van 't Hoff equation, 8.31470 J/(mol K) against the exact value
# (7e-5 at 60 °C), and the `-ZETA` terms of pitzer.dat, which the Pitzer model
# does not carry (8e-5). With the A and B of ChemistryLab's own water model, the
# gap is that of A, 0.27 % at 25 °C, and stays within a percent.

@testsection "PHREEQC databases against PHREEQC" begin
    oracle = JSON.parsefile(joinpath(@__DIR__, "reference", "phreeqc_databases.json"))["databases"]
    solutes = ["Na+" => 0.5, "K+" => 0.01, "Ca+2" => 0.01, "Mg+2" => 0.02, "Cl-" => 0.525, "SO4-2" => 0.02, "HCO3-" => 0.005]
    elements = Set([:H, :O, :Na, :K, :Ca, :Mg, :Cl, :S, :C])
    # The relative tolerance with PHREEQC's A and B, at 25 and 60 °C; `nothing`
    # where the model cannot be given them (the temperature terms of a Pitzer
    # set come with ChemistryLab's own A).
    tight = Dict(
        "phreeqc.dat" => (2.0e-5, 1.5e-4), "wateq4f.dat" => (2.0e-5, 1.5e-4),
        "minteq.v4.dat" => (2.0e-5, 1.5e-4), "llnl.dat" => (2.0e-5, 2.0e-5),
        "sit.dat" => (2.0e-5, 2.0e-5), "pitzer.dat" => (1.5e-4, nothing),
    )

    function with_phreeqc_AB(model, o, T)
        model isa TruesdellJonesActivityModel && return TruesdellJonesActivityModel(;
            parameters = model.parameters, A = o["DH_A"], B = o["DH_B"], water = :phreeqc,
        )
        model isa SITActivityModel && return SITActivityModel(;
            parameters = model.parameters, A = o["DH_A"], water = :osmotic,
        )
        model isa PitzerActivityModel && return PitzerActivityModel(;
            parameters = model.parameters, A = o["DH_A"], missing_pairs = :zero,
        )
        # The LLNL model takes its A and B from the database, as PHREEQC does.
        @test model isa LLNLActivityModel
        @test ChemistryLab._llnl_terms(model, T_ZERO_CELSIUS + T)[1] ≈ o["DH_A"] rtol = 1.0e-12
        return model
    end

    # The largest relative gap over the species PHREEQC finds above 1e-12 mol/kg.
    function worst_gap(db, eq, o)
        w = ustrip(us"mol", moles(eq, "H2O@")) * ustrip(us"kg/mol", eq.system.species[only(eq.system.idx_solvent)][:M])
        by_name = Dict(r.name => r for r in eachrow(db) if r.aggregate_state == AS_AQUEOUS)
        worst = 0.0
        for (name, m) in o["molality"]
            m < 1.0e-12 && continue
            sym = by_name[ChemistryLab._phreeqc_name(name)].symbol
            worst = max(worst, abs(ustrip(us"mol", moles(eq, sym)) / w / m - 1))
        end
        return worst
    end

    for (file, (tol25, tol60)) in sort!(collect(tight))
        _, db, _ = read_phreeqc_database(datapath(file))
        own = database_activity_model(db)
        @testset "$file" begin
            for case in ("speciation", "minerals")
                phases = case == "minerals" ? ["Calcite", "Gypsum"] : String[]
                names = [r.name for r in eachrow(db) if r.aggregate_state == AS_AQUEOUS && all(in(elements), keys(r.atoms))]
                cs = ChemicalSystem(build_species(db, vcat(names, phases)))
                for (T, tol) in ((25.0, tol25), (60.0, tol60))
                    o = oracle[file][case][string(T)]
                    st = ChemicalState(cs; T = (T_ZERO_CELSIUS + T) * u"K", P = 1.0u"Constants.atm")
                    set_quantity!(st, "H2O@", 1.0u"kg")
                    if case == "speciation"
                        for (s, m) in solutes
                            set_quantity!(st, s, m * u"mol")
                        end
                    else
                        set_quantity!(st, "Calcite", 10.0u"mol")
                        set_quantity!(st, "Gypsum", 10.0u"mol")
                    end
                    for (model, rtol) in ((own, 1.5e-2), (tol === nothing ? nothing : with_phreeqc_AB(own, o, T), tol))
                        model === nothing && continue
                        eq = equilibrate(st; model)
                        @test worst_gap(db, eq, o) < rtol
                        @test ionic_strength(eq) ≈ o["mu"] rtol = rtol
                        if case == "minerals"
                            for m in ("Calcite", "Gypsum")
                                @test 10 - ustrip(us"mol", moles(eq, m)) ≈ o["dissolved"][m] rtol = rtol
                            end
                        end
                        # PHREEQC's Pitzer reports single-ion activities on the
                        # MacInnes scale, which moves its pH by 0.03 here and no
                        # composition: the pH is compared under the other models.
                        own isa PitzerActivityModel || @test pH(eq, model) ≈ o["pH"] atol = 5.0e-3
                        rtol < 1.0e-3 && !(own isa PitzerActivityModel) && @test pH(eq, model) ≈ o["pH"] atol = 1.0e-4
                    end
                end
            end
        end
    end
end

@testsection "PHREEQC databases: gauge, notes, readers" begin
    # Two writings of one database, each with its own master species for carbon
    # (CO3-2 in the first, HCO3- in the second): the energies of the species
    # differ, the equilibrium does not. The constants are illustrative, not
    # those of any database.
    masters(c) = """
    SOLUTION_MASTER_SPECIES
    H     H+     -1.0  H     1.008
    H(1)  H+     -1.0  0
    E     e-      0.0  0     0.0
    O     H2O     0.0  O     16.0
    O(-2) H2O     0.0  0
    Ca    Ca+2    0.0  Ca    40.08
    C     $c      2.0  HCO3  12.0111
    C(4)  $c      2.0  HCO3
    SOLUTION_SPECIES
    H+ = H+
        -gamma 9.0 0.0
    e- = e-
    H2O = H2O
    Ca+2 = Ca+2
        -gamma 5.0 0.165
    H2O = OH- + H+
        -log_k -14.0
        -delta_h 55.9 kJ
        -gamma 3.5 0.0
    """
    a = masters("CO3-2") * """
        CO3-2 = CO3-2
            -gamma 5.4 0.0
        CO3-2 + H+ = HCO3-
            -log_k 10.3
            -delta_h -15.0 kJ
            -gamma 5.4 0.0
        CO3-2 + 2 H+ = CO2 + H2O
            -log_k 16.7
            -delta_h -24.0 kJ
        Ca+2 + CO3-2 = CaCO3
            -log_k 3.2
            -delta_h 15.0 kJ
        PHASES
        Calcite
            CaCO3 = CO3-2 + Ca+2
            -log_k -8.5
            -delta_h -10.0 kJ
        END
        """
    b = masters("HCO3-") * """
        HCO3- = HCO3-
            -gamma 5.4 0.0
        HCO3- = CO3-2 + H+
            -log_k -10.3
            -delta_h 15.0 kJ
            -gamma 5.4 0.0
        HCO3- + H+ = CO2 + H2O
            -log_k 6.4
            -delta_h -9.0 kJ
        Ca+2 + HCO3- = CaCO3 + H+
            -log_k -7.1
            -delta_h 30.0 kJ
        PHASES
        Calcite
            CaCO3 + H+ = HCO3- + Ca+2
            -log_k 1.8
            -delta_h -25.0 kJ
        END
        """
    mktempdir() do dir
        fa, fb = joinpath(dir, "a.dat"), joinpath(dir, "b.dat")
        write(fa, a)
        write(fb, b)
        (_, da, _), (_, db, _) = read_phreeqc_database(fa), read_phreeqc_database(fb)
        @test metadata(da, "gauge") != metadata(db, "gauge")
        @test only(unique(da.gauge)) == metadata(da, "gauge")
        sa, sb = build_species(da), build_species(db)
        ga = Dict(symbol(s) => s for s in sa)
        gb = Dict(symbol(s) => s for s in sb)
        T, P = T_ZERO_CELSIUS + 50.0, P_STANDARD
        # The energies differ by the gauge: CO3-2 is at zero in the first only.
        @test ga["CO3-2"][:ΔₐG⁰](T = T, P = P) == 0.0
        @test abs(gb["CO3-2"][:ΔₐG⁰](T = T, P = P)) > 1.0e4
        # A species defined by the same reaction in both has the same energy.
        @test ga["OH-"][:ΔₐG⁰](T = T, P = P) ≈ gb["OH-"][:ΔₐG⁰](T = T, P = P) rtol = 1.0e-12
        model = database_activity_model(da)
        for (Tc, tol) in ((25.0, 1.0e-9), (50.0, 1.0e-9))
            amounts = map((sa, sb)) do sp
                cs = ChemicalSystem(sp)
                st = ChemicalState(cs; T = (T_ZERO_CELSIUS + Tc) * u"K", P = 1.0u"Constants.atm")
                set_quantity!(st, "H2O@", 1.0u"kg")
                set_quantity!(st, "Calcite", 1.0u"mol")
                eq = equilibrate(st; model)
                Dict(s => ustrip(us"mol", moles(eq, s)) for s in ("Ca+2", "CO3-2", "HCO3-", "CO2@", "CaCO3@", "OH-", "H+"))
            end
            for s in keys(amounts[1])
                @test amounts[1][s] ≈ amounts[2][s] rtol = tol
            end
        end
        # Species of the two cannot be mixed in one system.
        err = try
            ChemicalSystem([ga["H2O@"], ga["H+"], gb["Ca+2"], gb["CO3-2"]])
        catch e
            e
        end
        @test err isa ArgumentError
        @test occursin("different zeros", sprint(showerror, err))

        # What the reader does not use is noted with its line: a species
        # defined again, an option the manual does not document, a pseudo-element,
        # an input block.
        fc = joinpath(dir, "c.dat")
        write(
            fc, masters("CO3-2") * """
                CO3-2 = CO3-2
                Ca+2 + CO3-2 = CaCO3
                    -log_k 3.0
                    -frobnicate 2
                Ca+2 + CO3-2 = CaCO3
                    -log_k 3.2
                    -delta_h 4184 J
                Ca+2 + 2 CO3-2 = Ca(CO3)2-2
                    -log_k 3.5
                    -delta_h 1.0 furlongs
                    -add_constant 0.5
                Ca+2 + H2O = CaOH+ + H+
                    -log_k -12.8
                    -add_logk Unnamed 1.0
                Ca+2 + CO3-2 = CaCO3:sorbed
                    -log_k 1.0
                    -cd_music 1 0 0 0 0
                Xx+2 + CO3-2 = XxCO3
                    -log_k 2.0
                Mtg = Mtg
                Mtg + Ca+2 = CaMtg+2
                    -log_k 1.0
                SOLUTION_MASTER_SPECIES
                Mtg     Mtg     0.0  Mtg  16.042
                PHASES
                    CaCO3 = CO3-2 + Ca+2
                Calcite
                    CaCO3 = CO3-2 + Ca+2
                    -log_k -8.5
                Xxite
                    XxCO3 = Xx+2 + CO3-2
                    -log_k -5.0
                SOLUTION_SPECIES
                    stray line
                KNOBS
                    -iterations 200
                END
                """,
        )
        _, dc, rc = read_phreeqc_database(fc)
        notes = metadata(dc, "notes")
        bysym = Dict(r.name => r for r in eachrow(dc))
        @test any(n -> occursin("CaCO3 is defined again", n), notes)
        @test any(n -> occursin("`-frobnicate`", n), notes)
        @test any(n -> occursin("CaMtg+2 is made of", n), notes)
        @test any(n -> occursin("KNOBS is an input block", n), notes)
        caco3 = bysym["CaCO3"]
        @test first(ChemistryLab._log10K(caco3.formation, T_STANDARD)) ≈ 3.2
        # An enthalpy in joules; a unit the manual does not name is taken as kJ.
        r = ChemistryLab._log10K(caco3.formation, T_STANDARD)
        @test r[2] ≈ 4184 / (R_GAS * log(10) * T_STANDARD^2) rtol = 1.0e-12
        # A constant added to log K, an expression that does not exist, an
        # electrostatic option, a species and a phase on an undefined species, an
        # equation in PHASES with no phase name, a line that belongs to no species.
        cc = bysym["Ca(CO3)2-2"]
        @test first(ChemistryLab._log10K(cc.formation, T_STANDARD)) ≈ 4.0
        @test any(n -> occursin("`-add_logk Unnamed`", n), notes)
        @test !haskey(bysym, "CaOH+")
        @test any(n -> occursin("`-cd_music` (a surface electrostatic option)", n), notes)
        @test any(n -> occursin("XxCO3 rests on a species the database does not define", n), notes)
        @test any(n -> occursin("phase Xxite rests on a species", n), notes)
        @test any(n -> occursin("an equation with no phase name", n), notes)
        @test any(n -> occursin("`stray line` belongs to no species", n), notes)
        # The reactions as written, each with its constant.
        @test only(rc[rc.symbol .== "Calcite", :equation]) == "CaCO3 = CO3-2 + Ca+2"
        @test "CO3-2" in rc.symbol

        # The electron used without being defined, as some databases do.
        fd = joinpath(dir, "d.dat")
        write(
            fd, """
            SOLUTION_MASTER_SPECIES
            H     H+     -1.0  H     1.008
            O     H2O     0.0  O     16.0
            SOLUTION_SPECIES
            H+ = H+
            H2O = H2O
            2 H2O = O2 + 4 H+ + 4 e-
                -log_k -86.08
            END
            """,
        )
        _, dd, _ = read_phreeqc_database(fd)
        o2 = only(r for r in eachrow(dd) if r.name == "O2")
        @test o2.atoms == Dict(:O => 2.0) && iszero(o2.charge)
    end

    # The parameters of `-gamma`, the master species, and the activity model of
    # each kind of database.
    γ = phreeqc_gamma_parameters(datapath("phreeqc.dat"))
    @test γ["Ca+2"] == (5.0, 0.165)
    primaries = extract_primary_species(datapath("phreeqc.dat"))
    @test "Ca+2" in primaries.symbol
    @test last(primaries.symbol) == "Zz"
    @test !("HCO3-" in primaries.symbol)
    @test database_activity_model(read_phreeqc_database(datapath("wateq4f.dat"))[2]) isa TruesdellJonesActivityModel

    # The LLNL model: its A, B and B-dot interpolated linearly in °C, refused
    # outside its grid, and its arguments checked.
    llnl = database_activity_model(read_phreeqc_database(datapath("llnl.dat"))[2])
    A, B, Bdot = ChemistryLab._llnl_terms(llnl, T_ZERO_CELSIUS + 120.0)[1:3]
    @test A ≈ 0.5995 + 0.4 * (0.6855 - 0.5995)
    @test Bdot ≈ 0.046 + 0.4 * 0.001
    @test_throws DomainError ChemistryLab._llnl_terms(llnl, T_ZERO_CELSIUS + 320.0)
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [25.0], A = [0.5], B = [0.3], Bdot = [0.04], co2 = zeros(5), sizes = Dict{String, Float64}())
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [0.0, 25.0], A = [0.5], B = [0.3, 0.3], Bdot = [0.04, 0.04], co2 = zeros(5), sizes = Dict{String, Float64}())
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [25.0, 0.0], A = [0.5, 0.5], B = [0.3, 0.3], Bdot = [0.04, 0.04], co2 = zeros(5), sizes = Dict{String, Float64}())
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [0.0, 25.0], A = [0.5, 0.5], B = [0.3, 0.3], Bdot = [0.04, 0.04], co2 = zeros(4), sizes = Dict{String, Float64}())
    @test_throws ArgumentError LLNLActivityModel(; temperatures = [0.0, 25.0], A = [0.5, 0.5], B = [0.3, 0.3], Bdot = [0.04, 0.04], co2 = zeros(5), sizes = Dict{String, Float64}(), water = :ideal)
    @test_throws ArgumentError TruesdellJonesActivityModel(; parameters = Dict{String, Tuple{Float64, Float64}}(), water = :ideal)
    @test_throws ArgumentError SITActivityModel(; water = :ideal)
    @test_throws ArgumentError PitzerActivityModel(; parameters = build_pitzer_parameters(datapath("pitzer-reardon1990.toml")), missing_pairs = :ignore)

    # The kinds of species of the LLNL model, and PHREEQC's activity of water,
    # held at its bound past the 59 mol/kg where it has no value.
    toy = LLNLActivityModel(;
        temperatures = [0.0, 100.0], A = [0.5, 0.6], B = [0.33, 0.34], Bdot = [0.04, 0.05],
        co2 = (-1.0312, 0.0012806, 255.9, 0.4445, -0.001606), sizes = Dict("Na+" => 4.0, "SiO2@" => 3.0),
        co2_species = ["CO2@"], gamma = Dict("K+" => (3.5, 0.015)), water = :phreeqc,
    )
    terms = ChemistryLab._llnl_terms(toy, T_STANDARD)
    I, sI = 0.5, sqrt(0.5)
    @test ChemistryLab._llnl_log10γ((0, 0.0, 0.0), 1, I, sI, terms[1], terms[2:5]) == 0.0
    @test ChemistryLab._llnl_log10γ((3, 3.5, 0.015), 1, I, sI, terms[1], terms[2:5]) ≈ 0.015 * I
    @test ChemistryLab._llnl_log10γ((2, 0.0, 0.0), 0, I, sI, terms[1], terms[2:5]) ≈
        (terms[4] * I - terms[5] * I / (1 + I)) / log(10)
    # The coefficients a state reports are those of the closure: an ion with a
    # size, carbon dioxide, a neutral species with a size (γ = 1).
    _, db_llnl, _ = read_phreeqc_database(datapath("llnl.dat"))
    cs = ChemicalSystem(build_species(db_llnl, ["H2O", "H+", "OH-", "Na+", "Cl-", "HCO3-", "CO3-2", "CO2", "NaCl"]))
    st = ChemicalState(cs; T = (T_ZERO_CELSIUS + 60.0) * u"K", P = 1.0u"Constants.atm")
    set_quantity!(st, "H2O@", 1.0u"kg")
    set_quantity!(st, "Na+", 0.5u"mol")
    set_quantity!(st, "Cl-", 0.49u"mol")
    set_quantity!(st, "HCO3-", 0.01u"mol")
    eq = equilibrate(st; model = llnl)
    γs = activity_coefficients(eq, llnl)
    A60, B60, Bd60, c1, c2 = ChemistryLab._llnl_terms(llnl, T_ZERO_CELSIUS + 60.0)
    Ieq = ionic_strength(eq)
    @test log10(γs["Na+"]) ≈ -A60 * sqrt(Ieq) / (1 + 4.0 * B60 * sqrt(Ieq)) + Bd60 * Ieq rtol = 1.0e-6
    @test log10(γs["CO2@"]) ≈ (c1 * Ieq - c2 * Ieq / (1 + Ieq)) / log(10) rtol = 1.0e-6
    @test γs["NaCl@"] ≈ 1.0
    # An element outside the order the package writes formulas in.
    @test length(build_species(db_llnl, ["ZnCl+", "LiCl"])) == 2
    Mw = ustrip(us"kg/mol", Species("H2O")[:M])
    @test ChemistryLab._solvent_lna(:phreeqc, 1.0, 2.0, 1.0, Mw) ≈ log(1 - ChemistryLab._PHREEQC_WATER_COEFFICIENT / Mw)
    @test isfinite(ChemistryLab._solvent_lna(:phreeqc, 1.0, 101.0, 100.0, Mw))
end

# The readers of PHREEQC files share one scanner of blocks, one reader of
# equations and one rule for names, and the readers of the other formats the same
# rule. Each test fails on the readers as they were, each with its own rules.
@testsection "One rule for the names and the blocks of every reader" begin
    # The rule: `(aq)` dropped, `@` on a neutral species, water the solvent, a
    # run of signs a charge.
    @test ChemistryLab._solute_symbol("CaSO4(aq)") == "CaSO4@"
    @test ChemistryLab._solute_symbol("CaSO4(AQ)") == "CaSO4@"
    @test ChemistryLab._solute_symbol("H2O") == "H2O@"
    @test ChemistryLab._solute_symbol("Na+") == "Na+"
    @test ChemistryLab._phreeqc_name("SO4--") == "SO4-2"
    @test ChemistryLab._phreeqc_name("Na+1") == "Na+"

    mktempdir() do dir
        # PITZER: `SO4--` was kept as written (no species of a system is named
        # so) and `CaSO4(aq)` became `CaSO4(aq)@`; a coefficient line at the
        # first column ended the block, and its remaining lines were lost.
        pz = joinpath(dir, "pitzer-names.dat")
        write(
            pz, """
            PITZER
            -B0
              Na+   SO4--   0.0195
            Ca+2  Cl-   0.3159
            -LAMDA
              CaSO4(aq)  Na+   0.1
            -THETA
              K+  Na+  -0.012
            END
            """,
        )
        p = build_pitzer_parameters(pz; format = :phreeqc)
        @test p.beta0[("Na+", "SO4-2")] == 0.0195
        @test p.beta0[("Ca+2", "Cl-")] == 0.3159
        @test p.lambda[("CaSO4@", "Na+")] == 0.1
        @test p.theta[("K+", "Na+")] == -0.012

        # SIT: a line of another shape ended the reading; it is now reported,
        # and the lines after it are read.
        st = joinpath(dir, "sit-names.dat")
        write(
            st, """
            SIT
            -epsilon
              Na+   SO4--   -0.12
              Na+   Cl-   0.03   0.0
              K+    Cl-   0.00
            END
            """,
        )
        q = @test_logs (:warn, r"Na\+   Cl-   0.03   0.0") build_sit_parameters(st)
        @test value(sit_epsilon(q, "Na+", "SO4-2")) == -0.12
        @test value(sit_epsilon(q, "K+", "Cl-")) == 0.0
        @test sit_epsilon(q, "Na+", "Cl-") === nothing

        # Sorption: logical lines split at semicolons as in every PHREEQC
        # block (the constant of the first reaction was lost with the line it
        # shared), a block given twice read twice, a run of signs a charge, and
        # the comment of the line kept on both pieces.
        so = joinpath(dir, "sorption-names.dat")
        write(
            so, """
            SURFACE_MASTER_SPECIES
                Hfo_w   Hfo_wOH
            SURFACE_SPECIES
                Hfo_wOH = Hfo_wOH; -log_k 0.0
                Hfo_wOH + Ca++ = Hfo_wOCa+ + H+; -log_k 4.97   # ref: Dzombak:1990:bk: error: 0.1
            SURFACE_SPECIES
                Hfo_wOH + H+ = Hfo_wOH2+
                -log_k 7.29
            END
            """,
        )
        m = read_sorption_model(so)
        # The identity reaction of the master species produces nothing and
        # belongs to no site; the two others are read.
        rs = m.surfaces["Hfo_w"].reactions
        @test length(rs) == 2
        ca = only(r for r in rs if haskey(r.stoichiometry, "Ca+2"))
        @test ca.stoichiometry == Dict("Hfo_wOH" => -1, "Ca+2" => -1, "Hfo_wOCa+" => 1, "H+" => 1)
        @test value(ca.log_K) == 4.97
        @test source(ca.log_K) == "Dzombak:1990:bk:"
        @test uncertainty(ca.log_K) == 0.1
        @test any(r -> haskey(r.stoichiometry, "Hfo_wOH2+"), rs)
    end

    # `log_k` without its dash, as llnl.dat, minteq.v4.dat, wateq4f.dat and
    # pitzer.dat write it in their SURFACE_SPECIES: their constants were all
    # passed over, and their sorption models read without a reaction.
    for f in ("llnl.dat", "minteq.v4.dat", "wateq4f.dat", "pitzer.dat")
        rs = read_sorption_model(datapath(f)).surfaces["Hfo_w"].reactions
        protonation = only(r for r in rs if haskey(r.stoichiometry, "Hfo_wOH2+"))
        @test value(protonation.log_K) == 7.29
    end

    # A sorption reaction names its aqueous partners as a database does: a
    # neutral one is found under the symbol the readers give it.
    s = Species("H4SiO4"; symbol = "H4SiO4@", aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
    lookup = Dict("H4SiO4@" => s)
    @test ChemistryLab._aqueous_participant(lookup, "H4SiO4", "f") === s
    @test ChemistryLab._aqueous_participant(Dict("H2O@" => s), "H2O", "f") === s
    @test_throws ArgumentError ChemistryLab._aqueous_participant(lookup, "SiO2", "f")
end
