# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2025-2026 Jean-François Barthélémy and Anthony Soive (Cerema, UMR MCD)

using ChemistryLab
using DynamicQuantities
using ForwardDiff
using JSON
using SciMLBase
using Test

using ChemistryLab: value, source

include("reference_species.jl")

# ── The matched PHREEQC case ──────────────────────────────────────────────────
#
# Generated by `test/reference/phreeqc_sit.py`.
#
# The fixture carries, per point, the molality AND the activity coefficient
# PHREEQC computed for every species — so this compares the ACTIVITY FORMULA and
# nothing else. The Julia side evaluates its own SIT at PHREEQC's composition:
# no speciation, no log K and no convergence path enters the comparison, which
# is what makes it a test of the equation rather than of two databases.
#
# The ε travel with the fixture because the compilation is not ours to ship:
# `sit.dat` is the ANDRA/RWM ThermoChimie-TDB, redistributed with PHREEQC but
# not USGS-authored. Three coefficients, named and sourced, keep the test
# runnable in CI without redistributing five hundred.
const PHREEQC_SIT = reference_oracle("phreeqc_sit")

_sit_parameters() = SITParameters(
    [
        (e.a, e.b) => Traced(e.value, PROV_PUBLISHED, PHREEQC_SIT.database)
            for e in PHREEQC_SIT.epsilon
    ];
    source = "$(PHREEQC_SIT.database) sha256 $(first(PHREEQC_SIT.database_sha256, 12))",
)

function _sit_system()
    h2o, hp, oh, na, cl = reference_species(("H2O@", "H+", "OH-", "Na+", "Cl-"))
    cs = ChemicalSystem([h2o, hp, oh, na, cl], [h2o, hp, na, cl])
    return cs, Dict(symbol(sp) => k for (k, sp) in enumerate(cs.species))
end

@testsection "SIT, the model the NEA reviews are calibrated in" begin

    @testset "a compilation says where each coefficient came from" begin
        p = SITParameters(
            [("Na+", "Cl-") => 0.03]; source = "a source", kind = PROV_PUBLISHED,
        )
        @test length(p) == 1
        @test !isempty(p)
        # Symmetric in the pair, because SIT sums over opposite charges and the
        # pair is unordered — one coefficient, reachable either way round.
        @test value(sit_epsilon(p, "Na+", "Cl-")) == 0.03
        @test value(sit_epsilon(p, "Cl-", "Na+")) == 0.03
        @test sit_epsilon(p, "Na+", "SO4-2") === nothing
        @test source(sit_epsilon(p, "Na+", "Cl-")) == "a source"
        @test is_evidence(sit_epsilon(p, "Na+", "Cl-"))

        # The same pair twice with two values is the compilation contradicting
        # itself, not a last-one-wins.
        @test_throws ArgumentError SITParameters(
            [("Na+", "Cl-") => 0.03, ("Cl-", "Na+") => 0.09],
        )
        # ...but the same value twice is simply the same statement twice.
        @test length(SITParameters([("Na+", "Cl-") => 0.03, ("Cl-", "Na+") => 0.03])) == 1

        # Provenance survives being put in and taken out, which is the point of
        # the type: a borrowed coefficient must not become indistinguishable
        # from a measured one on the way through.
        q = SITParameters(
            [("Al(OH)4-", "Na+") => Traced(0.05, PROV_ESTIMATED, "analog: SO4-2")];
            source = "a compilation", kind = PROV_PUBLISHED,
        )
        # A BORROWED COEFFICIENT KEEPS ITS OWN STANDING. It does not inherit
        # the compilation's, which is the whole reason the provenance is on the
        # value and not on the table.
        c = sit_epsilon(q, "Na+", "Al(OH)4-")
        @test provenance(c) === PROV_ESTIMATED
        @test !is_evidence(c)
        @test source(c) == "analog: SO4-2"
        @test occursin("estimated", sprint(show, c))
        # and the report says so about the compilation as a whole
        r = provenance_report(values(q.epsilon))
        @test r.weakest === PROV_ESTIMATED
        @test !r.all_evidence

        @test isempty(SITParameters())
        @test occursin("empty", sprint(show, SITParameters()))
    end

    @testset "the model, and the convention it cannot have changed" begin
        m = SITActivityModel()
        @test m.A ≈ 0.509
        @test m.b ≈ 1.5                     # the SIT convention, not a fit
        @test isempty(m.parameters)         # never silently a full calculation
        @test_throws ArgumentError SITActivityModel(; b = 0.0)
        @test_throws ArgumentError SITActivityModel(; b = -1.5)
        @test occursin("SITActivityModel", sprint(show, m))
    end

    @testset "reading a compilation rather than transcribing one" begin
        # A PHREEQC-format block written here on purpose: the point is to test
        # the reader, and the real compilation is not this package's to carry.
        path = joinpath(mktempdir(), "tiny-sit.dat")
        write(
            path, """
            # a minimal PHREEQC database
            SIT
            -epsilon

                Na+     Cl-     0.03
                H+      Cl-     0.12   # with a trailing comment
                Na+     SO4-2   -0.12

            SOLUTION_SPECIES
                H2O = H2O
                log_k 0.0
            """,
        )
        p = build_sit_parameters(path)
        @test length(p) == 3
        @test value(sit_epsilon(p, "Na+", "Cl-")) == 0.03
        @test value(sit_epsilon(p, "H+", "Cl-")) == 0.12
        @test value(sit_epsilon(p, "Na+", "SO4-2")) == -0.12
        # The block ends at the next keyword; nothing after it is read as a pair.
        @test sit_epsilon(p, "H2O", "H2O") === nothing
        # And the source names the file and its content, so a coefficient can
        # always be traced back.
        @test occursin("tiny-sit.dat", p.source)
        @test occursin("sha256", p.source)

        @test_throws ArgumentError build_sit_parameters(joinpath(dirname(path), "nope.dat"))
        # A database with no SIT block is refused by name rather than returning
        # an empty compilation that would silently be Debye-Hückel.
        plain = joinpath(dirname(path), "plain.dat")
        write(plain, "SOLUTION_SPECIES\n    H2O = H2O\n    log_k 0.0\n")
        @test_throws ArgumentError build_sit_parameters(plain)
    end
end

@testsection "SIT against PHREEQC, on the formula alone" begin
    params = _sit_parameters()
    model = SITActivityModel(; parameters = params)
    cs, idx = _sit_system()
    lna = activity_model(cs, model)
    ln10 = log(10.0)

    @testset "the closed form, by hand, at one molar" begin
        # log₁₀γ = −z² A√I/(1 + 1.5√I) + Σ ε m, and at I = 1 with NaCl alone
        # that is −0.509/2.5 + 0.03 = −0.1736. Worth writing out once: the whole
        # difference between SIT and Davies is that second term, and a test that
        # only compared against another code would not say what is being tested.
        I = 1.0
        by_hand = -0.509 * sqrt(I) / (1 + 1.5 * sqrt(I)) + 0.03 * 1.0
        @test by_hand ≈ -0.1736 atol = 1.0e-4

        n = fill(1.0e-12, length(cs.species))
        n[idx["H2O@"]] = moles_of_water()
        n[idx["Na+"]] = 1.0
        n[idx["Cl-"]] = 1.0
        out = lna(n, (; ϵ = 1.0e-30, T = 298.15))
        log10γ = (out[idx["Na+"]] - log(1.0)) / ln10
        @test log10γ ≈ by_hand rtol = 1.0e-6
    end

    @testset "seven points, four decades of ionic strength" begin
        # The signature of SIT is that γ turns around: the pairwise term
        # eventually beats the Debye-Hückel one. A model without it cannot
        # reproduce both ends of this range, which is why the range is the test.
        worst, turned = 0.0, false
        prev = nothing
        for pt in PHREEQC_SIT.points
            n = fill(1.0e-12, length(cs.species))
            n[idx["H2O@"]] = moles_of_water()
            for (name, sp) in pairs(pt.species)
                n[idx[String(name)]] = sp.molality
            end
            out = lna(n, (; ϵ = 1.0e-30, T = 298.15))
            for (name, sp) in pairs(pt.species)
                i = idx[String(name)]
                log10γ = (out[i] - log(sp.molality)) / ln10
                worst = max(worst, abs(log10γ - sp.log_gamma))
            end
            g = pt.species.var"Na+".log_gamma
            prev !== nothing && g > prev && (turned = true)
            prev = g
        end
        @test turned                     # γ really does come back up
        @info "SIT against PHREEQC, worst |Δ log₁₀γ|" worst
        # Measured at 1.4e-3. The residual is the Debye-Hückel slope: PHREEQC
        # recomputes `A` from water properties and this runs at the 25 °C
        # value 0.509, which at I = 3 is worth about a millifraction of a log
        # unit. It is NOT the ε, which are the same three numbers on both sides.
        @test worst < 5.0e-3
    end

    @testset "which pairs the compilation does not carry" begin
        # An unlisted ε is taken as zero by the SIT literature. That is a
        # convention and never a measurement, so a caller can ask which of its
        # pairs are resting on it.
        sub, _ = _sit_system()
        miss = missing_epsilon_pairs(sub, model)
        @test ("H+", "OH-") in miss || ("OH-", "H+") in miss
        @test !(("Na+", "Cl-") in miss) && !(("Cl-", "Na+") in miss)
        # Like-charged and neutral pairs are not missing; they are not summed.
        @test !any(p -> "Na+" in p && "H+" in p, miss)
        # Adding the absent pairs to the compilation empties the list, which is
        # what says the report is about coverage and not about something else.
        filled = SITParameters(
            vcat(
                [(a, b) => 0.0 for (a, b) in miss],
                [(k[1], k[2]) => value(c) for (k, c) in params.epsilon],
            ),
        )
        @test isempty(
            missing_epsilon_pairs(sub, SITActivityModel(; parameters = filled)),
        )
    end

    @testset "it differentiates" begin
        # Through the composition, which is what an inverse problem needs, and
        # through the coefficient itself, which is what CALIBRATING one needs.
        n = fill(1.0e-12, length(cs.species))
        n[idx["H2O@"]] = moles_of_water()
        n[idx["Na+"]] = 1.0
        n[idx["Cl-"]] = 1.0

        g = ForwardDiff.gradient(x -> lna(x, (; ϵ = 1.0e-30, T = 298.15))[idx["Na+"]], n)
        @test all(isfinite, g)
        @test g[idx["Cl-"]] != 0          # the pairwise term is visible in it

        dε = ForwardDiff.derivative(
            e -> begin
                m = SITActivityModel(;
                    parameters = SITParameters([("Na+", "Cl-") => e]),
                )
                activity_model(cs, m)(n, (; ϵ = 1.0e-30, T = 298.15))[idx["Na+"]]
            end, 0.03,
        )
        # ∂ln a(Na⁺)/∂ε = ln10 · m(Cl⁻) — the coefficient enters linearly, which
        # is why identifying one from data is a well-posed question.
        @test dε ≈ log(10.0) * 1.0 rtol = 1.0e-6
    end
end
