# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2025-2026 Jean-François Barthélémy and Anthony Soive (Cerema, UMR MCD)

using ChemistryLab
using DynamicQuantities
using ForwardDiff
using SciMLBase
using Test

const RT25 = 8.31446261815324 * 298.15

# An amphoteric surface, which is the physics of every oxide and also the one
# shape in which competition has a **closed form under a single constraint**:
# both occupied states are driven by the proton activity, so
#
#     β₁ = K₁ a_H        (XsOH + H⁺ ⇌ XsOH₂⁺)
#     β₂ = K₂ / a_H      (XsOH ⇌ XsO⁻ + H⁺)
#
# and ideal site mixing gives the competitive Langmuir form with its shared
# denominator, without an isotherm being written anywhere:
#
#     n_j / N = β_j / (1 + β₁ + β₂)
#
# The standard energies below are chosen to *be* those constants, so the oracle
# is derived rather than fitted.
_g0(value) = SymbolicFunc(value * u"J/mol")

function _amphoteric_system(; logK1 = 7.0, logK2 = -9.0, n_sites = 1.0e-3)
    h2o = Species("H2O@"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLVENT)
    h2o[:ΔₐG⁰] = _g0(-237181.0)
    h2o[:M] = 0.018015u"kg/mol"
    h2o[:V⁰] = SymbolicFunc(1.807e-5u"m^3/mol")

    hp = Species("H+"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
    hp[:ΔₐG⁰] = _g0(0.0)
    oh = Species("OH-"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
    oh[:ΔₐG⁰] = _g0(-157297.0)

    free = Species("XsOH"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    free[:ΔₐG⁰] = _g0(0.0)
    prot = Species("XsOH2+"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    prot[:ΔₐG⁰] = _g0(-RT25 * log(10.0^logK1))
    depr = Species("XsO-"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    depr[:ΔₐG⁰] = _g0(-RT25 * log(10.0^logK2))

    support = SurfaceSupport("oxide", nothing, FixedSurfaceArea(1.0))
    family = SiteFamily(
        "Xs", free, [prot, depr];
        capacity = TotalSiteAmount(n_sites), support,
    )
    species = [h2o, hp, oh, free, prot, depr]
    cs = ChemicalSystem(species, [h2o, hp, free]; site_families = [family])

    n = Any[fill(1.0e-12u"mol", length(cs.species))...]
    n[1] = 55.5u"mol"
    n[4] = n_sites * u"mol"          # all sites free to start with
    return cs, ChemicalState(cs, n), family
end

# The closed form the plan derives: a shared denominator is the signature of a
# finite capacity, and it is what makes this a test of competition rather than
# of two isotherms side by side.
_langmuir(β) = (1 ./ (1 + sum(β)), β ./ (1 + sum(β)))

# ── The matched PHREEQC case ──────────────────────────────────────────────────
#
# Generated by `test/reference/phreeqc_hfo_surface.py --case protolysis`. Paste
# the block it prints, header included: the version of every piece and the md5
# of the database are what make this reproducible rather than merely recorded.
#
# What matches, and what deliberately does not. The two log K are PHREEQC's own,
# read from its database by the generator rather than typed here. The comparison
# is made at **matched proton activity**, which `Fix_H+` on one side and
# `FixedpH` on the other both prescribe exactly — so the aqueous activity model,
# which differs between the two codes, does not enter. With no metal in the
# system there is nothing else it could enter through. That is the narrowest
# honest comparison, and narrowing it is the point: it isolates the surface
# chemistry, which is what this release adds.
# generated by test/reference/phreeqc_hfo_surface.py
# python       3.12.14
# phreeqpython 1.6.2
# database     phreeqc.dat  md5 fca384eb269fda632fcefa6f74c8f90e
# model        no_edl, weak sites only, no metal
# sites        0.0002 mol
# log K        protonation 7.29, deprotonation -8.93
const PHREEQC_PROTOLYSIS = (
    logK_protonation = 7.29,
    logK_deprotonation = -8.93,
    n_sites = 0.0002,
    points = [
        (pH = 4.0, la_H = -4.0, free = 0.0005125984889321876, protonated = 0.9994873954885607, deprotonated = 6.022507113121253e-9),
        (pH = 5.0, la_H = -5.0, free = 0.005102442309144079, protonated = 0.9948969582061565, deprotonated = 5.994846993233386e-7),
        (pH = 6.0, la_H = -6.0, free = 0.0487813899152302, protonated = 0.9511612969490318, deprotonated = 5.731313573795587e-5),
        (pH = 7.0, la_H = -7.0, free = 0.33765605393582376, protonated = 0.658376833342379, deprotonated = 0.003967112721797296),
        (pH = 8.0, la_H = -8.0, free = 0.7619197300893887, protonated = 0.14856250711639016, deprotonated = 0.08951776279422106),
        (pH = 9.0, la_H = -9.0, free = 0.455706262485419, protonated = 0.00888556394983117, deprotonated = 0.5354081735647499),
    ],
)

# ── Two families on one support: Dzombak & Morel's ferrihydrite ───────────────
#
# Generated by `test/reference/phreeqc_hfo_surface.py --case zn-edge`.
#
# The two families differ in exactly two ways — the strong sites are forty times
# scarcer and bind zinc about a thousand times more strongly — and share their
# protolysis constants. That contrast is what produces a sorption edge rather
# than a single smooth curve.
# generated by test/reference/phreeqc_hfo_surface.py
# python       3.12.14
# phreeqpython 1.6.2
# database     phreeqc.dat  md5 fca384eb269fda632fcefa6f74c8f90e
# model        no_edl
# Fe           0.001 mol -> strong 5e-06, weak 0.0002 mol
# Zn total     1e-05 mol/kgw
const PHREEQC_HFO_ZN = (
    logK_protonation = 7.29,
    logK_deprotonation = -8.93,
    logK_zn_strong = 0.99,
    logK_zn_weak = -1.99,
    n_strong = 5.0e-6,
    n_weak = 0.0002,
    zn_total = 1.0e-5,
    points = [
        (pH = 4.0, la_H = -4.0, la_Zn = -5.185138490125704, s_free = 2.562154433971782e-9, s_prot = 4.995802986826005e-6, s_depr = 3.0102689798509237e-14, s_zn = 1.6348082217479586e-9, w_free = 1.02519662256492e-7, w_prot = 0.00019989740981983975, w_depr = 1.2045010051837894e-12, w_zn = 6.849654667554699e-11, zn_free = 9.815116717770936e-6, zn_sorbed_fraction = 0.00017033047684235052),
        (pH = 5.0, la_H = -5.0, la_Zn = -5.1914005129500085, s_free = 2.4718965460702547e-8, s_prot = 4.819814131515647e-6, s_depr = 2.9042252080414057e-12, s_zn = 1.5546397854754539e-7, w_free = 1.0204541674107353e-6, w_prot = 0.00019897270476264172, w_depr = 1.1989291062187247e-10, w_zn = 6.720367001603556e-9, zn_free = 9.658133783949691e-6, zn_sorbed_fraction = 0.016218434554914892),
        (pH = 6.0, la_H = -6.0, la_Zn = -5.386450540389415, s_free = 8.245784848101475e-8, s_prot = 1.6077999056837405e-6, s_depr = 9.687952456591873e-11, s_zn = 3.309645347459107e-6, w_free = 9.736316210593181e-6, w_prot = 0.0001898430358476183, w_depr = 1.143917410994405e-8, w_zn = 4.092080134460339e-7, zn_free = 6.161096800883752e-6, zn_sorbed_fraction = 0.37188533609051405),
        (pH = 7.0, la_H = -7.0, la_Zn = -6.200927421320358, s_free = 7.753192610410841e-8, s_prot = 1.511752074229357e-7, s_depr = 9.109207040946931e-10, s_zn = 4.7703819364614295e-6, w_free = 6.609338861596599e-5, w_prot = 0.00012887183687255126, w_depr = 7.76529606825665e-7, w_zn = 4.258244532359745e-6, zn_free = 9.437120668726694e-7, zn_sorbed_fraction = 0.9028626468821174),
        (pH = 8.0, la_H = -8.0, la_Zn = -7.471499477584883, s_free = 1.4572393171909458e-7, s_prot = 2.8413902131798714e-8, s_depr = 1.712106910729392e-8, s_zn = 4.808741179098876e-6, w_free = 0.00014847497259009844, w_prot = 2.8950312350402767e-5, w_depr = 1.744428822658206e-5, w_zn = 5.130430115199375e-6, zn_free = 5.056055260744571e-8, zn_sorbed_fraction = 0.9939171294298249),
        (pH = 9.0, la_H = -9.0, la_Zn = -8.250538418622458, s_free = 8.759576588032303e-8, s_prot = 1.7079813106341766e-9, s_depr = 1.0291605115584693e-7, s_zn = 4.807781207204123e-6, w_free = 8.881514289031195e-5, w_prot = 1.7317572674141364e-6, w_depr = 0.00010434869422343237, w_zn = 5.104445840881339e-6, zn_free = 8.401202338101974e-9, zn_sorbed_fraction = 0.991222704808546),
    ],
)

# Both families of the HFO model, with a metal that binds to each. Built from
# PHREEQC's own constants, so the standard energies below *are* those log K.
function _hfo_system(; background = 0.01)
    f = PHREEQC_HFO_ZN
    sf(sym, g) = begin
        s = Species(sym; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        s[:ΔₐG⁰] = _g0(g)
        s
    end
    aq(sym, g, cl = SC_AQSOLUTE) = begin
        s = Species(sym; aggregate_state = AS_AQUEOUS, class = cl)
        s[:ΔₐG⁰] = _g0(g)
        s
    end
    mRT(logK) = -RT25 * log(10.0^logK)

    h2o = aq("H2O@", -237181.0, SC_AQSOLVENT); h2o[:M] = 0.018015u"kg/mol"
    hp, oh = aq("H+", 0.0), aq("OH-", -157297.0)
    zn = aq("Zn+2", 0.0)
    na, cl = aq("Na+", -261881.0), aq("Cl-", -131290.0)

    s_free, s_prot = sf("XsOH", 0.0), sf("XsOH2+", mRT(f.logK_protonation))
    s_depr, s_zn = sf("XsO-", mRT(f.logK_deprotonation)), sf("XsOZn+", mRT(f.logK_zn_strong))
    w_free, w_prot = sf("XwOH", 0.0), sf("XwOH2+", mRT(f.logK_protonation))
    w_depr, w_zn = sf("XwO-", mRT(f.logK_deprotonation)), sf("XwOZn+", mRT(f.logK_zn_weak))

    support = SurfaceSupport("hydrous ferric oxide", nothing, FixedSurfaceArea(53.4))
    fam_s = SiteFamily(
        "Hfo_s", s_free, [s_prot, s_depr, s_zn];
        capacity = TotalSiteAmount(f.n_strong), support,
    )
    fam_w = SiteFamily(
        "Hfo_w", w_free, [w_prot, w_depr, w_zn];
        capacity = TotalSiteAmount(f.n_weak), support,
    )

    species = [
        h2o, hp, oh, zn, na, cl,
        s_free, s_prot, s_depr, s_zn, w_free, w_prot, w_depr, w_zn,
    ]
    cs = ChemicalSystem(
        species, [h2o, hp, zn, na, cl, s_free, w_free]; site_families = [fam_s, fam_w],
    )
    idx = Dict(symbol(sp) => k for (k, sp) in enumerate(cs.species))

    n0 = Any[fill(1.0e-14u"mol", length(cs.species))...]
    # Exactly one kilogram of water, so amounts and molalities share a basis with
    # PHREEQC's `-water 1`.
    n0[idx["H2O@"]] = (1.0 / 0.018015)u"mol"
    n0[idx["Na+"]] = background * u"mol"
    n0[idx["Cl-"]] = background * u"mol"
    n0[idx["Zn+2"]] = f.zn_total * u"mol"
    n0[idx["XsOH"]] = f.n_strong * u"mol"
    n0[idx["XwOH"]] = f.n_weak * u"mol"
    return cs, ChemicalState(cs, n0), idx
end

@testsection "Surface complexation" begin

    @testset "a site activity is a site fraction, in every activity model" begin
        cs, st, _ = _amphoteric_system()
        n = Float64[ustrip(us"mol", x) for x in st.n]
        # A composition with all three states populated, so the fractions are
        # not degenerate.
        n[4], n[5], n[6] = 5.0e-4, 3.0e-4, 2.0e-4
        p = ChemistryLab._build_params(st)
        N = n[4] + n[5] + n[6]

        for model in (
                DiluteSolutionModel(), HKFActivityModel(), DaviesActivityModel(),
            )
            lna = activity_model(cs, model)(n, p)
            for i in 4:6
                @test lna[i] ≈ log(n[i] / N) rtol = 1.0e-9
            end
        end
    end

    @testset "the mixing differentiates" begin
        cs, st, _ = _amphoteric_system()
        n0 = Float64[ustrip(us"mol", x) for x in st.n]
        n0[4], n0[5], n0[6] = 5.0e-4, 3.0e-4, 2.0e-4
        p = ChemistryLab._build_params(st)
        lna = activity_model(cs, DiluteSolutionModel())

        J = ForwardDiff.jacobian(nn -> lna(nn, p), n0)
        @test all(isfinite, J[4:6, 4:6])
        # d(ln x_i)/dn_i = 1/n_i − 1/N, exactly, and the cross term is −1/N:
        # the free site is coupled to every occupied state, which is what makes
        # saturation a shared effect rather than a per-species one.
        N = n0[4] + n0[5] + n0[6]
        @test J[4, 4] ≈ 1 / n0[4] - 1 / N rtol = 1.0e-6
        @test J[4, 5] ≈ -1 / N rtol = 1.0e-6
        @test J[5, 4] ≈ -1 / N rtol = 1.0e-6
    end

    @testset "competitive Langmuir falls out of the site balance" begin
        logK1, logK2, n_sites = 7.0, -9.0, 1.0e-3
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        A = Float64.(cs.SM.A)
        b = A * Float64[ustrip(us"mol", x) for x in st.n]

        for target_pH in (4.0, 6.0, 8.0, 10.0)
            q = Base.RefValue{Any}(nothing)
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(target_pH), parameters = q,
            )
            n = Float64[ustrip(us"mol", x) for x in eq.n]

            # The prescribed quantity is the activity, so read it back rather
            # than assume the target was reached.
            p = ChemistryLab._build_params(eq)
            a_H = exp(des.lna(n, p)[2])

            β = [10.0^logK1 * a_H, 10.0^logK2 / a_H]
            x_free, x_occ = _langmuir(β)

            N = n[4] + n[5] + n[6]
            @test N ≈ n_sites rtol = 1.0e-8            # sites are conserved
            @test n[4] / N ≈ x_free rtol = 1.0e-6
            @test n[5] / N ≈ x_occ[1] rtol = 1.0e-6
            @test n[6] / N ≈ x_occ[2] rtol = 1.0e-6
        end
    end

    @testset "saturation, and the surface activity coefficient it makes unnecessary" begin
        # A drive strong enough to fill the sites: at pH 2 with logK₁ = 7 the
        # protonation drive is β₁ = 1e5, so the free sites are nearly gone.
        logK1, logK2, n_sites = 7.0, -9.0, 1.0e-3
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
        q = Base.RefValue{Any}(nothing)
        eq = SciMLBase.solve(des, st; b = b, constraint = FixedpH(2.0), parameters = q)
        n = Float64[ustrip(us"mol", x) for x in eq.n]

        N = n[4] + n[5] + n[6]
        θ = (n[5] + n[6]) / N                      # occupied fraction
        @test θ > 0.999
        @test n[4] / N < 1.0e-3                    # free sites nearly exhausted

        # Kulik's 2006 surface activity coefficient, γ_L = 1/(1 − θ), is what an
        # *eliminated* free site needs in order to reproduce what an explicit one
        # already produces. Here the identity is a check, not a correction:
        # applying γ_L on top of this mixing would count saturation twice.
        @test 1 / (1 - θ) ≈ N / n[4] rtol = 1.0e-8
    end

    @testset "matched against PHREEQC, at matched proton activity" begin
        f = PHREEQC_PROTOLYSIS
        cs, st, _ = _amphoteric_system(;
            logK1 = f.logK_protonation, logK2 = f.logK_deprotonation,
            n_sites = f.n_sites,
        )
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]

        worst = 0.0
        for pt in f.points
            q = Base.RefValue{Any}(nothing)
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(pt.pH), parameters = q,
            )
            n = Float64[ustrip(us"mol", x) for x in eq.n]
            p = ChemistryLab._build_params(eq)

            # PHREEQC prescribed the activity, so check ours is the same one
            # before comparing anything that depends on it.
            la_H = des.lna(n, p)[2] / log(10)
            @test la_H ≈ pt.la_H atol = 1.0e-6

            N = n[4] + n[5] + n[6]
            for (got, want) in (
                    (n[4] / N, pt.free), (n[5] / N, pt.protonated),
                    (n[6] / N, pt.deprotonated),
                )
                @test got ≈ want rtol = 1.0e-5
                worst = max(worst, abs(got / want - 1))
            end
        end
        # Reported rather than only asserted: a margin that shrinks is visible
        # before it becomes a failure. Measured at 1.7e-8 over the six points.
        @info "PHREEQC protolysis: worst relative deviation" worst
        @test worst < 1.0e-5
    end

    @testset "residuals, one scale per conserved quantity" begin
        # A single absolute tolerance across water, a trace species and a site
        # budget compares numbers ten orders of magnitude apart. Each conserved
        # quantity is scaled by its own total instead.
        #
        # This solve is **closed** — no constraint — precisely so that charge can
        # be checked. `FixedpH` holds the proton activity by titrating, so under
        # it the proton row and the charge balance are the constraint's to move,
        # not the solver's to conserve, and checking them there would be
        # checking the wrong thing.
        logK1, logK2, n_sites = 7.29, -8.93, 2.0e-4
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        A = Float64.(cs.SM.A)
        n0 = Float64[ustrip(us"mol", x) for x in st.n]
        b = A * n0
        eq = SciMLBase.solve(des, st; b = b)
        n = Float64[ustrip(us"mol", x) for x in eq.n]
        r = A * n .- b

        # The scale of a conservation row is how much matter it *moves*, not its
        # net budget. A perfectly balanced row has a budget of exactly zero —
        # here the proton row does, the initial traces canceling — and dividing
        # by that compares a residual with nothing at all.
        turnover(c) = sum(abs(A[c, i]) * n[i] for i in eachindex(n))
        for c in eachindex(b)
            scale = max(abs(b[c]), turnover(c), eps())
            @test abs(r[c]) / scale < 1.0e-9
        end

        # The site row on its own, against the site budget rather than against
        # the water: it is the row this release adds, and the one whose failure
        # would be silent.
        i_site = findfirst(p -> symbol(p) == "XsOH", cs.SM.primaries)
        @test abs(r[i_site]) / b[i_site] < 1.0e-10

        # And the budget is what was put in, floors included — `b` rather than
        # the nominal capacity, because the two differ by the trace amounts the
        # initial state carries and the solver conserves the first, exactly.
        @test (n[4] + n[5] + n[6]) ≈ b[i_site] rtol = 1.0e-10

        # Charge. The surface states are charged, the initial composition is
        # neutral, and a closed system must stay so.
        z = Float64[charge(sp) for sp in cs.species]
        scale = max(sum(abs, z .* n), eps())
        @test abs(sum(z .* n0)) / scale < 1.0e-8      # it started neutral
        @test abs(sum(z .* n)) / scale < 1.0e-8       # and it stayed neutral
    end

    @testset "two families on one support, and a metal between them" begin
        f = PHREEQC_HFO_ZN
        cs, st, idx = _hfo_system()
        @test length(cs.site_groups) == 2
        @test length(cs.idx_surface) == 8

        des = DualEquilibriumSolver(cs, DaviesActivityModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]

        worst = 0.0
        for pt in f.points
            eq = SciMLBase.solve(des, st; b = b, constraint = FixedpH(pt.pH))
            n = Float64[ustrip(us"mol", x) for x in eq.n]

            # Each family keeps its own budget. Two families sharing one support
            # is the structural novelty here, and this is what it has to mean.
            Ns = sum(n[i] for i in cs.site_groups[1])
            Nw = sum(n[i] for i in cs.site_groups[2])
            @test Ns ≈ f.n_strong rtol = 1.0e-8
            @test Nw ≈ f.n_weak rtol = 1.0e-8

            sorbed = (n[idx["XsOZn+"]] + n[idx["XwOZn+"]]) / f.zn_total
            phreeqc = pt.zn_sorbed_fraction
            # Below 1 % sorbed the comparison is between two very small numbers
            # and says more about either code's floor than about the model.
            phreeqc < 0.01 && continue
            worst = max(worst, abs(sorbed / phreeqc - 1))
        end

        # The tolerance comes from the measurement, with a factor of two of
        # margin: the worst departure is 0.94 %, and it is the *lowest* point of
        # the edge, where 1.6 % of the zinc is sorbed and a relative comparison
        # magnifies a small absolute difference. A threshold set at the measured
        # value would be a test that reports the machine it ran on.
        #
        # What the remaining gap is, is measured in the next testset rather than
        # asserted: it is the aqueous activity model, not the surface model.
        @info "HFO zinc edge against PHREEQC, Davies" worst
        @test worst < 0.02
    end

    @testset "and the gap that remains is the aqueous model, measured" begin
        # The surface model matches PHREEQC to 1.7e-8 where no metal is involved.
        # With one, the two codes differ — and the difference is not in the
        # surface chemistry but in what each says the metal's activity is.
        #
        # Zn²⁺ carries two charges, so its activity coefficient departs from one
        # fast: about 0.72 at I = 0.01 by Davies. An ideal model puts it at 1 and
        # therefore drives more sorption. Running the same system both ways turns
        # that explanation into a measurement.
        f = PHREEQC_HFO_ZN
        cs, st, idx = _hfo_system()
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]

        gaps = map((DiluteSolutionModel(), DaviesActivityModel())) do model
            des = DualEquilibriumSolver(cs, model)
            worst = 0.0
            for pt in f.points
                pt.zn_sorbed_fraction < 0.01 && continue
                eq = SciMLBase.solve(des, st; b = b, constraint = FixedpH(pt.pH))
                n = Float64[ustrip(us"mol", x) for x in eq.n]
                sorbed = (n[idx["XsOZn+"]] + n[idx["XwOZn+"]]) / f.zn_total
                worst = max(worst, abs(sorbed / pt.zn_sorbed_fraction - 1))
            end
            worst
        end
        ideal_gap, davies_gap = gaps

        @info "worst gap to PHREEQC" ideal = ideal_gap davies = davies_gap
        # Ideal activities are off by tens of percent; Davies by under two.
        @test ideal_gap > 0.1
        @test davies_gap < 0.02
        # And the improvement is an order of magnitude, which is the attribution.
        @test ideal_gap / davies_gap > 10
    end

    @testset "a system without a surface is unchanged" begin
        # The kernel must be a no-op when nothing declares a site, in all four
        # activity models — the guard against a regression reaching every solve.
        h2o = Species("H2O@"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLVENT)
        h2o[:ΔₐG⁰] = _g0(-237181.0)
        h2o[:M] = 0.018015u"kg/mol"
        hp = Species("H+"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
        hp[:ΔₐG⁰] = _g0(0.0)
        oh = Species("OH-"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
        oh[:ΔₐG⁰] = _g0(-157297.0)
        cs = ChemicalSystem([h2o, hp, oh], [h2o, hp])
        st = ChemicalState(cs, Any[55.5u"mol", 1.0e-7u"mol", 1.0e-7u"mol"])
        n = Float64[ustrip(us"mol", x) for x in st.n]
        p = ChemistryLab._build_params(st)

        @test isempty(cs.site_groups)
        for model in (DiluteSolutionModel(), HKFActivityModel(), DaviesActivityModel())
            lna = activity_model(cs, model)(n, p)
            @test all(isfinite, lna)
            @test length(lna) == 3
        end
    end

end
