# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2025-2026 Jean-François Barthélémy and Anthony Soive (Cerema, UMR MCD)

using ChemistryLab
using DynamicQuantities
using JSON
using ForwardDiff
using LinearAlgebra
using SciMLBase
using Test

const RT25 = ChemistryLab.R_GAS * 298.15
include("reference_species.jl")


# An amphoteric surface, which is the physics of every oxide and also the one
# shape in which competition has a **closed form under a single constraint**:
# both occupied states are driven by the proton activity, so
#
#     β₁ = K₁ a_H        (XsOH + H⁺ ⇌ XsOH₂⁺)
#     β₂ = K₂ / a_H      (XsOH ⇌ XsO⁻ + H⁺)
#
# and ideal site mixing gives the competitive Langmuir form with its shared
# denominator, without an isotherm being written anywhere:
#
#     n_j / N = β_j / (1 + β₁ + β₂)
#
# The standard energies below are chosen to *be* those constants, so the oracle
# is derived rather than fitted.
_g0(value) = SymbolicFunc(value * u"J/mol")

function _amphoteric_system(; logK1 = 7.0, logK2 = -9.0, n_sites = 1.0e-3)
    # Aqueous species from the shipped database; only the surface species are
    # built here, because their standard energies ARE the log K under test.
    h2o, hp, oh = reference_species(("H2O@", "H+", "OH-"))

    free = Species("XsOH"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    free[:ΔₐG⁰] = _g0(0.0)
    prot = Species("XsOH2+"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    prot[:ΔₐG⁰] = _g0(-RT25 * log(10.0^logK1))
    depr = Species("XsO-"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    depr[:ΔₐG⁰] = _g0(-RT25 * log(10.0^logK2))

    support = SurfaceSupport("oxide", nothing, FixedSurfaceArea(1.0))
    family = SiteFamily(
        "Xs", free, [prot, depr];
        capacity = TotalSiteAmount(n_sites), support,
    )
    species = [h2o, hp, oh, free, prot, depr]
    cs = ChemicalSystem(species, [h2o, hp, free]; site_families = [family])

    n = Any[fill(1.0e-12u"mol", length(cs.species))...]
    n[1] = moles_of_water() * u"mol"
    n[4] = n_sites * u"mol"          # all sites free to start with
    return cs, ChemicalState(cs, n), family
end

# The closed form the plan derives: a shared denominator is the signature of a
# finite capacity, and it is what makes this a test of competition rather than
# of two isotherms side by side.
_langmuir(β) = (1 ./ (1 + sum(β)), β ./ (1 + sum(β)))

# ── The matched PHREEQC case ──────────────────────────────────────────────────
#
# Generated by `test/reference/phreeqc_hfo_surface.py --case protolysis`. Paste
# the block it prints, header included: the version of every piece and the md5
# of the database are what make this reproducible rather than merely recorded.
#
# What matches, and what deliberately does not. The two log K are PHREEQC's own,
# read from its database by the generator rather than typed here. The comparison
# is made at **matched proton activity**, which `Fix_H+` on one side and
# `FixedpH` on the other both prescribe exactly — so the aqueous activity model,
# which differs between the two codes, does not enter. With no metal in the
# system there is nothing else it could enter through. That is the narrowest
# honest comparison, and narrowing it is the point: it isolates the surface
# chemistry, which is what this release adds.
# generated by test/reference/phreeqc_hfo_surface.py
# python       3.12.14
# phreeqpython 1.6.2
# database     phreeqc.dat  md5 fca384eb269fda632fcefa6f74c8f90e
# model        no_edl, weak sites only, no metal
# sites        0.0002 mol
# log K        protonation 7.29, deprotonation -8.93
const PHREEQC_PROTOLYSIS = reference_oracle("phreeqc_protolysis")

# ── Two families on one support: Dzombak & Morel's ferrihydrite ───────────────
#
# Generated by `test/reference/phreeqc_hfo_surface.py --case zn-edge`.
#
# The two families differ in exactly two ways — the strong sites are forty times
# scarcer and bind zinc about a thousand times more strongly — and share their
# protolysis constants. That contrast is what produces a sorption edge rather
# than a single smooth curve.
# generated by test/reference/phreeqc_hfo_surface.py
# python       3.12.14
# phreeqpython 1.6.2
# database     phreeqc.dat  md5 fca384eb269fda632fcefa6f74c8f90e
# model        no_edl
# Fe           0.001 mol -> strong 5e-06, weak 0.0002 mol
# Zn total     1e-05 mol/kgw
const PHREEQC_HFO_ZN = reference_oracle("phreeqc_hfo_zn")

# The SAME experiment with the double layer on — PHREEQC's default `SURFACE`
# rather than `-no_edl`. It is a different model, not a refinement: the edge
# moves by about half a pH unit, from 0.372 sorbed at pH 6 to 0.182. That shift
# is what makes this a gate rather than a formality.
const PHREEQC_HFO_ZN_DDL = reference_oracle("phreeqc_hfo_zn_ddl")

# Both families of the HFO model, with a metal that binds to each. Built from
# PHREEQC's own constants, so the standard energies below *are* those log K.
function _hfo_system(;
        background = 0.01, chloride = background, model = IdealSiteMixing(),
        f = PHREEQC_HFO_ZN,
    )
    sf(sym, g) = begin
        s = Species(sym; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        s[:ΔₐG⁰] = _g0(g)
        s
    end
    aq(sym, g, cl = SC_AQSOLUTE) = begin
        s = Species(sym; aggregate_state = AS_AQUEOUS, class = cl)
        s[:ΔₐG⁰] = _g0(g)
        s
    end
    mRT(logK) = -RT25 * log(10.0^logK)

    h2o, hp, oh, zn, na, cl =
        reference_species(("H2O@", "H+", "OH-", "Zn+2", "Na+", "Cl-"))
    # The zinc complexes carry the aqueous zinc's own standard energy, because
    # XsOH + Zn²⁺ = XsOZn⁺ + H⁺ puts it in the balance:
    #   G(XsOZn⁺) = −RT ln K + G(Zn²⁺),  with G(XsOH) = G(H⁺) = 0 by the gauge.
    # An earlier version set G(Zn²⁺) to zero, which made the arithmetic trivial
    # and the species fictitious.
    G_ZN = ustrip(us"J/mol", zn[:ΔₐG⁰](T = 298.15u"K", P = 1.0e5u"Pa"; unit = true))

    s_free, s_prot = sf("XsOH", 0.0), sf("XsOH2+", mRT(f.logK_protonation))
    s_depr = sf("XsO-", mRT(f.logK_deprotonation))
    s_zn = sf("XsOZn+", mRT(f.logK_zn_strong) + G_ZN)
    w_free, w_prot = sf("XwOH", 0.0), sf("XwOH2+", mRT(f.logK_protonation))
    w_depr = sf("XwO-", mRT(f.logK_deprotonation))
    w_zn = sf("XwOZn+", mRT(f.logK_zn_weak) + G_ZN)

    support = SurfaceSupport("hydrous ferric oxide", nothing, FixedSurfaceArea(53.4))
    fam_s = SiteFamily(
        "Hfo_s", s_free, [s_prot, s_depr, s_zn];
        capacity = TotalSiteAmount(f.n_strong), support, model,
    )
    fam_w = SiteFamily(
        "Hfo_w", w_free, [w_prot, w_depr, w_zn];
        capacity = TotalSiteAmount(f.n_weak), support, model,
    )

    species = [
        h2o, hp, oh, zn, na, cl,
        s_free, s_prot, s_depr, s_zn, w_free, w_prot, w_depr, w_zn,
    ]
    cs = ChemicalSystem(
        species, [h2o, hp, zn, na, cl, s_free, w_free]; site_families = [fam_s, fam_w],
    )
    idx = Dict(symbol(sp) => k for (k, sp) in enumerate(cs.species))

    n0 = Any[fill(1.0e-14u"mol", length(cs.species))...]
    # Exactly one kilogram of water, so amounts and molalities share a basis with
    # PHREEQC's `-water 1`.
    n0[idx["H2O@"]] = moles_of_water() * u"mol"
    n0[idx["Na+"]] = background * u"mol"
    n0[idx["Cl-"]] = chloride * u"mol"
    n0[idx["Zn+2"]] = f.zn_total * u"mol"
    n0[idx["XsOH"]] = f.n_strong * u"mol"
    n0[idx["XwOH"]] = f.n_weak * u"mol"
    return cs, ChemicalState(cs, n0), idx
end

@testsection "Surface complexation" begin

    @testset "a site activity is a site fraction, in every activity model" begin
        cs, st, _ = _amphoteric_system()
        n = Float64[ustrip(us"mol", x) for x in st.n]
        # A composition with all three states populated, so the fractions are
        # not degenerate.
        n[4], n[5], n[6] = 5.0e-4, 3.0e-4, 2.0e-4
        p = ChemistryLab._build_params(st)
        N = n[4] + n[5] + n[6]

        # All four, not three. A site fraction owes nothing to the ionic
        # strength of the solution beside it, so every aqueous model has to
        # apply the same site mixing — and one that skips it leaves its surface
        # species at `ln a = 0`, unit activity, which is a plausible number and
        # a wrong one. Pitzer is the one that would have been forgotten.
        pitzer = PitzerActivityModel(;
            parameters = build_pitzer_parameters(datapath("pitzer-reardon1990.toml")),
        )
        for model in (
                DiluteSolutionModel(), HKFActivityModel(), DaviesActivityModel(), pitzer,
            )
            lna = activity_model(cs, model)(n, p)
            for i in 4:6
                @test lna[i] ≈ log(n[i] / N) rtol = 1.0e-9
            end
        end
    end

    @testset "the mixing differentiates" begin
        cs, st, _ = _amphoteric_system()
        n0 = Float64[ustrip(us"mol", x) for x in st.n]
        n0[4], n0[5], n0[6] = 5.0e-4, 3.0e-4, 2.0e-4
        p = ChemistryLab._build_params(st)
        lna = activity_model(cs, DiluteSolutionModel())

        J = ForwardDiff.jacobian(nn -> lna(nn, p), n0)
        @test all(isfinite, J[4:6, 4:6])
        # d(ln x_i)/dn_i = 1/n_i − 1/N, exactly, and the cross term is −1/N:
        # the free site is coupled to every occupied state, which is what makes
        # saturation a shared effect rather than a per-species one.
        N = n0[4] + n0[5] + n0[6]
        @test J[4, 4] ≈ 1 / n0[4] - 1 / N rtol = 1.0e-6
        @test J[4, 5] ≈ -1 / N rtol = 1.0e-6
        @test J[5, 4] ≈ -1 / N rtol = 1.0e-6
    end

    @testset "competitive Langmuir falls out of the site balance" begin
        logK1, logK2, n_sites = 7.0, -9.0, 1.0e-3
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        A = Float64.(cs.SM.A)
        b = A * Float64[ustrip(us"mol", x) for x in st.n]

        for target_pH in (4.0, 6.0, 8.0, 10.0)
            q = Base.RefValue{Any}(nothing)
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(target_pH), parameters = q,
            )
            n = Float64[ustrip(us"mol", x) for x in eq.n]

            # The prescribed quantity is the activity, so read it back rather
            # than assume the target was reached.
            p = ChemistryLab._build_params(eq)
            a_H = exp(des.lna(n, p)[2])

            β = [10.0^logK1 * a_H, 10.0^logK2 / a_H]
            x_free, x_occ = _langmuir(β)

            N = n[4] + n[5] + n[6]
            @test N ≈ n_sites rtol = 1.0e-8            # sites are conserved
            @test n[4] / N ≈ x_free rtol = 1.0e-6
            @test n[5] / N ≈ x_occ[1] rtol = 1.0e-6
            @test n[6] / N ≈ x_occ[2] rtol = 1.0e-6
        end
    end

    @testset "saturation, and the surface activity coefficient it makes unnecessary" begin
        # A drive strong enough to fill the sites: at pH 2 with logK₁ = 7 the
        # protonation drive is β₁ = 1e5, so the free sites are nearly gone.
        logK1, logK2, n_sites = 7.0, -9.0, 1.0e-3
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
        q = Base.RefValue{Any}(nothing)
        eq = SciMLBase.solve(des, st; b = b, constraint = FixedpH(2.0), parameters = q)
        n = Float64[ustrip(us"mol", x) for x in eq.n]

        N = n[4] + n[5] + n[6]
        θ = (n[5] + n[6]) / N                      # occupied fraction
        @test θ > 0.999
        @test n[4] / N < 1.0e-3                    # free sites nearly exhausted

        # Kulik's 2006 surface activity coefficient, γ_L = 1/(1 − θ), is what an
        # *eliminated* free site needs in order to reproduce what an explicit one
        # already produces. Here the identity is a check, not a correction:
        # applying γ_L on top of this mixing would count saturation twice.
        @test 1 / (1 - θ) ≈ N / n[4] rtol = 1.0e-8
    end

    @testset "matched against PHREEQC, at matched proton activity" begin
        f = PHREEQC_PROTOLYSIS
        cs, st, _ = _amphoteric_system(;
            logK1 = f.logK_protonation, logK2 = f.logK_deprotonation,
            n_sites = f.n_sites,
        )
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]

        worst = 0.0
        for pt in f.points
            q = Base.RefValue{Any}(nothing)
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(pt.pH), parameters = q,
            )
            n = Float64[ustrip(us"mol", x) for x in eq.n]
            p = ChemistryLab._build_params(eq)

            # PHREEQC prescribed the activity, so check ours is the same one
            # before comparing anything that depends on it.
            la_H = des.lna(n, p)[2] / log(10)
            @test la_H ≈ pt.la_H atol = 1.0e-6

            N = n[4] + n[5] + n[6]
            for (got, want) in (
                    (n[4] / N, pt.free), (n[5] / N, pt.protonated),
                    (n[6] / N, pt.deprotonated),
                )
                @test got ≈ want rtol = 1.0e-5
                worst = max(worst, abs(got / want - 1))
            end
        end
        # Reported rather than only asserted: a margin that shrinks is visible
        # before it becomes a failure. Measured at 1.7e-8 over the six points.
        @info "PHREEQC protolysis: worst relative deviation" worst
        @test worst < 1.0e-5
    end

    @testset "residuals, one scale per conserved quantity" begin
        # A single absolute tolerance across water, a trace species and a site
        # budget compares numbers ten orders of magnitude apart. Each conserved
        # quantity is scaled by its own total instead.
        #
        # This solve is **closed** — no constraint — precisely so that charge can
        # be checked. `FixedpH` holds the proton activity by titrating, so under
        # it the proton row and the charge balance are the constraint's to move,
        # not the solver's to conserve, and checking them there would be
        # checking the wrong thing.
        logK1, logK2, n_sites = 7.29, -8.93, 2.0e-4
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        A = Float64.(cs.SM.A)
        n0 = Float64[ustrip(us"mol", x) for x in st.n]
        b = A * n0
        eq = SciMLBase.solve(des, st; b = b)
        n = Float64[ustrip(us"mol", x) for x in eq.n]
        r = A * n .- b

        # The scale of a conservation row is how much matter it *moves*, not its
        # net budget. A perfectly balanced row has a budget of exactly zero —
        # here the proton row does, the initial traces canceling — and dividing
        # by that compares a residual with nothing at all.
        turnover(c) = sum(abs(A[c, i]) * n[i] for i in eachindex(n))
        for c in eachindex(b)
            scale = max(abs(b[c]), turnover(c), eps())
            @test abs(r[c]) / scale < 1.0e-9
        end

        # The site row on its own, against the site budget rather than against
        # the water: it is the row this release adds, and the one whose failure
        # would be silent.
        i_site = findfirst(p -> symbol(p) == "XsOH", cs.SM.primaries)
        @test abs(r[i_site]) / b[i_site] < 1.0e-10

        # And the budget is what was put in, floors included — `b` rather than
        # the nominal capacity, because the two differ by the trace amounts the
        # initial state carries and the solver conserves the first, exactly.
        @test (n[4] + n[5] + n[6]) ≈ b[i_site] rtol = 1.0e-10

        # Charge. The surface states are charged, the initial composition is
        # neutral, and a closed system must stay so.
        z = Float64[charge(sp) for sp in cs.species]
        scale = max(sum(abs, z .* n), eps())
        @test abs(sum(z .* n0)) / scale < 1.0e-8      # it started neutral
        @test abs(sum(z .* n)) / scale < 1.0e-8       # and it stayed neutral
    end

    @testset "two families on one support, and a metal between them" begin
        f = PHREEQC_HFO_ZN
        cs, st, idx = _hfo_system()
        @test length(cs.site_groups) == 2
        @test length(cs.idx_surface) == 8

        des = DualEquilibriumSolver(cs, DaviesActivityModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]

        worst = 0.0
        for pt in f.points
            eq = SciMLBase.solve(des, st; b = b, constraint = FixedpH(pt.pH))
            n = Float64[ustrip(us"mol", x) for x in eq.n]

            # Each family keeps its own budget. Two families sharing one support
            # is the structural novelty here, and this is what it has to mean.
            Ns = sum(n[i] for i in cs.site_groups[1])
            Nw = sum(n[i] for i in cs.site_groups[2])
            @test Ns ≈ f.n_strong rtol = 1.0e-8
            @test Nw ≈ f.n_weak rtol = 1.0e-8

            sorbed = (n[idx["XsOZn+"]] + n[idx["XwOZn+"]]) / f.zn_total
            phreeqc = pt.zn_sorbed_fraction
            # Below 1 % sorbed the comparison is between two very small numbers
            # and says more about either code's floor than about the model.
            phreeqc < 0.01 && continue
            worst = max(worst, abs(sorbed / phreeqc - 1))
        end

        # The tolerance comes from the measurement, with a factor of two of
        # margin: the worst departure is 0.94 %, and it is the *lowest* point of
        # the edge, where 1.6 % of the zinc is sorbed and a relative comparison
        # magnifies a small absolute difference. A threshold set at the measured
        # value would be a test that reports the machine it ran on.
        #
        # What the remaining gap is, is measured in the next testset rather than
        # asserted: it is the aqueous activity model, not the surface model.
        @info "HFO zinc edge against PHREEQC, Davies" worst
        @test worst < 0.02
    end

    @testset "and the gap that remains is the aqueous model, measured" begin
        # The surface model matches PHREEQC to 1.7e-8 where no metal is involved.
        # With one, the two codes differ — and the difference is not in the
        # surface chemistry but in what each says the metal's activity is.
        #
        # Zn²⁺ carries two charges, so its activity coefficient departs from one
        # fast: about 0.72 at I = 0.01 by Davies. An ideal model puts it at 1 and
        # therefore drives more sorption. Running the same system both ways turns
        # that explanation into a measurement.
        f = PHREEQC_HFO_ZN
        cs, st, idx = _hfo_system()
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]

        gaps = map((DiluteSolutionModel(), DaviesActivityModel())) do model
            des = DualEquilibriumSolver(cs, model)
            worst = 0.0
            for pt in f.points
                pt.zn_sorbed_fraction < 0.01 && continue
                eq = SciMLBase.solve(des, st; b = b, constraint = FixedpH(pt.pH))
                n = Float64[ustrip(us"mol", x) for x in eq.n]
                sorbed = (n[idx["XsOZn+"]] + n[idx["XwOZn+"]]) / f.zn_total
                worst = max(worst, abs(sorbed / pt.zn_sorbed_fraction - 1))
            end
            worst
        end
        ideal_gap, davies_gap = gaps

        @info "worst gap to PHREEQC" ideal = ideal_gap davies = davies_gap
        # Ideal activities are off by tens of percent; Davies by under two.
        @test ideal_gap > 0.1
        @test davies_gap < 0.02
        # And the improvement is an order of magnitude, which is the attribution.
        @test ideal_gap / davies_gap > 10
    end

    @testset "the same edge with the double layer on — Dzombak & Morel's model" begin
        # THE GATE THE ZINC PAGE HAS BEEN LEAVING OPEN. Everything above runs
        # `-no_edl` on both sides, which is a fair cross-code check and is not
        # the model the published constants were fitted in. This is.
        #
        # It is also the first case where two families share one surface AND
        # carry a potential, and that is not a detail: a proton on a weak site
        # charges the same oxide a proton on a strong site does. A potential
        # computed per family would make the two electrostatically invisible to
        # each other and is not this model.
        f = PHREEQC_HFO_ZN_DDL
        @test length(
            unique(
                surface_support(fam).name
                    for fam in _hfo_system(; f)[1].site_families
            )
        ) == 1                                   # one surface, two families
        @test length(_hfo_system(; f)[1].site_families) == 2

        worst, n_certified = 0.0, 0
        for pt in f.points
            # The ionic strength is matched to PHREEQC's, which its own titrant
            # moves; the chloride carries the difference.
            cs, st, idx = _hfo_system(;
                background = 0.01,
                chloride = 2 * pt.I - 0.01 - 10.0^(-pt.pH) - 10.0^(pt.pH - 14),
                model = DiffuseLayer(; area = f.area), f,
            )
            des = DualEquilibriumSolver(cs, DaviesActivityModel())
            b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(pt.pH),
                parameters = Base.RefValue{Any}(nothing),
            )
            cert = optimality_certificate(des, eq; b = b, constraint = FixedpH(pt.pH))
            cert.stationarity < 1.0e-8 || continue
            n_certified += 1
            n = Float64[ustrip(us"mol", x) for x in eq.n]
            sorbed = (n[idx["XsOZn+"]] + n[idx["XwOZn+"]]) / f.zn_total
            # Only where there is a zinc front to compare: below 1 % sorbed the
            # relative figure is the ratio of two numbers near zero.
            pt.zn_sorbed_fraction < 0.01 && continue
            worst = max(worst, abs(sorbed / pt.zn_sorbed_fraction - 1))
        end
        @test n_certified == length(f.points)
        @info "zinc edge, diffuse layer: worst relative gap to PHREEQC" worst
        @test worst < 0.05

        # AND IT IS A DIFFERENT ANSWER, not a rounding of the previous one. The
        # layer moves the edge by about half a pH unit; a test that passed both
        # fixtures would be testing nothing.
        plain = Dict(pt.pH => pt.zn_sorbed_fraction for pt in PHREEQC_HFO_ZN.points)
        shifted = maximum(
            abs(pt.zn_sorbed_fraction - plain[pt.pH]) for pt in f.points
        )
        @test shifted > 0.15
    end

    @testset "a charged surface: the model, and where the solve stops" begin
        # Hydrous ferric oxide's real geometry, because this term is a surface
        # *density* effect and an unphysical one makes nonsense of it: 2e-4 mol
        # of sites on 1 m² would put σ at 96 C/m², a hundred times anything
        # measured, and every exponential in the model with it.
        N, A = 2.0e-4, 53.4
        _sys(model) = begin
            cs, st, _ = _amphoteric_system(; logK1 = 7.29, logK2 = -8.93, n_sites = N)
            fam = SiteFamily(
                "Xs", cs.species[4], cs.species[5:6];
                capacity = TotalSiteAmount(N), support = SurfaceSupport(
                    "oxide", nothing, FixedSurfaceArea(A)
                ), model,
            )
            cs2 = ChemicalSystem(
                cs.species, cs.SM.primaries; site_families = [fam],
            )
            n = Any[fill(1.0e-12u"mol", length(cs2.species))...]
            n[1] = moles_of_water() * u"mol"; n[4] = N * u"mol"
            (cs2, ChemicalState(cs2, n))
        end

        # ── the shift is exactly z_k ψ̃, evaluated rather than trusted ──────
        C = 3.0
        cs_e, st_e = _sys(ConstantCapacitance(; C = C, area = A))
        cs_i, _ = _sys(IdealSiteMixing())
        n = zeros(length(cs_e.species))
        n[1] = moles_of_water(); n[2] = 1.0e-5; n[3] = 1.0e-9
        n[4], n[5], n[6] = 0.2N, 0.8N, 1.0e-14
        p = (ϵ = 1.0e-30, T = 298.15)
        lna_e = activity_model(cs_e, DiluteSolutionModel())(n, p)
        lna_i = activity_model(cs_i, DiluteSolutionModel())(n, p)
        ψ = FARADAY^2 * (n[5] - n[6]) / (C * A * R_GAS * 298.15)
        @test lna_e[4] ≈ lna_i[4] rtol = 1.0e-12          # neutral, untouched
        @test lna_e[5] - lna_i[5] ≈ ψ rtol = 1.0e-10      # z = +1, penalized
        @test lna_e[6] - lna_i[6] ≈ -ψ rtol = 1.0e-10     # z = −1, favored

        # ── convex, and measured so ───────────────────────────────────────
        # G_el is a quadratic form with Hessian (F²/CA) z zᵀ, positive
        # semi-definite. Its second derivative along the charge direction is the
        # only non-zero eigenvalue, and it must be positive.
        gel(m) = FARADAY^2 * (m[5] - m[6])^2 / (2 * C * A * R_GAS * 298.15)
        H = ForwardDiff.hessian(gel, n)
        @test issymmetric(round.(H; digits = 12))
        @test minimum(eigvals(H[4:6, 4:6])) > -1.0e-8     # no negative curvature
        @test maximum(eigvals(H[4:6, 4:6])) ≈ 2 * FARADAY^2 / (C * A * R_GAS * 298.15) rtol =
            1.0e-8

        # ── an infinite capacitance is no electrostatics at all ───────────
        for pH in (5.0, 7.0)
            solve_at(cs, st, pH) = begin
                des = DualEquilibriumSolver(cs, DiluteSolutionModel())
                b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
                eq = SciMLBase.solve(des, st; b = b, constraint = FixedpH(pH))
                m = Float64[ustrip(us"mol", x) for x in eq.n]
                m[5] / (m[4] + m[5] + m[6])
            end
            # The approach is `O(1/C)`: at C = 1000 the residual stiffness is
            # still ψ̃_max ≈ 0.014 and the protonation differs in the third
            # digit. Taking C large enough that ψ̃_max is 1e-5 makes the limit
            # unambiguous rather than approximate.
            cs_big, st_big = _sys(ConstantCapacitance(; C = 1.0e6, area = A))
            cs_id, st_id = _sys(IdealSiteMixing())
            @test solve_at(cs_big, st_big, pH) ≈ solve_at(cs_id, st_id, pH) rtol = 1.0e-4
        end

        # ── and a real capacitance does what the physics says ─────────────
        # A surface already charged resists charging further, so at an acid pH
        # it protonates *less*. Measured: 0.995 without, 0.81 at C = 3 F/m².
        cs_c, st_c = _sys(ConstantCapacitance(; C = C, area = A))
        des_c = DualEquilibriumSolver(cs_c, DiluteSolutionModel())
        b_c = Float64.(cs_c.SM.A) * Float64[ustrip(us"mol", x) for x in st_c.n]
        eq_c = SciMLBase.solve(des_c, st_c; b = b_c, constraint = FixedpH(5.0))
        m = Float64[ustrip(us"mol", x) for x in eq_c.n]
        prot = m[5] / (m[4] + m[5] + m[6])
        cert = optimality_certificate(des_c, eq_c; b = b_c, constraint = FixedpH(5.0))
        @test cert.stationarity < 1.0e-10        # the solve is found, not guessed
        @test 0.7 < prot < 0.9                   # and it is damped, not saturated

        # ── the limit, stated as a number rather than discovered ──────────
        # ψ̃_max is the dimensionless stiffness the elimination puts into an
        # activity. Below about 5 the Newton finds the minimum; above it, it does
        # not — and convexity says that is the solver, since the minimum is
        # unique. The formulation with Ψ as an unknown is what lifts it.
        ψmax(c) = FARADAY^2 * N / (c * A * R_GAS * 298.15)
        @test ψmax(3.0) < 5.0
        @test ψmax(1.2) > 10.0
    end

    @testset "a system without a surface is unchanged" begin
        # The kernel must be a no-op when nothing declares a site, in all four
        # activity models — the guard against a regression reaching every solve.
        h2o, hp, oh = reference_species(("H2O@", "H+", "OH-"))
        cs = ChemicalSystem([h2o, hp, oh], [h2o, hp])
        st = ChemicalState(cs, Any[moles_of_water() * u"mol", 1.0e-7u"mol", 1.0e-7u"mol"])
        n = Float64[ustrip(us"mol", x) for x in st.n]
        p = ChemistryLab._build_params(st)

        @test isempty(cs.site_groups)
        pitzer = PitzerActivityModel(;
            parameters = build_pitzer_parameters(datapath("pitzer-reardon1990.toml")),
        )
        for model in (
                DiluteSolutionModel(), HKFActivityModel(), DaviesActivityModel(), pitzer,
            )
            lna = activity_model(cs, model)(n, p)
            @test all(isfinite, lna)
            @test length(lna) == 3
        end
    end

end

@testsection "a declared capacity is compared with the state that uses it" begin

    # The audit's reproduction, kept as the shape of the test: a family
    # declaring one capacity and a state initialized with another gave an
    # equilibrium holding the state's, with `optimality_certificate` reporting
    # `optimal = true`. The certificate was not wrong — it checks the budget it
    # is given. Nothing compared that budget with the declaration, and changing
    # the declared capacity alone changed no number in the answer.

    declared = 1.0e-3                      # `_amphoteric_system`'s default
    cs, st, family = _amphoteric_system()
    nm = symbol.(cs.species)
    idx(s) = findfirst(==(s), nm)

    function state_with(n_free)
        n = Any[fill(1.0e-12u"mol", length(cs.species))...]
        n[idx("H2O@")] = moles_of_water() * u"mol"
        n[idx("XsOH")] = n_free * u"mol"
        return ChemicalState(cs, n)
    end

    @testset "agreement reads zero and raises nothing" begin
        @test declared_site_moles(st, family) ≈ declared
        # The two tiny complexes are in the state at the 1e-12 floor, so the
        # present total is the free sites plus that — which is why this is a
        # tolerance and not an equality.
        @test present_site_moles(st, family) ≈ declared rtol = 1.0e-8
        @test abs(site_budget_residual(st)["Xs"]) < 1.0e-6 * declared
        @test check_site_budget(st) === nothing
    end

    @testset "disagreement is named, with both numbers" begin
        bad = state_with(1.0e-1)
        @test site_budget_residual(bad)["Xs"] ≈ 1.0e-1 - declared rtol = 1.0e-6
        e = try
            check_site_budget(bad)
            nothing
        catch err
            err
        end
        @test e isa InconsistentSiteBudget
        # The message carries BOTH numbers, or it says only that something is
        # wrong — which the caller already knew.
        msg = sprint(showerror, e)
        @test occursin("Xs", msg)
        @test occursin("host_consistent_state", msg)
    end

    @testset "the tolerance is relative, because a site budget has no scale" begin
        # 1e-6 mol on an oxide and 1e-1 mol on a clay: an absolute threshold
        # would be meaningless on one of the two.
        @test check_site_budget(state_with(declared * (1 + 1.0e-9))) === nothing
        @test_throws InconsistentSiteBudget check_site_budget(
            state_with(declared * (1 + 1.0e-3)),
        )
    end

    @testset "the repair derives the free site, and refuses the impossible" begin
        fixed = host_consistent_state(state_with(1.0e-1))
        @test abs(site_budget_residual(fixed)["Xs"]) < 1.0e-6 * declared
        @test check_site_budget(fixed) === nothing
        # It moved the FREE site and nothing else: an occupied site holds a
        # sorbate whose elements the rest of the system accounts for.
        @test ustrip(us"mol", fixed.n[idx("XsOH")]) ≈ declared rtol = 1.0e-8
        @test fixed.n[idx("H2O@")] == state_with(1.0e-1).n[idx("H2O@")]

        # Complexes already over the capacity is a declaration to correct, not
        # an initialization to repair.
        n = Any[fill(1.0e-12u"mol", length(cs.species))...]
        n[idx("H2O@")] = moles_of_water() * u"mol"
        n[idx("XsOH2+")] = 10 * declared * u"mol"
        @test_throws ArgumentError host_consistent_state(ChemicalState(cs, n))
    end

    @testset "a capacity measured on a host is evaluated on that host" begin
        # The other half of the contract: given a host, the density is read on
        # its amount. This is the path a coupled support takes, and until now
        # only its refusal was exercised.
        h2o, hp, ca2 = reference_species(("H2O@", "H+", "Ca+2"))
        host = reference_species("Portlandite"; db = :cemdata18)
        free3 = Species("XsOH"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        free3[:ΔₐG⁰] = _g0(0.0)
        fam3 = SiteFamily(
            "Xs", free3, AbstractSpecies[];
            capacity = MassSiteDensity(2.0),
            support = SurfaceSupport(
                "sorbent", "Portlandite", FixedSurfaceArea(1.0);
                coupling = SITES_FOLLOW_HOST,
            ),
        )
        cs3 = ChemicalSystem(
            [h2o, hp, ca2, host, free3], [h2o, hp, ca2, free3]; site_families = [fam3],
        )
        M = ustrip(us"kg/mol", host[:M])
        n_host = 0.1
        st3 = ChemicalState(
            cs3,
            [moles_of_water() * u"mol", 1.0e-12u"mol", 1.0e-12u"mol", n_host * u"mol", 1.0e-12u"mol"],
        )
        # q · M · n_host, checkable by hand.
        @test declared_site_moles(st3, fam3) ≈ 2.0 * M * n_host
        # And it MOVES with the host, which is the whole point of the coupling.
        st4 = ChemicalState(
            cs3,
            [moles_of_water() * u"mol", 1.0e-12u"mol", 1.0e-12u"mol", 2n_host * u"mol", 1.0e-12u"mol"],
        )
        @test declared_site_moles(st4, fam3) ≈ 2 * declared_site_moles(st3, fam3)
    end

    @testset "a capacity that needs a host, without one, is refused" begin
        # An area or mass density cannot be evaluated without the solid that
        # carries the sites. Evaluating it at zero would report a capacity of
        # zero, which is a different model rather than a missing input.
        free2 = Species("XwOH"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        free2[:ΔₐG⁰] = _g0(0.0)
        fam2 = SiteFamily(
            "Xw", free2, AbstractSpecies[];
            capacity = AreaSiteDensity(1.0e-5),
            support = SurfaceSupport("oxide", nothing, FixedSurfaceArea(1.0)),
        )
        h2o, hp = reference_species(("H2O@", "H+"))
        cs2 = ChemicalSystem([h2o, hp, free2], [h2o, hp, free2]; site_families = [fam2])
        st2 = ChemicalState(cs2, [moles_of_water() * u"mol", 1.0e-12u"mol", 1.0e-3u"mol"])
        @test_throws ArgumentError declared_site_moles(st2, fam2)
    end
end

@testsection "a site budget that follows its phase, against PHREEQC" begin

    # PHREEQC has coupled a SURFACE to an EQUILIBRIUM_PHASES mineral since v2:
    #
    #     Hfo_sOH   Fe(OH)3(a)   equilibrium_phase   0.005   53300
    #
    # which is `SITES_FOLLOW_HOST` in another code's words. The fixture captures
    # its COUPLING LAW over a titration that dissolves the sorbent step by step;
    # `not_a_reproduction` states what is deliberately not shared between the
    # two, and the test asserts on that field rather than trusting the prose
    # around it.
    F = reference_oracle("phreeqc_evolving_surface")

    @testset "the oracle really is coupled" begin
        # A fixture of a feature that was not switched on would compare nothing.
        # Every partially dissolved state must carry exactly the declared moles
        # of sites per mole of phase.
        worst = 0.0
        n_partial = 0
        for pt in F.points
            pt.fe_phase > 0 || continue
            n_partial += 1
            for (tot, coef) in (
                    (pt.strong_total, F.sites_strong_per_mol),
                    (pt.weak_total, F.sites_weak_per_mol),
                )
                worst = max(worst, abs(tot / pt.fe_phase / coef - 1))
            end
        end
        @test n_partial >= 4                 # a law, not a single point
        @info "PHREEQC coupling law" worst n_partial
        # Measured at 2.0e-10; the threshold keeps three decades of margin. It
        # was 7e-6 until the molalities were multiplied by the water mass, which
        # is not 1 kg once acid has been added — a units error that reads as a
        # coupling error.
        @test worst < 1.0e-7
    end

    @testset "the sorbent goes with the phase, all the way to nothing" begin
        first_pt, last_pt = F.points[1], F.points[end]
        @test first_pt.fe_phase > 0.9e-3                 # intact at the start
        @test last_pt.fe_phase == 0                      # gone at the end
        # And the sites go with it: PHREEQC leaves them at the floor, not at a
        # remembered value.
        @test last_pt.strong_total < 1.0e-20
        @test last_pt.weak_total < 1.0e-20
        # In between, both fall monotonically with the phase — while there IS a
        # phase. Past exhaustion the totals sit at a 1e-26 floor where their
        # order carries no information, and requiring monotonicity there would
        # be asserting on noise.
        live = [pt for pt in F.points if pt.fe_phase > 0]
        @test issorted([pt.fe_phase for pt in live]; rev = true)
        @test issorted([pt.strong_total for pt in live]; rev = true)
        @test all(pt -> pt.strong_total < 1.0e-20, setdiff(F.points, live))
    end

    @testset "this package states the same law" begin
        # PHREEQC declares moles of sites per mole of phase directly. Here that
        # is `ν`, and a mass density reaches it as `q · M`, so the two
        # declarations meet on a number rather than on an intention.
        host = reference_species("Portlandite"; db = :cemdata18)
        M = ustrip(us"kg/mol", host[:M])
        q = F.sites_strong_per_mol / M
        free2 = Species("XwOH"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        free2[:ΔₐG⁰] = _g0(0.0)
        fam = SiteFamily(
            "Xw", free2, AbstractSpecies[];
            capacity = MassSiteDensity(q),
            support = SurfaceSupport(
                "sorbent", "Portlandite", FixedSurfaceArea(1.0);
                coupling = SITES_FOLLOW_HOST,
            ),
        )
        @test ChemistryLab.sites_per_host(fam, M) ≈ F.sites_strong_per_mol rtol = 1.0e-12

        # And the row the package builds is that law: `Σ d n − ν n_host = 0`.
        h2o, hp, ca2 = reference_species(("H2O@", "H+", "Ca+2"))
        bare = Species("Xw+"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
        cs = ChemicalSystem(
            [h2o, hp, ca2, host, free2], [h2o, hp, ca2, bare]; site_families = [fam],
        )
        rows, _ = site_coupling_rows(cs)
        i = Dict(s => k for (k, s) in enumerate(symbol.(cs.species)))
        @test rows[1, i["XwOH"]] == 1.0
        @test rows[1, i["Portlandite"]] ≈ -F.sites_strong_per_mol rtol = 1.0e-12
    end

    @testset "what is not compared is written down" begin
        @test occursin("not a shared surface model", F.not_a_reproduction)
        @test occursin("no back-reaction", F.not_a_reproduction)
        # Provenance read at run time, never assumed — including the engine
        # version, which the older surface generator does not record.
        @test F.phreeqc_engine == "3.7.3-15968"
        @test F.database == "phreeqc.dat"
        @test F.electrostatics == "-no_edl"
    end
end

@testsection "the standard state of a free site is a gauge only while nothing follows" begin

    # THE TEST THAT MEASURES THE BOUNDARY BETWEEN A GAUGE AND A PARAMETER, and
    # the reason it exists: with a fixed budget, `ΔₐG⁰` of the free site cancels
    # out of every surface reaction, both sides carrying a site, so setting it
    # to zero is free. With a budget that FOLLOWS ITS HOST it does not cancel:
    # the host carries `−ν` of the site component, so the site potential enters
    # the host's own chemical potential and moves its solubility.
    #
    # Shifting the WHOLE family by the same Δ leaves every internal log K
    # untouched, which is what isolates the gauge from the chemistry.
    #
    # Measured on amorphous ferric hydroxide at Dzombak and Morel's weak-site
    # density, `ν = 0.2`, over 40 kJ/mol of shift: the host's saturation index
    # moves by `−ν Δ / (RT ln 10)` to five decimals, and the uncoupled system
    # does not move at all. At `ν = 0.2` that is 0.35 log units per 10 kJ/mol —
    # which is why a coupled family cannot be given an arbitrary reference.

    psi = build_species(datapath("psinagra-12-07-thermofun.json"); verbose = false)
    bn = Dict(symbol(s) => s for s in psi)
    M = ustrip(us"kg/mol", bn["Fe(OH)3(am)"][:M])
    ν = 0.2
    aq = speciation(
        psi, ["Fe(OH)3(am)"]; aggregate_state = [AS_AQUEOUS],
        exclude_species = split("H2@ O2@ Fe+2 FeOH+ FeO+"),
    )
    surf(sym, g) = (
        s = Species(sym; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX);
        s[:ΔₐG⁰] = _g0(g); s
    )

    function run(Δ; coupled)
        mem = [
            surf("XwOH", Δ), surf("XwOH2+", Δ - RT25 * log(10.0^7.29)),
            surf("XwO-", Δ - RT25 * log(10.0^-8.93)),
        ]
        support = SurfaceSupport(
            "hydrous ferric oxide", "Fe(OH)3(am)", FixedSurfaceArea(1.0);
            coupling = coupled ? SITES_FOLLOW_HOST : SITES_FIXED,
        )
        family = SiteFamily(
            "Xw", mem[1], mem[2:3];
            capacity = coupled ? MassSiteDensity(ν / M) : TotalSiteAmount(ν * 1.0e-3),
            support,
        )
        # Coupled, the component is the BARE site; uncoupled, the free site.
        comp = coupled ?
            Species("Xw+"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX) : mem[1]
        cs = ChemicalSystem(
            AbstractSpecies[vcat(aq, mem)...],
            AbstractSpecies[bn["H2O@"], bn["H+"], bn["Fe+3"], comp];
            site_families = [family],
        )
        st = ChemicalState(cs)
        set_quantity!(st, "H2O@", moles_of_water() * u"mol")
        set_quantity!(st, "Fe(OH)3(am)", 1.0e-3u"mol")
        if coupled
            st = host_consistent_state(st)
        else
            set_quantity!(st, "XwOH", (ν * 1.0e-3)u"mol")
        end
        b = conservation_matrix(cs) * Float64[ustrip(us"mol", x) for x in st.n]
        model = DaviesActivityModel()
        eq, _ = equilibrate_certified(st; model, b = b)
        i = findfirst(==("Fe(OH)3(am)"), symbol.(cs.species))
        return (
            host = ustrip(us"mol", eq.n[i]),
            si = saturation_indices(eq, model)["Fe(OH)3(am)"],
        )
    end

    @testset "a fixed budget: invariant to the solver's own noise" begin
        # NOT asserted bit for bit, and the reason is worth stating: shifting
        # every member's reference energy changes the numbers the dual Newton
        # iterates on, so it takes a different path to the same answer. What is
        # invariant is the answer. The scale below is the solver's own
        # reproducibility, and the contrast at the end is what makes it mean
        # something — the coupled system moves by four orders of magnitude more
        # on the same shift.
        ref = run(0.0; coupled = false)
        worst = 0.0
        for Δ in (-5.0e3, -2.0e4, 1.0e4)
            r = run(Δ; coupled = false)
            @test r.host ≈ ref.host rtol = 1.0e-6
            @test r.si ≈ ref.si atol = 1.0e-5
            worst = max(worst, abs(r.si - ref.si))
        end
        @info "gauge invariance, fixed budget" worst
        # The comparison that makes the two testsets one statement.
        coupled_shift = abs(run(-2.0e4; coupled = true).si - run(0.0; coupled = true).si)
        @test coupled_shift > 1.0e3 * max(worst, 1.0e-9)
    end

    @testset "a budget that follows its host: the shift is −ν Δ / (RT ln 10)" begin
        ref = run(0.0; coupled = true)
        for Δ in (-5.0e3, -1.0e4, -2.0e4, -3.0e4, -4.0e4)
            r = run(Δ; coupled = true)
            @test r.si - ref.si ≈ -ν * Δ / (RT25 * log(10)) atol = 1.0e-4
        end
        # And the magnitude is the point: at this site density the reference
        # energy is worth 0.35 log units of solubility per 10 kJ/mol, so it is
        # a parameter of the calculation and not a convention inside it.
        @test abs(run(-1.0e4; coupled = true).si - ref.si) > 0.3
    end
end
