# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2025-2026 Jean-François Barthélémy and Anthony Soive (Cerema, UMR MCD)

using ChemistryLab
using DynamicQuantities
using ForwardDiff
using SciMLBase
using Test

const RT25 = 8.31446261815324 * 298.15

# An amphoteric surface, which is the physics of every oxide and also the one
# shape in which competition has a **closed form under a single constraint**:
# both occupied states are driven by the proton activity, so
#
#     β₁ = K₁ a_H        (XsOH + H⁺ ⇌ XsOH₂⁺)
#     β₂ = K₂ / a_H      (XsOH ⇌ XsO⁻ + H⁺)
#
# and ideal site mixing gives the competitive Langmuir form with its shared
# denominator, without an isotherm being written anywhere:
#
#     n_j / N = β_j / (1 + β₁ + β₂)
#
# The standard energies below are chosen to *be* those constants, so the oracle
# is derived rather than fitted.
_g0(value) = SymbolicFunc(value * u"J/mol")

function _amphoteric_system(; logK1 = 7.0, logK2 = -9.0, n_sites = 1.0e-3)
    h2o = Species("H2O@"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLVENT)
    h2o[:ΔₐG⁰] = _g0(-237181.0)
    h2o[:M] = 0.018015u"kg/mol"
    h2o[:V⁰] = SymbolicFunc(1.807e-5u"m^3/mol")

    hp = Species("H+"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
    hp[:ΔₐG⁰] = _g0(0.0)
    oh = Species("OH-"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
    oh[:ΔₐG⁰] = _g0(-157297.0)

    free = Species("XsOH"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    free[:ΔₐG⁰] = _g0(0.0)
    prot = Species("XsOH2+"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    prot[:ΔₐG⁰] = _g0(-RT25 * log(10.0^logK1))
    depr = Species("XsO-"; aggregate_state = AS_SURFACE, class = SC_SURFCOMPLEX)
    depr[:ΔₐG⁰] = _g0(-RT25 * log(10.0^logK2))

    support = SurfaceSupport("oxide", nothing, FixedSurfaceArea(1.0))
    family = SiteFamily(
        "Xs", free, [prot, depr];
        capacity = TotalSiteAmount(n_sites), support,
    )
    species = [h2o, hp, oh, free, prot, depr]
    cs = ChemicalSystem(species, [h2o, hp, free]; site_families = [family])

    n = Any[fill(1.0e-12u"mol", length(cs.species))...]
    n[1] = 55.5u"mol"
    n[4] = n_sites * u"mol"          # all sites free to start with
    return cs, ChemicalState(cs, n), family
end

# The closed form the plan derives: a shared denominator is the signature of a
# finite capacity, and it is what makes this a test of competition rather than
# of two isotherms side by side.
_langmuir(β) = (1 ./ (1 + sum(β)), β ./ (1 + sum(β)))

# ── The matched PHREEQC case ──────────────────────────────────────────────────
#
# Generated by `test/reference/phreeqc_hfo_surface.py --case protolysis`. Paste
# the block it prints, header included: the version of every piece and the md5
# of the database are what make this reproducible rather than merely recorded.
#
# What matches, and what deliberately does not. The two log K are PHREEQC's own,
# read from its database by the generator rather than typed here. The comparison
# is made at **matched proton activity**, which `Fix_H+` on one side and
# `FixedpH` on the other both prescribe exactly — so the aqueous activity model,
# which differs between the two codes, does not enter. With no metal in the
# system there is nothing else it could enter through. That is the narrowest
# honest comparison, and narrowing it is the point: it isolates the surface
# chemistry, which is what this release adds.
# generated by test/reference/phreeqc_hfo_surface.py
# python       3.12.14
# phreeqpython 1.6.2
# database     phreeqc.dat  md5 fca384eb269fda632fcefa6f74c8f90e
# model        no_edl, weak sites only, no metal
# sites        0.0002 mol
# log K        protonation 7.29, deprotonation -8.93
const PHREEQC_PROTOLYSIS = (
    logK_protonation = 7.29,
    logK_deprotonation = -8.93,
    n_sites = 0.0002,
    points = [
        (pH = 4.0, la_H = -4.0, free = 0.0005125984889321876, protonated = 0.9994873954885607, deprotonated = 6.022507113121253e-9),
        (pH = 5.0, la_H = -5.0, free = 0.005102442309144079, protonated = 0.9948969582061565, deprotonated = 5.994846993233386e-7),
        (pH = 6.0, la_H = -6.0, free = 0.0487813899152302, protonated = 0.9511612969490318, deprotonated = 5.731313573795587e-5),
        (pH = 7.0, la_H = -7.0, free = 0.33765605393582376, protonated = 0.658376833342379, deprotonated = 0.003967112721797296),
        (pH = 8.0, la_H = -8.0, free = 0.7619197300893887, protonated = 0.14856250711639016, deprotonated = 0.08951776279422106),
        (pH = 9.0, la_H = -9.0, free = 0.455706262485419, protonated = 0.00888556394983117, deprotonated = 0.5354081735647499),
    ],
)

@testsection "Surface complexation" begin

    @testset "a site activity is a site fraction, in every activity model" begin
        cs, st, _ = _amphoteric_system()
        n = Float64[ustrip(us"mol", x) for x in st.n]
        # A composition with all three states populated, so the fractions are
        # not degenerate.
        n[4], n[5], n[6] = 5.0e-4, 3.0e-4, 2.0e-4
        p = ChemistryLab._build_params(st)
        N = n[4] + n[5] + n[6]

        for model in (
                DiluteSolutionModel(), HKFActivityModel(), DaviesActivityModel(),
            )
            lna = activity_model(cs, model)(n, p)
            for i in 4:6
                @test lna[i] ≈ log(n[i] / N) rtol = 1.0e-9
            end
        end
    end

    @testset "the mixing differentiates" begin
        cs, st, _ = _amphoteric_system()
        n0 = Float64[ustrip(us"mol", x) for x in st.n]
        n0[4], n0[5], n0[6] = 5.0e-4, 3.0e-4, 2.0e-4
        p = ChemistryLab._build_params(st)
        lna = activity_model(cs, DiluteSolutionModel())

        J = ForwardDiff.jacobian(nn -> lna(nn, p), n0)
        @test all(isfinite, J[4:6, 4:6])
        # d(ln x_i)/dn_i = 1/n_i − 1/N, exactly, and the cross term is −1/N:
        # the free site is coupled to every occupied state, which is what makes
        # saturation a shared effect rather than a per-species one.
        N = n0[4] + n0[5] + n0[6]
        @test J[4, 4] ≈ 1 / n0[4] - 1 / N rtol = 1.0e-6
        @test J[4, 5] ≈ -1 / N rtol = 1.0e-6
        @test J[5, 4] ≈ -1 / N rtol = 1.0e-6
    end

    @testset "competitive Langmuir falls out of the site balance" begin
        logK1, logK2, n_sites = 7.0, -9.0, 1.0e-3
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        A = Float64.(cs.SM.A)
        b = A * Float64[ustrip(us"mol", x) for x in st.n]

        for target_pH in (4.0, 6.0, 8.0, 10.0)
            q = Base.RefValue{Any}(nothing)
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(target_pH), parameters = q,
            )
            n = Float64[ustrip(us"mol", x) for x in eq.n]

            # The prescribed quantity is the activity, so read it back rather
            # than assume the target was reached.
            p = ChemistryLab._build_params(eq)
            a_H = exp(des.lna(n, p)[2])

            β = [10.0^logK1 * a_H, 10.0^logK2 / a_H]
            x_free, x_occ = _langmuir(β)

            N = n[4] + n[5] + n[6]
            @test N ≈ n_sites rtol = 1.0e-8            # sites are conserved
            @test n[4] / N ≈ x_free rtol = 1.0e-6
            @test n[5] / N ≈ x_occ[1] rtol = 1.0e-6
            @test n[6] / N ≈ x_occ[2] rtol = 1.0e-6
        end
    end

    @testset "saturation, and the surface activity coefficient it makes unnecessary" begin
        # A drive strong enough to fill the sites: at pH 2 with logK₁ = 7 the
        # protonation drive is β₁ = 1e5, so the free sites are nearly gone.
        logK1, logK2, n_sites = 7.0, -9.0, 1.0e-3
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]
        q = Base.RefValue{Any}(nothing)
        eq = SciMLBase.solve(des, st; b = b, constraint = FixedpH(2.0), parameters = q)
        n = Float64[ustrip(us"mol", x) for x in eq.n]

        N = n[4] + n[5] + n[6]
        θ = (n[5] + n[6]) / N                      # occupied fraction
        @test θ > 0.999
        @test n[4] / N < 1.0e-3                    # free sites nearly exhausted

        # Kulik's 2006 surface activity coefficient, γ_L = 1/(1 − θ), is what an
        # *eliminated* free site needs in order to reproduce what an explicit one
        # already produces. Here the identity is a check, not a correction:
        # applying γ_L on top of this mixing would count saturation twice.
        @test 1 / (1 - θ) ≈ N / n[4] rtol = 1.0e-8
    end

    @testset "matched against PHREEQC, at matched proton activity" begin
        f = PHREEQC_PROTOLYSIS
        cs, st, _ = _amphoteric_system(;
            logK1 = f.logK_protonation, logK2 = f.logK_deprotonation,
            n_sites = f.n_sites,
        )
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        b = Float64.(cs.SM.A) * Float64[ustrip(us"mol", x) for x in st.n]

        worst = 0.0
        for pt in f.points
            q = Base.RefValue{Any}(nothing)
            eq = SciMLBase.solve(
                des, st; b = b, constraint = FixedpH(pt.pH), parameters = q,
            )
            n = Float64[ustrip(us"mol", x) for x in eq.n]
            p = ChemistryLab._build_params(eq)

            # PHREEQC prescribed the activity, so check ours is the same one
            # before comparing anything that depends on it.
            la_H = des.lna(n, p)[2] / log(10)
            @test la_H ≈ pt.la_H atol = 1.0e-6

            N = n[4] + n[5] + n[6]
            for (got, want) in (
                    (n[4] / N, pt.free), (n[5] / N, pt.protonated),
                    (n[6] / N, pt.deprotonated),
                )
                @test got ≈ want rtol = 1.0e-5
                worst = max(worst, abs(got / want - 1))
            end
        end
        # Reported rather than only asserted: a margin that shrinks is visible
        # before it becomes a failure. Measured at 1.7e-8 over the six points.
        @info "PHREEQC protolysis: worst relative deviation" worst
        @test worst < 1.0e-5
    end

    @testset "residuals, one scale per conserved quantity" begin
        # A single absolute tolerance across water, a trace species and a site
        # budget compares numbers ten orders of magnitude apart. Each conserved
        # quantity is scaled by its own total instead.
        #
        # This solve is **closed** — no constraint — precisely so that charge can
        # be checked. `FixedpH` holds the proton activity by titrating, so under
        # it the proton row and the charge balance are the constraint's to move,
        # not the solver's to conserve, and checking them there would be
        # checking the wrong thing.
        logK1, logK2, n_sites = 7.29, -8.93, 2.0e-4
        cs, st, _ = _amphoteric_system(; logK1, logK2, n_sites)
        des = DualEquilibriumSolver(cs, DiluteSolutionModel())
        A = Float64.(cs.SM.A)
        n0 = Float64[ustrip(us"mol", x) for x in st.n]
        b = A * n0
        eq = SciMLBase.solve(des, st; b = b)
        n = Float64[ustrip(us"mol", x) for x in eq.n]
        r = A * n .- b

        # The scale of a conservation row is how much matter it *moves*, not its
        # net budget. A perfectly balanced row has a budget of exactly zero —
        # here the proton row does, the initial traces canceling — and dividing
        # by that compares a residual with nothing at all.
        turnover(c) = sum(abs(A[c, i]) * n[i] for i in eachindex(n))
        for c in eachindex(b)
            scale = max(abs(b[c]), turnover(c), eps())
            @test abs(r[c]) / scale < 1.0e-9
        end

        # The site row on its own, against the site budget rather than against
        # the water: it is the row this release adds, and the one whose failure
        # would be silent.
        i_site = findfirst(p -> symbol(p) == "XsOH", cs.SM.primaries)
        @test abs(r[i_site]) / b[i_site] < 1.0e-10

        # And the budget is what was put in, floors included — `b` rather than
        # the nominal capacity, because the two differ by the trace amounts the
        # initial state carries and the solver conserves the first, exactly.
        @test (n[4] + n[5] + n[6]) ≈ b[i_site] rtol = 1.0e-10

        # Charge. The surface states are charged, the initial composition is
        # neutral, and a closed system must stay so.
        z = Float64[charge(sp) for sp in cs.species]
        scale = max(sum(abs, z .* n), eps())
        @test abs(sum(z .* n0)) / scale < 1.0e-8      # it started neutral
        @test abs(sum(z .* n)) / scale < 1.0e-8       # and it stayed neutral
    end

    @testset "a system without a surface is unchanged" begin
        # The kernel must be a no-op when nothing declares a site, in all four
        # activity models — the guard against a regression reaching every solve.
        h2o = Species("H2O@"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLVENT)
        h2o[:ΔₐG⁰] = _g0(-237181.0)
        h2o[:M] = 0.018015u"kg/mol"
        hp = Species("H+"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
        hp[:ΔₐG⁰] = _g0(0.0)
        oh = Species("OH-"; aggregate_state = AS_AQUEOUS, class = SC_AQSOLUTE)
        oh[:ΔₐG⁰] = _g0(-157297.0)
        cs = ChemicalSystem([h2o, hp, oh], [h2o, hp])
        st = ChemicalState(cs, Any[55.5u"mol", 1.0e-7u"mol", 1.0e-7u"mol"])
        n = Float64[ustrip(us"mol", x) for x in st.n]
        p = ChemistryLab._build_params(st)

        @test isempty(cs.site_groups)
        for model in (DiluteSolutionModel(), HKFActivityModel(), DaviesActivityModel())
            lna = activity_model(cs, model)(n, p)
            @test all(isfinite, lna)
            @test length(lna) == 3
        end
    end

end
