# The bundled zeolite extension of CEMDATA18.
#
# `data/cemdata18-zeolites.json` is GENERATED by `data/zeolites/regenerate.jl`
# and vendored. A generated file that ships is a promise about its content, so
# the promises are asserted here rather than in the generator alone: the
# generator can only refuse at the moment it runs, and nothing otherwise stops a
# hand edit, a bad merge or a partial write from reaching a release.
#
# The central one is the `log Ksp` round trip. Both source papers publish
# `log Ksp` AND `ΔfG⁰` for each phase, referred to the CEMDATA18 primary
# species; recomputing one from the other through CEMDATA18's own aqueous Gibbs
# energies closes the loop, and it can only close if the two datasets share a
# reference state and the transcription is exact.

using JSON

@testsection "Zeolite extension of CEMDATA18" begin
    base = JSON.parsefile(datapath("cemdata18-thermofun.json"); dicttype = Dict{String, Any})
    ext = JSON.parsefile(datapath("cemdata18-zeolites.json"); dicttype = Dict{String, Any})

    by_symbol(db) = Dict(String(s["symbol"]) => s for s in db["substances"])
    B, E = by_symbol(base), by_symbol(ext)

    @testset "a strict superset, with nothing overwritten" begin
        @test issubset(keys(B), keys(E))
        added = setdiff(keys(E), keys(B))
        @test length(added) == 28

        # Value identity on the base entries, not merely presence. An offset of
        # a few kJ/mol on one aqueous species would move every dissolution
        # equilibrium by an order of magnitude and no solver would complain.
        gibbs(s) = get(get(s, "sm_gibbs_energy", Dict()), "values", nothing)
        @test all(gibbs(E[k]) == gibbs(B[k]) for k in keys(B))

        # The papers revise ΔfG⁰ for phases CEMDATA18 already carries, so the new
        # entries must take distinct symbols and leave the old ones in place.
        @test haskey(E, "natrolite") && haskey(E, "NAT-Na")
        @test gibbs(E["natrolite"]) == gibbs(B["natrolite"])
    end

    @testset "every added phase carries its provenance" begin
        added = sort(collect(setdiff(keys(E), keys(B))))
        for k in added
            s = E[k]
            @test haskey(s, "zeolite_provenance")
            p = s["zeolite_provenance"]
            @test startswith(String(p["doi"]), "10.1016/j.cemconres.20")
            @test String(p["S_Cp_origin"]) in ("measured", "additivity", "literature")
            @test !isempty(get(s, "datasources", []))
        end
    end

    @testset "log Ksp closes against the CEMDATA18 aqueous energies" begin
        # The check that makes the merge defensible, re-run here on the shipped
        # file. Both source papers publish `log Ksp` AND `ΔfG⁰` for each phase,
        # referred to the CEMDATA18 primary species; recomputing one from the
        # other through CEMDATA18's own aqueous Gibbs energies closes the loop,
        # and it can only close if the two datasets share a reference state and
        # the transcription is exact.
        #
        # The dissolution products are READ FROM THE FILE, not inferred from the
        # formula. Inferring them means assuming one alkali per aluminum, which
        # is wrong for the sodalites and the cancrinite: `SOD-Cl-Na` is
        # Na8(Al6Si6)O24Cl2, eight sodiums for six aluminums, and the balance is
        # made up by chloride. A test that guessed the reaction would be checking
        # a different reaction from the one the generator checked.
        R = 8.31446261815324          # J/(mol·K), CODATA
        RTln10 = R * 298.15 * log(10)
        G = Dict{String, Float64}()
        for s in base["substances"]
            v = get(get(s, "sm_gibbs_energy", Dict()), "values", nothing)
            v === nothing || isempty(v) || (G[String(s["symbol"])] = Float64(v[1]))
        end

        worst = 0.0
        added = sort(collect(setdiff(keys(E), keys(B))))
        for k in added
            s = E[k]
            products = s["zeolite_provenance"]["dissolution_products"]
            @test !isempty(products)
            # Every product must be a CEMDATA18 aqueous species, or the reaction
            # is not written over the primaries the papers refer their constants
            # to and the round trip below would be meaningless.
            @test all(haskey(G, String(sp)) for sp in keys(products))

            ΔrG = sum(Float64(ν) * G[String(sp)] for (sp, ν) in products) -
                Float64(s["sm_gibbs_energy"]["values"][1])
            lk = -ΔrG / RTln10
            published = Float64(s["zeolite_provenance"]["log_Ksp_298K"])
            worst = max(worst, abs(lk - published))
            @test isapprox(lk, published; atol = 0.05)
        end
        @test worst < 0.05
    end
end
