# The bundled zeolite extension of CEMDATA18.
#
# `data/cemdata18-zeolites.json` is GENERATED by `data/zeolites/regenerate.jl`
# and vendored. A generated file that ships is a promise about its content, so
# the promises are asserted here rather than in the generator alone: the
# generator can only refuse at the moment it runs, and nothing otherwise stops a
# hand edit, a bad merge or a partial write from reaching a release.
#
# The central one is the `log Ksp` round trip. Both source papers publish
# `log Ksp` AND `ΔfG⁰` for each phase, referred to the CEMDATA18 primary
# species; recomputing one from the other through CEMDATA18's own aqueous Gibbs
# energies closes the loop, and it can only close if the two datasets share a
# reference state and the transcription is exact.

using JSON

@testsection "Zeolite extension of CEMDATA18" begin
    base = JSON.parsefile(datapath("cemdata18-thermofun.json"); dicttype = Dict{String, Any})
    ext = JSON.parsefile(datapath("cemdata18-zeolites.json"); dicttype = Dict{String, Any})

    by_symbol(db) = Dict(String(s["symbol"]) => s for s in db["substances"])
    B, E = by_symbol(base), by_symbol(ext)

    @testset "a strict superset, with nothing overwritten" begin
        @test issubset(keys(B), keys(E))
        added = setdiff(keys(E), keys(B))
        @test length(added) == 28

        # Value identity on the base entries, not merely presence. An offset of
        # a few kJ/mol on one aqueous species would move every dissolution
        # equilibrium by an order of magnitude and no solver would complain.
        gibbs(s) = get(get(s, "sm_gibbs_energy", Dict()), "values", nothing)
        @test all(gibbs(E[k]) == gibbs(B[k]) for k in keys(B))

        # The papers revise ΔfG⁰ for phases CEMDATA18 already carries, so the new
        # entries must take distinct symbols and leave the old ones in place.
        @test haskey(E, "natrolite") && haskey(E, "NAT-Na")
        @test gibbs(E["natrolite"]) == gibbs(B["natrolite"])
    end

    @testset "every added phase carries its provenance" begin
        added = sort(collect(setdiff(keys(E), keys(B))))
        for k in added
            s = E[k]
            @test haskey(s, "zeolite_provenance")
            p = s["zeolite_provenance"]
            @test startswith(String(p["doi"]), "10.1016/j.cemconres.20")
            @test String(p["S_Cp_origin"]) in ("measured", "additivity", "literature")
            @test !isempty(get(s, "datasources", []))
        end
    end

    @testset "log Ksp closes against the CEMDATA18 aqueous energies" begin
        R = 8.31446261815324          # J/(mol·K), CODATA
        RTln10 = R * 298.15 * log(10)
        G = Dict{String, Float64}()
        for s in base["substances"]
            v = get(get(s, "sm_gibbs_energy", Dict()), "values", nothing)
            v === nothing || isempty(v) || (G[String(s["symbol"])] = Float64(v[1]))
        end

        # The dissolution products are not stored in the JSON -- they belong to
        # the transcription -- so they are read back from the formula, over the
        # primary species the papers refer their constants to. A zeolite is
        # M_x(Al_x Si_y)O_z (H2O)_w and dissolves congruently to x M+, x AlO2-,
        # y SiO2@ and w H2O@.
        worst = 0.0
        added = sort(collect(setdiff(keys(E), keys(B))))
        for k in added
            s = E[k]
            atoms = Dict(
                Symbol(a) => Float64(n)
                    for (a, n) in ChemistryLab.parse_formula(String(s["formula"]))
            )
            al = get(atoms, :Al, 0.0)
            si = get(atoms, :Si, 0.0)
            na = get(atoms, :Na, 0.0)
            ka = get(atoms, :K, 0.0)
            # oxygen beyond the framework and the aluminate is structural water
            h2o = get(atoms, :H, 0.0) / 2

            @test al > 0 && si > 0
            @test isapprox(na + ka, al; atol = 1.0e-9)   # charge balance of the framework

            ΔrG = na * G["Na+"] + ka * G["K+"] + al * G["AlO2-"] +
                si * G["SiO2@"] + h2o * G["H2O@"] -
                Float64(s["sm_gibbs_energy"]["values"][1])
            lk = -ΔrG / RTln10
            published = Float64(s["zeolite_provenance"]["log_Ksp_298K"])
            worst = max(worst, abs(lk - published))
            @test isapprox(lk, published; atol = 0.05)
        end
        @test worst < 0.05
    end
end
