# GEMS3K on this machine: what it can run, and the one case it cannot.
#
# `xgems.ChemicalEngine` runs a GEMS3K **system export** -- a `*-dat.lst` file and
# the `*.dat` files beside it. The xGEMS repository publishes several exports,
# and `xgems_cement.py` runs its CEMDATA18 cement: that is how GEMS3K serves as an
# oracle here, without GEM-Selektor.
#
# The ClaySor 2023 deposit (doi:10.5281/zenodo.15095062, CC-BY-4.0) ships a
# GEM-Selektor *database* instead -- `dcomp`, `reacdc`, `icomp`, `phase`, `compos`
# and `sdref` `.pdb` files in GEMBASE format, whose readable strings show the ion
# exchangers `MontX` and `IlliteX` and the amphoteric edge layers -- and no
# export, so the comparison of the same ClaySor model in PHREEQC and in GEMS is
# not available: a missing input, not a missing capability, recorded rather than
# worked around. The PHREEQC half of the deposit is directly usable
# (`phreeqc_claysor.py`).

import sys


def main() -> int:
    try:
        import xgems
    except Exception as exc:  # pragma: no cover - the whole point is to report
        print(f"xgems does not import: {exc}")
        return 1

    print("# generated by test/reference/gems_bench.py")
    print(f"# python  {sys.version.split()[0]}")
    try:
        from importlib.metadata import version

        print(f"# xgems   {version('xgems')}")
    except Exception:
        print("# xgems   version unknown")

    engine_available = hasattr(xgems, "ChemicalEngine")
    print(f"# ChemicalEngine available: {engine_available}")
    print()
    print("GEMS3K loads, and runs the exports xGEMS publishes (see xgems_cement.py).")
    print("The ClaySor comparison has no export to run: the deposit ships a")
    print("GEM-Selektor database instead.")
    print()
    print("To unblock it, in GEM-Selektor: open the ClaySor project, build the")
    print("system, then File -> Export -> GEMS3K files. Drop the resulting")
    print("`*-dat.lst` beside this script and the comparison becomes available.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
