# GEMS3K on this machine: what it can do today, and what it cannot.
#
# GEM-Selektor is the third reference code, and the one that matters most for
# the cementitious case: it carries multi-site sorption phases and CEMDATA18,
# which is more than either PHREEQC or Reaktoro offers there. Its computational
# core, GEMS3K, is installable and importable:
#
#   conda create -n mpcm-oracles -c conda-forge python=3.12 xgems gems3k
#
# This script reports that it loads, and then states plainly the one thing that
# blocks using it as an oracle right now.
#
# ## The blocker, measured rather than assumed
#
# `xgems.ChemicalEngine` takes a **GEMS3K system export** -- a `*-dat.lst` file
# and the `*.dat` files beside it -- which is produced by GEM-Selektor's
# graphical "Export to GEMS3K" command. It does not read a GEM-Selektor
# *database*.
#
# The ClaySor 2023 deposit (doi:10.5281/zenodo.15095062, CC-BY-4.0) ships a
# database: `dcomp`, `reacdc`, `icomp`, `phase`, `compos` and `sdref` `.pdb`
# files in GEMBASE format. Its readable strings show the whole model -- the ion
# exchangers `MontX` and `IlliteX`, the amphoteric edge layers `MonEdS` and
# `IllEdS`, and their strong (`=Ss`), weak (`=Sw`) and second weak (`=Sv`) sites
# -- but no exported system, so nothing here can run it.
#
# So the comparison the plan wanted from this deposit, PHREEQC against GEMS on
# an *identical* model, is not available without GEM-Selektor itself. That is a
# missing tool, not a missing capability, and it is recorded rather than worked
# around: a tolerance floor invented from a comparison that was not run would be
# worse than no floor at all.
#
# The PHREEQC half of the same deposit *is* directly usable --
# `PHREEQC/claysor23_v0.7.dat` is a database IPhreeqc loads -- so the ClaySor
# model is reachable through one code today, and through two the day a system
# export exists.

import sys


def main() -> int:
    try:
        import xgems
    except Exception as exc:  # pragma: no cover - the whole point is to report
        print(f"xgems does not import: {exc}")
        return 1

    print("# generated by test/reference/gems_bench.py")
    print(f"# python  {sys.version.split()[0]}")
    try:
        from importlib.metadata import version

        print(f"# xgems   {version('xgems')}")
    except Exception:
        print("# xgems   version unknown")

    engine_available = hasattr(xgems, "ChemicalEngine")
    print(f"# ChemicalEngine available: {engine_available}")
    print()
    print("GEMS3K loads. It has no system to run:")
    print("  `ChemicalEngine` needs a GEMS3K export (`*-dat.lst`), and the")
    print("  ClaySor deposit ships a GEM-Selektor database instead.")
    print()
    print("To unblock it, in GEM-Selektor: open the ClaySor project, build the")
    print("system, then File -> Export -> GEMS3K files. Drop the resulting")
    print("`*-dat.lst` beside this script and the comparison becomes available.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
